-- Verifies generate_fk_recovery() emits a path-A script that actually rebuilds a
-- valid composite FK against the partitioned parent.
create extension if not exists pgtap;

begin;
select plan(4);

create table public.fk_parent (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  v          text
);
insert into public.fk_parent (created_at, v)
  values (now() - interval '40 days', 'a'), (now(), 'b');
create table public.fk_child (id bigint primary key, parent_id bigint references public.fk_parent (id));
insert into public.fk_child (id, parent_id) values (1, 1);

-- adopt + drop the incoming FK (records it for recovery)
select pgpm.adopt('public.fk_parent', 'created_at', '1 month', p_incoming_fks => 'drop');

select is(
  (select count(*) from pgpm.generate_fk_recovery('public.fk_parent'))::int,
  1,
  'generate_fk_recovery emits one script for the dropped FK'
);

-- run the generated script (multiple statements) to rebuild the composite FK
select lives_ok(
  $$ do $do$ declare s text; begin
       select sql into s from pgpm.generate_fk_recovery('public.fk_parent');
       execute s;
     end $do$; $$,
  'the generated recovery SQL runs and rebuilds the composite FK'
);

select ok(
  exists (
    select 1 from pg_constraint
     where conrelid = 'public.fk_child'::regclass and contype = 'f'
       and confrelid = 'public.fk_parent'::regclass and convalidated
  ),
  'fk_child now has a validated composite FK to the partitioned parent'
);

select is(
  (select parent_created_at from public.fk_child where id = 1),
  (select created_at from public.fk_parent where id = 1),
  'the companion column was backfilled to the referenced row''s partition key'
);

select * from finish();
rollback;
