-- The drain (REDESIGN.md sections 3, 9): in the monolith model transmute moves no rows (the
-- bulk lands in the monolith, the DEFAULT is born empty), so the drain is no longer the bulk mover --
-- regrain() is. The drain demotes to a sideline: it keeps the DEFAULT empty by evacuating
-- the occasional STRAY (here a backdated row in a closed interval below the monolith) into a proper
-- partition. drain_all is synchronous (ignores pause), so this does not depend on pg_cron.
create extension if not exists pgtap;

begin;
select plan(3);

create table public.dr (
  id bigint generated by default as identity,
  created_at timestamptz not null,
  body text, primary key (created_at, id)
);
insert into public.dr (created_at) select now() - (g || ' minutes')::interval from generate_series(1, 20) g;
select pgpm.transmute('public.dr', 'created_at', interval '1 month', p_paused => false);   -- monolith holds the recent rows; DEFAULT empty
-- a backdated stray lands in the (otherwise empty) DEFAULT, in a closed interval below the monolith
insert into public.dr (created_at, body)
  select date_trunc('month', now()) - interval '3 months' + interval '10 days', 'stray' from generate_series(1, 15) g;

select cmp_ok(
  (select closed_rows from pgpm.check_default('public.dr'))::int,
  '>', 0,
  'a backdated stray lands in the otherwise-empty DEFAULT as a closed interval');

select cmp_ok(
  pgpm.drain_all('public.dr', p_include_open => true),
  '>', 0,
  'the drain performs at least one batch evacuating the stray');

select is(
  (select count(*) from public.dr_default)::int,
  0,
  'the DEFAULT is empty again after the drain');

select * from finish();
rollback;
