-- Attach methods in the monolith model. obtain plain-attaches forward partitions (the DEFAULT is empty,
-- so no exclusion-CHECK dance is needed); the drain attaches a closed stray via the
-- scan-skipping check_skip path (an exclusion CHECK on the DEFAULT, validated then dropped); and no
-- temporary exclusion constraints linger on the DEFAULT afterward.
create extension if not exists pgtap;

begin;
select plan(3);

create table public.am (
  id bigint generated by default as identity,
  created_at timestamptz not null,
  body text, primary key (created_at, id)
);
insert into public.am (created_at) select now() - (g || ' minutes')::interval from generate_series(1, 20) g;
select pgpm.transmute('public.am', 'created_at', interval '1 month', p_paused => false);
select pgpm.obtain('public.am');   -- forward partitions, plain-attached (empty DEFAULT, no scan)
-- a backdated stray for the drain to evacuate via check_skip
insert into public.am (created_at, body)
  select date_trunc('month', now()) - interval '3 months' + interval '10 days', 'stray' from generate_series(1, 10) g;
select pgpm.drain_all('public.am', p_include_open => true);

select cmp_ok(
  (select count(*) from pgpm.log where parent_table = 'public.am'::regclass and action = 'obtain' and method = 'plain')::int,
  '>', 0,
  'obtain plain-attaches forward partitions (empty DEFAULT, no scan)');

select cmp_ok(
  (select count(*) from pgpm.log where parent_table = 'public.am'::regclass and action = 'drain_attach' and method = 'check_skip')::int,
  '>', 0,
  'the drain attaches a closed stray via the scan-skipping check_skip path');

select is(
  (select count(*) from pg_constraint
    where conrelid = 'public.am_default'::regclass and conname ~ '_excl$')::int,
  0,
  'temporary exclusion CHECK constraints were dropped after attach');

select * from finish();
rollback;
