-- Retention in the monolith model, and retention-aware refine. While history is one coarse monolith
-- spanning the horizon, retain() cannot drop it (retention is suspended over coarse history). refine() is
-- retention-aware: it materializes only the within-horizon sub-ranges and RECLAIMS the ones entirely
-- below the horizon (it skips the copy; their rows are dropped with the coarse source), so no doomed
-- partition is ever created and a later retain() has nothing to do. Mirrors the drain's retain_reclaim
-- (issue #91).
create extension if not exists pgtap;

begin;
select plan(6);

create table public.rt7 (id bigint generated by default as identity primary key, payload text);
insert into public.rt7 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
select pgpm.transmute('public.rt7', 'id', 10000, p_retain => 30000);   -- monolith [0, 60000); retain 30000 ids
select pgpm.obtain('public.rt7');
insert into public.rt7 (id, payload) values (65000, 'frontier');   -- frontier=65000 -> monolith frozen; horizon boundary = 30000

select is(
  pgpm.retain('public.rt7'),
  0, 'retention is suspended over the coarse monolith (a partition spanning the horizon cannot be dropped)');

select is(
  (select pgpm.refine_history('public.rt7'))::int,
  3, 'retention-aware refine materializes only the 3 within-horizon sub-ranges [30000, 60000)');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.rt7'::regclass and action = 'refine_reclaim'),
  3, 'the 3 below-horizon sub-ranges are reclaimed (logged refine_reclaim), never materialized');

select is(
  (select count(*)::int from public.rt7 where id < 30000),
  0, 'the aged rows below the horizon are reclaimed (dropped with the coarse source), never copied');

select is(
  pgpm.retain('public.rt7'),
  0, 'a later retain() is a no-op: refine already reclaimed the aged ranges (no materialize-then-drop churn)');

select ok(
  to_regclass('public.rt7_p' || lpad('0', 19, '0')) is null
    and to_regclass('public.rt7_p' || lpad('30000', 19, '0')) is not null,
  'no doomed aged fine child was materialized; the within-horizon children exist');

select * from finish();
rollback;
