-- adopt() refuses a table with incoming foreign keys by default; p_incoming_fks => 'preserve' drops
-- and records them so the conversion can proceed (restore_incoming_fks re-adds them later). The table
-- partitions on its own id primary key -- pgpm never rewrites the PK, so the FK is preservable.
create extension if not exists pgtap;

begin;
select plan(5);

-- a fresh parent (partitioned on its own id PK) with an INCOMING foreign key from another table
create table public.fk_parent (
  id bigint generated by default as identity primary key,
  v  text
);
insert into public.fk_parent (v) values ('a'), ('b');
create table public.fk_child (
  id        bigint primary key,
  parent_id bigint references public.fk_parent (id)
);

-- (1) default: adopt refuses while the incoming FK exists (RAISE => SQLSTATE P0001)
select throws_ok(
  $$ select pgpm.adopt('public.fk_parent', 'id', 100000) $$,
  'P0001', null,
  'adopt() refuses a table with incoming foreign keys by default'
);

-- (2) the refusal mutated nothing: the FK is still there
select ok(
  exists (select 1 from pg_constraint
           where confrelid = 'public.fk_parent'::regclass and contype = 'f'),
  'incoming FK is left intact after the refusal'
);

-- (3) with p_incoming_fks => preserve: the conversion succeeds
select lives_ok(
  $$ select pgpm.adopt('public.fk_parent', 'id', 100000, p_incoming_fks => 'preserve') $$,
  'adopt(..., p_incoming_fks => ''preserve'') succeeds'
);

-- (4) the incoming FK was dropped for the conversion
select is(
  (select count(*) from pg_constraint
    where confrelid = 'public.fk_parent'::regclass and contype = 'f')::int,
  0,
  'the incoming FK was dropped for the conversion'
);

-- (5) and recorded for restoration
select cmp_ok(
  (select count(*) from pgpm.dropped_fk
    where referencing_table = 'public.fk_child'::regclass)::int,
  '>=', 1,
  'the dropped FK was recorded in pgpm.dropped_fk'
);

select * from finish();
rollback;
