-- Verifies adopt() refuses a table with incoming foreign keys by default, and
-- with p_incoming_fks => 'drop' drops and records them so the swap can proceed.
create extension if not exists pgtap;

begin;
select plan(5);

-- a fresh parent with an INCOMING foreign key from another table
create table public.fk_parent (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  v          text
);
insert into public.fk_parent (created_at, v)
  values (now() - interval '40 days', 'a'), (now(), 'b');
create table public.fk_child (
  id        bigint primary key,
  parent_id bigint references public.fk_parent (id)
);

-- (1) default: adopt refuses while the incoming FK exists (RAISE => SQLSTATE P0001)
select throws_ok(
  $$ select pgpm.adopt('public.fk_parent', 'created_at', '1 month') $$,
  'P0001', null,
  'adopt() refuses a table with incoming foreign keys by default'
);

-- (2) the refusal mutated nothing: the FK is still there
select ok(
  exists (select 1 from pg_constraint
           where confrelid = 'public.fk_parent'::regclass and contype = 'f'),
  'incoming FK is left intact after the refusal'
);

-- (3) with p_incoming_fks => drop: the swap succeeds
select lives_ok(
  $$ select pgpm.adopt('public.fk_parent', 'created_at', '1 month', p_incoming_fks => 'drop') $$,
  'adopt(..., p_incoming_fks => ''drop'') succeeds'
);

-- (4) the incoming FK was dropped
select is(
  (select count(*) from pg_constraint
    where confrelid = 'public.fk_parent'::regclass and contype = 'f')::int,
  0,
  'the incoming FK was dropped'
);

-- (5) and recorded for later reconstruction
select cmp_ok(
  (select count(*) from pgpm.dropped_fk
    where referencing_table = 'public.fk_child'::regclass)::int,
  '>=', 1,
  'the dropped FK was recorded in pgpm.dropped_fk'
);

select * from finish();
rollback;
