-- maintain_obtain's back-off must not outlast the forward grid.
--
-- A lock-timeout deferral sets config.obtain_retry_after, and maintain_obtain skips obtain until it passes,
-- so sustained write contention does not retry an ACCESS EXCLUSIVE every tick. That was harmless while a
-- DEFAULT partition caught writes past the grid; since #288 such a write is refused. A fixed 30 s back-off
-- measured on a local load test (~42k ids/s, obtain 3 x step 200000 = ~14 s of lookahead) let the grid run
-- out mid back-off and every client abort. The rule under test: the back-off is honored only while at least
-- ceil(obtain / 2) complete partitions remain ahead of the frontier's own partition; below that, obtain runs.
--
-- The back-off is set by hand (an hour out) instead of provoked with a real lock race: what matters here is
-- the decision, and bench/obtain_backoff_headroom.sh covers the real race end to end.
--
-- Grid for public.ob, all literals checked by the preconditions below: step 1000, obtain 4, 500 rows, so the
-- monolith is [0, 1000) and transmute's lookahead runs to 5000 (5 partitions).
--   case 1: frontier id 2001 -> partition [2000, 3000); 2 complete partitions ahead ([3000,4000), [4000,5000))
--           -> 2 is not < ceil(4/2) = 2 -> back-off honored, nothing created, even though obtain WOULD create 2.
--   case 2: frontier id 5001 -> partition [5000, 6000); 1 ahead ([6000,7000)) -> 1 < 2 -> obtain runs despite
--           the back-off, creating [7000,8000), [8000,9000), [9000,10000) and clearing obtain_retry_after.
--
-- Headroom is attached COVERAGE, not a count of partitions that start past the frontier. transmute's
-- p_bound_headroom gives the monolith a permanent hi several grid steps beyond the frontier, and those steps
-- are safe room even though the monolith's lo is far behind. public.obh: same grid, p_bound_headroom => 4, so
-- the monolith is [0, 5000) and nothing else is attached (every obtain candidate overlaps it).
--   case 3: frontier id 1001 -> [1000, 2000); [2000,3000), [3000,4000), [4000,5000) are covered inside the
--           monolith -> 3 is not < 2 -> back-off honored, nothing created (obtain WOULD create [5000,6000)).
--   case 4: frontier id 4001 -> [4000, 5000); only [5000,6000) is covered beyond it -> 1 < 2 -> obtain runs,
--           creating [6000,7000), [7000,8000), [8000,9000).
create extension if not exists pgtap;

select plan(17);

create table public.ob (id bigint generated by default as identity primary key, body text);
insert into public.ob (body) select 'x' from generate_series(1, 500);
call pgpm.transmute('public.ob', 'id', 1000::bigint, 4, p_paused => false);

select is((select count(*)::int from pgpm.part where parent_table = 'public.ob'::regclass and attached), 5,
  'precondition: monolith [0,1000) plus 4 forward partitions');
select is((select max(hi::numeric) from pgpm.part where parent_table = 'public.ob'::regclass and attached), 5000::numeric,
  'precondition: the grid top is 5000');

-- ---------------------------------------------------------------- case 1: ample headroom, back-off holds
insert into public.ob (id, body) values (2001, 'case 1 frontier');
update pgpm.config set obtain_retry_after = clock_timestamp() + interval '1 hour' where parent_table = 'public.ob'::regclass;
do $$ declare s text; begin call pgpm.maintain_obtain('public.ob', s); end $$;

select is((select count(*)::int from pgpm.part where parent_table = 'public.ob'::regclass and attached), 5,
  'case 1: 2 partitions still ahead (not < ceil(4/2)) -> back-off honored, nothing created');
select isnt((select obtain_retry_after from pgpm.config where parent_table = 'public.ob'::regclass), null,
  'case 1: the back-off is still in place');

-- liveness witness for case 1: the same tick with the back-off cleared DOES create partitions, so the
-- "nothing created" above was the back-off, not an idle obtain.
update pgpm.config set obtain_retry_after = null where parent_table = 'public.ob'::regclass;
do $$ declare s text; begin call pgpm.maintain_obtain('public.ob', s); end $$;
select is((select count(*)::int from pgpm.part where parent_table = 'public.ob'::regclass and attached), 7,
  'case 1 witness: without the back-off the same tick creates [5000,6000) and [6000,7000)');
select ok(exists (select 1 from pgpm.part where parent_table = 'public.ob'::regclass and attached
                   and lo::numeric = 6000 and hi::numeric = 7000),
  'case 1 witness: [6000,7000) exists');

-- ---------------------------------------------------------------- case 2: headroom low, back-off bypassed
insert into public.ob (id, body) values (5001, 'case 2 frontier');
update pgpm.config set obtain_retry_after = clock_timestamp() + interval '1 hour' where parent_table = 'public.ob'::regclass;
do $$ declare s text; begin call pgpm.maintain_obtain('public.ob', s); end $$;

select is((select count(*)::int from pgpm.part where parent_table = 'public.ob'::regclass and attached), 10,
  'case 2: only 1 partition ahead (< ceil(4/2)) -> obtain runs despite the back-off, creating 3');
select ok(exists (select 1 from pgpm.part where parent_table = 'public.ob'::regclass and attached
                   and lo::numeric = 9000 and hi::numeric = 10000),
  'case 2: the grid now reaches [9000,10000)');
select is((select obtain_retry_after from pgpm.config where parent_table = 'public.ob'::regclass), null,
  'case 2: a successful obtain clears the back-off');
select lives_ok($$ insert into public.ob (id, body) values (9999, 'past the old top') $$,
  'case 2: a write at 9999, past the pre-tick grid top of 7000, is accepted');

-- ---------------------------------------------------------------- p_bound_headroom: coverage inside the monolith
create table public.obh (id bigint generated by default as identity primary key, body text);
insert into public.obh (body) select 'x' from generate_series(1, 500);
call pgpm.transmute('public.obh', 'id', 1000::bigint, 4, p_paused => false, p_bound_headroom => 4);

select is((select count(*)::int from pgpm.part where parent_table = 'public.obh'::regclass and attached), 1,
  'headroom precondition: the monolith is the only attached partition');
select ok(exists (select 1 from pgpm.part where parent_table = 'public.obh'::regclass and attached
                   and lo::numeric = 0 and hi::numeric = 5000),
  'headroom precondition: the monolith is [0,5000)');

-- case 3: 3 complete steps covered inside the monolith beyond the frontier's cell
insert into public.obh (id, body) values (1001, 'case 3 frontier');
update pgpm.config set obtain_retry_after = clock_timestamp() + interval '1 hour' where parent_table = 'public.obh'::regclass;
do $$ declare s text; begin call pgpm.maintain_obtain('public.obh', s); end $$;

select is((select count(*)::int from pgpm.part where parent_table = 'public.obh'::regclass and attached), 1,
  'case 3: 3 steps still covered inside the monolith (not < ceil(4/2)) -> back-off honored, nothing created');
select isnt((select obtain_retry_after from pgpm.config where parent_table = 'public.obh'::regclass), null,
  'case 3: the back-off is still in place');

-- liveness witness for case 3: with the back-off cleared, the same tick does create [5000,6000)
update pgpm.config set obtain_retry_after = null where parent_table = 'public.obh'::regclass;
do $$ declare s text; begin call pgpm.maintain_obtain('public.obh', s); end $$;
select is((select count(*)::int from pgpm.part where parent_table = 'public.obh'::regclass and attached), 2,
  'case 3 witness: without the back-off the same tick creates [5000,6000)');

-- case 4: only 1 step covered beyond the frontier's cell
insert into public.obh (id, body) values (4001, 'case 4 frontier');
update pgpm.config set obtain_retry_after = clock_timestamp() + interval '1 hour' where parent_table = 'public.obh'::regclass;
do $$ declare s text; begin call pgpm.maintain_obtain('public.obh', s); end $$;

select is((select count(*)::int from pgpm.part where parent_table = 'public.obh'::regclass and attached), 5,
  'case 4: 1 step covered beyond the frontier (< ceil(4/2)) -> obtain runs despite the back-off, creating 3');
select is((select obtain_retry_after from pgpm.config where parent_table = 'public.obh'::regclass), null,
  'case 4: a successful obtain clears the back-off');

select * from finish();
