-- pgpm.progress(): the freeze forecast, and regrain_to on status() (issue #343, gaps 1 and 2).
--
-- THE GAP. After transmute the whole history sits in one coarse monolith that keeps taking writes until
-- the frontier crosses its upper bound `hi`, and regrain cannot start until then. Answering "when will
-- it freeze" meant hand-deriving `hi` from _grid_floor/_grid_next, p_anchor and p_bound_headroom, and
-- reading pgpm.part directly. In production that arithmetic hid a two-hour mixup between the anchor an
-- operator intended and the one actually used. progress() surfaces the child taking writes, its
-- ceiling, and the margin to it, read off pgpm.part and the frontier rather than re-derived.
--
-- THE HONESTY CONSTRAINT. For the three time-grid kinds the frontier is a timestamptz (now(), or
-- greatest(max(control), now())), so `hi - frontier` is an interval and freeze_in is plain arithmetic.
-- For `id` the frontier is max(control) and pgpm keeps no history of it, so there is no rate to
-- extrapolate a time from; progress() returns the raw margin (a count) and NULL for freeze_in. That
-- NULL is the contract, and it is asserted explicitly here, next to the margin that proves a forecast
-- WAS available to guess at.
--
-- Fixtures are asymmetric on purpose: the time table carries 2 steps of headroom (so the ceiling is
-- visibly not where a headroom-unaware operator would put it), the id table carries none.
create extension if not exists pgtap;
select plan(37);

-- ================================ (A) time grid: freeze_in is arithmetic ================================
create table public.fz_time (
  ts timestamptz not null, id bigint generated by default as identity, payload text,
  primary key (ts, id)
);
insert into public.fz_time (ts, payload) select now() - (g || ' hours')::interval, 'x' from generate_series(1, 72) g;
call pgpm.transmute('public.fz_time', 'ts', interval '1 day', p_bound_headroom => 2);
select pgpm.obtain('public.fz_time');

select child_name as time_mono from pgpm.part
  where parent_table = 'public.fz_time'::regclass and attached order by lo::timestamptz limit 1 \gset

-- LIVENESS: a forecast is only meaningful if there is a coarse child, and the frontier is inside it.
select ok(
  (select pgpm._native_gt('time', hi, pgpm._grid_next('time', '1 day', lo)) from pgpm.part
    where parent_table = 'public.fz_time'::regclass and child_name = :'time_mono'),
  'LIVENESS: the time monolith is coarse (wider than one step), so there is a freeze to forecast');
select ok(
  (select now() >= lo::timestamptz and now() < hi::timestamptz from pgpm.part
    where parent_table = 'public.fz_time'::regclass and child_name = :'time_mono'),
  'LIVENESS: the frontier (now()) sits inside the monolith, so it is the child taking writes');

select is(write_child, :'time_mono'::name,
  'time: write_child is the monolith, by name') from pgpm.progress('public.fz_time');
select is(write_ceiling,
  (select hi from pgpm.part where parent_table = 'public.fz_time'::regclass and child_name = :'time_mono'),
  'time: write_ceiling is the monolith''s hi -- the bound actually in force, headroom included')
  from pgpm.progress('public.fz_time');
select is(frontier::timestamptz, now(),
  'time: the frontier is now()') from pgpm.progress('public.fz_time');
select is(freeze_in, write_ceiling::timestamptz - now(),
  'time: freeze_in is exactly write_ceiling - frontier') from pgpm.progress('public.fz_time');
-- Without headroom the monolith would freeze within a day. The 2 extra steps push that past 2 days, and
-- that is the figure an operator who assumed no headroom would have got wrong by two days.
select ok(freeze_in > interval '2 days' and freeze_in <= interval '3 days',
  'time: the 2-step headroom is visible in the forecast (freeze_in in (2 days, 3 days], not under 1 day)')
  from pgpm.progress('public.fz_time');
select is(freeze_margin, freeze_in::text,
  'time: freeze_margin is the same interval, as text') from pgpm.progress('public.fz_time');
select is(coarse_frozen, 0::bigint,
  'time: no coarse child is frozen while the monolith still takes writes') from pgpm.progress('public.fz_time');
select ok(regrain_child is null and regrain_cursor is null and regrain_pct_range is null and regrain_eta is null,
  'time: no regrain in flight, so every in-flight column is null') from pgpm.progress('public.fz_time');

-- ================================ (B) id grid: a margin, and NO time estimate ================================
create table public.fz_id (id bigint primary key, payload text);
insert into public.fz_id select g, 'x' from generate_series(1, 5000) g;
call pgpm.transmute('public.fz_id', 'id', 1000);
select pgpm.obtain('public.fz_id');

select child_name as id_mono from pgpm.part
  where parent_table = 'public.fz_id'::regclass and attached order by lo::numeric limit 1 \gset

-- both sides cast: is() is polymorphic, and two bare literals resolve to `unknown`
select is(:'id_mono'::text, 'fz_id_p0000000000000000000_to_0000000000000006000'::text,
  'GUARD: the id monolith is [0, 6000) as the literals below assume');

select is(frontier, '5000', 'id: the frontier is max(id)') from pgpm.progress('public.fz_id');
select is(write_child, :'id_mono'::name, 'id: write_child is the monolith') from pgpm.progress('public.fz_id');
select is(write_ceiling, '6000', 'id: write_ceiling is the monolith''s hi') from pgpm.progress('public.fz_id');
select is(freeze_margin, '1000',
  'id: freeze_margin is the count of ids left before the ceiling (6000 - 5000)') from pgpm.progress('public.fz_id');
-- The negative, paired with the margin above that proves there WAS a ceiling to forecast against.
select is(freeze_in, null::interval,
  'id: freeze_in is NULL -- an id frontier has no clock, so pgpm does not guess a time') from pgpm.progress('public.fz_id');
select is(coarse_frozen, 0::bigint, 'id: nothing is frozen yet') from pgpm.progress('public.fz_id');

insert into public.fz_id values (5500, 'later');
select is(freeze_margin, '500',
  'id: the margin shrinks by exactly the frontier''s advance (frontier 5500, 500 left)') from pgpm.progress('public.fz_id');

insert into public.fz_id values (6500, 'past the ceiling');
select is(write_child, 'fz_id_p0000000000000006000'::name,
  'id: once the frontier crosses the ceiling, write_child is the fine forward partition') from pgpm.progress('public.fz_id');
select is(write_ceiling, '7000', 'id: and the ceiling is that partition''s hi') from pgpm.progress('public.fz_id');
select is(coarse_frozen, 1::bigint,
  'id: the monolith now counts as a frozen coarse child, eligible for regrain') from pgpm.progress('public.fz_id');
select is(freeze_in, null::interval,
  'id: freeze_in stays NULL for the fine child too -- no clock, no forecast') from pgpm.progress('public.fz_id');

-- ====================== (C) uuidv7 (fixture events_uuid): a data-fed time grid ======================
select ok(write_child is not null,
  'uuidv7: WITNESS -- a child is taking writes, so the two assertions below are not vacuous')
  from pgpm.progress('public.events_uuid');
select ok(frontier::timestamptz >= now(),
  'uuidv7: the frontier is greatest(max(id), now()), so it is never behind the clock')
  from pgpm.progress('public.events_uuid');
select is(freeze_in, write_ceiling::timestamptz - frontier::timestamptz,
  'uuidv7: freeze_in is exactly write_ceiling - frontier, plain arithmetic on a data-fed time grid')
  from pgpm.progress('public.events_uuid');

-- ================================ (D) regrain_to on status() (gap 2) ================================
-- Asymmetric: on for one table, off for the other, so a column that always read the same value fails.
select pgpm.set_regrain('public.fz_id', '1000');
select is((select regrain_to from pgpm.status() where parent = 'public.fz_id'::regclass), '1000',
  'status().regrain_to surfaces the auto-regrain target');
select is((select regrain_to from pgpm.status() where parent = 'public.fz_time'::regclass), null::text,
  'and is null for a table with auto-regrain off');
select is((select regrain_to from pgpm.progress('public.fz_id')), '1000',
  'progress().regrain_to carries the same value, so the drill-down needs no join');
select pgpm.set_regrain('public.fz_id', null);

-- ================================ (E) the argument ================================
select is((select count(*)::int from pgpm.progress('public.fz_id')), 1,
  'progress(p_parent) returns exactly that table''s row');
select is((select count(*)::int from pgpm.progress()), (select count(*)::int from pgpm.config),
  'progress() with no argument returns one row per managed table');
create table public.fz_unmanaged (id int);
select throws_like($$ select * from pgpm.progress('public.fz_unmanaged') $$, '%is not managed%',
  'progress() on an unmanaged table refuses by name rather than returning nothing');

-- ============ (F) a parent dropped without untransmute: report it, do not die (the status() lesson) ============
-- id WITH retention: the combination whose frontier read reaches the relation (see tests/79).
create table public.fz_gone (id bigint primary key, payload text);
insert into public.fz_gone select g, 'x' from generate_series(1, 5000) g;
call pgpm.transmute('public.fz_gone', 'id', 1000, p_retain => 3000);
select ('public.fz_gone'::regclass)::oid as gone_oid \gset
drop table public.fz_gone cascade;

-- LIVENESS: every assertion below is satisfied by a run where the dangling row never existed.
select is(
  (select count(*)::int from pgpm.config where parent_table::oid = :gone_oid
     and not exists (select 1 from pg_class c where c.oid = :gone_oid)),
  1, 'LIVENESS: the dropped parent''s config row is still there, pointing at an oid with no relation');

select is((select count(*)::int from pgpm.progress()), (select count(*)::int from pgpm.config),
  'progress() still returns a row for EVERY managed table with a dead parent among them');
select is((select parent_missing from pgpm.progress() where parent::oid = :gone_oid), true,
  'the dead parent is flagged parent_missing');
select ok(frontier is null and write_child is null and write_ceiling is null and freeze_in is null and coarse_frozen is null,
  'and every frontier-derived column is null for it: there is no relation to read a frontier from')
  from pgpm.progress() where parent::oid = :gone_oid;
select ok(not parent_missing and frontier is not null and coarse_frozen is not null,
  'while the healthy table''s row is still fully computed -- progress() degrades per row, not wholesale')
  from pgpm.progress('public.fz_id');
select is((select count(*)::int from pgpm.progress(:gone_oid::regclass)), 1,
  'progress(oid) addresses the dead row directly, by the oid that is all that remains of it');

drop table if exists public.fz_time, public.fz_id, public.fz_unmanaged cascade;

select * from finish();
