-- p_retain cannot be negative (issue #451).
--
-- Neither transmute overload checked the sign of p_retain. A negative interval or count put the retention
-- horizon in the FUTURE: _retain_boundary subtracts retain from the frontier and nothing downstream
-- questioned a boundary above it, so on the next tick _enforce_write_blocks blocked every partition and
-- retain() dropped them all, the monolith and the partition taking writes included. The next insert failed
-- with `no partition of relation ... found for row`. A sign typo was all it took. set_retain caught a
-- negative value only through its would-drop guard, which compares boundaries, so a value whose boundary
-- grid-floored to the same place as the current one slipped straight through and armed a later tick.
--
-- ZERO IS NOT THE DEFECT. retain 0 puts the horizon at grid_floor(frontier), the write partition's own
-- floor; that partition has hi > boundary, so it is never eligible, and zero means "keep only the partition
-- taking writes, everything behind it is aged" (tests/63 relies on exactly that). Only a negative value puts
-- the horizon PAST the write partition, so only a negative value is refused. Zero is asserted ACCEPTED here
-- at both entry points and for both kinds, with a tick showing what it does.
--
-- Three layers, each pinned here:
--   (A) both transmute overloads refuse a negative p_retain BEFORE anything is committed (time and id);
--   (B) set_retain refuses a negative p_retain unconditionally (time and id), including the value the
--       would-drop guard alone cannot see;
--   (C) defence in depth for a config.retain edited by hand: _retain_boundary and regrain_step refuse to
--       compute a horizon from it, so a tick logs skip_write_block / skip_retain (exact actions) and drops
--       nothing, status() stays alive, and set_retain can still repair it.
-- Plus the positive controls that show none of this is a blanket refusal: zero and a retain SHORTER than one
-- partition_step are both accepted, and the tick drops exactly the aged partitions while keeping the one
-- holding the frontier. In those fixtures the horizon lands exactly ON the frontier partition's grid floor,
-- which is the case an "at or above the frontier's floor" check would have wrongly refused.
--
-- WHICH ASSERTIONS DISCRIMINATE (the tests/83 caveat): throws_like wraps the CALL in a function, and a
-- committing procedure cannot commit inside one, so against pre-fix code the transmute CALLs in (A) die at
-- phase 1's COMMIT with 2D000. The throws_like fails on the message, for the right reason, but the
-- untouched-table assertions right after it pass pre-fix too; read them as the post-fix contract (refused
-- before any COMMIT), not as the proof. Section (C) is where pre-fix code shows the actual data loss: every
-- partition dropped, every row gone, and regrain discarding every sub-range as aged.
create extension if not exists pgtap;
select plan(70);

create schema pgpm_test108;

-- ======================= (A) transmute refuses a negative p_retain, accepts zero: time =======================
create table public.rs108t (id bigint generated by default as identity, ts timestamptz not null, payload text,
  primary key (ts, id));
insert into public.rs108t (ts, payload)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 100) g;

select throws_like(
  $$ call pgpm.transmute('public.rs108t', 'ts', interval '1 day', p_retain => interval '-1 day', p_paused => false, p_obtain => 3) $$,
  '%cannot be negative%', 'transmute (time) refuses a negative p_retain with the pgpm message');

-- refused up front: nothing committed, nothing left on the table for the operator to clean up
select is((select relkind::text from pg_class where oid = 'public.rs108t'::regclass), 'r',
  'the time table is untouched');
select is((select count(*) from pgpm.config where parent_table = 'public.rs108t'::regclass), 0::bigint,
  'the time table was not registered');
select is((select count(*) from pgpm.transmute_inflight), 0::bigint,
  'no claim was recorded');
select ok(not exists (select 1 from pg_constraint
                       where conrelid = 'public.rs108t'::regclass and conname = 'pgpm_monolith_bound'),
  'no bound CHECK was left behind');

-- LIVENESS WITNESS and positive control: the identical call with retain ZERO succeeds. Without this the
-- refusal above would pass against a build where transmute is broken for any reason at all.
call pgpm.transmute('public.rs108t', 'ts', interval '1 day', p_retain => interval '0', p_paused => false, p_obtain => 3);

select is((select relkind::text from pg_class where oid = 'public.rs108t'::regclass), 'p',
  'the same call succeeds with retain = 0');
select is((select retain from pgpm.config where parent_table = 'public.rs108t'::regclass), '00:00:00',
  'config.retain holds the zero retain');
-- zero puts the horizon exactly on the write partition's own floor, grid_floor(now()); that partition has
-- hi > boundary and is never eligible
select is(
  (select pgpm._retain_boundary(c) from pgpm.config c where c.parent_table = 'public.rs108t'::regclass),
  pgpm._grid_floor('time', '1 day', '2000-01-01 00:00:00+00', now()::text, 'UTC'),
  'retain 0 puts the horizon exactly on the frontier partition''s grid floor');

select child_name as t_write from pgpm.part
  where parent_table = 'public.rs108t'::regclass and attached
    and not pgpm._native_gt('time', lo, now()::text) and pgpm._native_gt('time', hi, now()::text) \gset

call pgpm.maintain('public.rs108t') \gset
select ok(:'p_status' like 'archived=0 dropped=0%' and :'p_status' not like '%deferred%',
  'a tick against retain 0 defers nothing and, with nothing behind the write partition on a fresh time grid, drops nothing: ' || :'p_status');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rs108t'::regclass and action in ('skip_write_block', 'skip_retain')),
  0, 'no skip_write_block / skip_retain was logged for retain 0');
select ok(
  (select attached from pgpm.part where parent_table = 'public.rs108t'::regclass and child_name = :'t_write'),
  'the partition holding now() survives the tick');
select lives_ok(
  $$ insert into public.rs108t (ts, payload) values (now(), 'live') $$,
  'the time table is live: a write at now() is accepted');
select is((select count(*) from public.rs108t), 101::bigint,
  'and it landed');

-- ======================= (A) transmute refuses a negative p_retain, accepts zero: id =======================
create table public.rs108i (id bigint generated by default as identity primary key, payload text);
insert into public.rs108i (payload) select 'x' from generate_series(1, 7);   -- ids 1..7

select throws_like(
  $$ call pgpm.transmute('public.rs108i', 'id', 1000, p_retain => -1000, p_paused => false) $$,
  '%cannot be negative%', 'transmute (id) refuses a negative p_retain with the pgpm message');
select is((select relkind::text from pg_class where oid = 'public.rs108i'::regclass), 'r',
  'the id table is untouched');
select is((select count(*) from pgpm.config where parent_table = 'public.rs108i'::regclass), 0::bigint,
  'the id table was not registered');

-- LIVENESS WITNESS and positive control: retain ZERO. Monolith [0, 1000) holds ids 1..7; [1000, 2000) gets
-- three rows; the frontier row 2500 lands in [2000, 3000). Zero means: keep [2000, 3000), everything behind
-- it is aged.
call pgpm.transmute('public.rs108i', 'id', 1000, p_retain => 0, p_paused => false);
insert into public.rs108i (id, payload) select g, 'y' from generate_series(1001, 1003) g;
insert into public.rs108i (id, payload) values (2500, 'frontier');

select child_name as i_mono from pgpm.part where parent_table = 'public.rs108i'::regclass and lo = '0' \gset
select child_name as i_sib  from pgpm.part where parent_table = 'public.rs108i'::regclass and lo = '1000' \gset
select child_name as i_live from pgpm.part where parent_table = 'public.rs108i'::regclass and lo = '2000' \gset

select is((select retain from pgpm.config where parent_table = 'public.rs108i'::regclass), '0',
  'the same call succeeds with retain = 0');
-- boundary = floor(2500 - 0) = 2000 = floor(frontier): the horizon is the write partition's own floor.
-- Everything with hi <= 2000 is aged; [2000, 3000) itself is not.
select is(
  (select pgpm._retain_boundary(c) from pgpm.config c where c.parent_table = 'public.rs108i'::regclass),
  pgpm._grid_floor('id', '1000', '0', pgpm._frontier_native('public.rs108i'), 'UTC'),
  'retain 0 lands the horizon exactly on the frontier partition''s grid floor');
select is(
  (select pgpm._retain_boundary(c) from pgpm.config c where c.parent_table = 'public.rs108i'::regclass),
  '2000', 'and that floor is 2000');

call pgpm.maintain('public.rs108i') \gset
select ok(:'p_status' like 'archived=0 dropped=2%' and :'p_status' not like '%deferred%',
  'the tick drops the two partitions behind the write partition and defers nothing: ' || :'p_status');
select is(
  (select array_agg(lo order by lo::numeric) from pgpm.log
    where parent_table = 'public.rs108i'::regclass and action = 'retain_drop'),
  array['0', '1000'], 'retain_drop was logged for exactly [0, 1000) and [1000, 2000)');
select ok(to_regclass(format('public.%I', :'i_mono')) is null and to_regclass(format('public.%I', :'i_sib')) is null,
  'the two aged partitions are gone');
select ok(
  (select attached from pgpm.part where parent_table = 'public.rs108i'::regclass and child_name = :'i_live'),
  'the partition holding the frontier survives: zero keeps exactly it');
select is((select array_agg(id order by id) from public.rs108i), array[2500]::bigint[],
  'exactly the frontier row survives; the aged rows went with their partitions (the legitimate policy)');
select lives_ok(
  $$ insert into public.rs108i (id, payload) values (2501, 'still live') $$,
  'the id table is live: a write at the frontier is accepted');
select is((select array_agg(id order by id) from public.rs108i), array[2500, 2501]::bigint[],
  'and it landed');

-- ======================= (B) set_retain refuses a negative p_retain, accepts zero =======================
-- time (config.retain is 0)
select throws_like(
  $$ select pgpm.set_retain('public.rs108t', '-1 day') $$,
  '%cannot be negative%', 'set_retain (time) refuses a negative p_retain');
select is((select retain from pgpm.config where parent_table = 'public.rs108t'::regclass), '00:00:00',
  'the refused call left the time table''s config.retain untouched');
-- a positive retain SHORTER than one partition_step is accepted (loosening from zero)
select lives_ok(
  $$ select pgpm.set_retain('public.rs108t', '1 hour') $$,
  'set_retain (time) accepts a positive retain shorter than the 1 day step');
select is((select retain from pgpm.config where parent_table = 'public.rs108t'::regclass), '1 hour',
  'config.retain was updated to 1 hour (set_retain stores the text as given; transmute stores the cast interval)');
-- its horizon sits at or below the grid floor of now(): "at" is legitimate (retain 1 hour at 15:00 floors to
-- today 00:00, as does now()), and it is never past the write partition
select ok(
  not pgpm._native_gt('time',
    (select pgpm._retain_boundary(c) from pgpm.config c where c.parent_table = 'public.rs108t'::regclass),
    pgpm._grid_floor('time', '1 day', '2000-01-01 00:00:00+00', now()::text, 'UTC')),
  'a sub-step retain puts the horizon at or below the frontier partition''s floor, never past it');
-- and back to zero: the horizon returns to the write partition's floor, which newly drops nothing
select lives_ok(
  $$ select pgpm.set_retain('public.rs108t', '0') $$,
  'set_retain (time) accepts zero');
select is((select retain from pgpm.config where parent_table = 'public.rs108t'::regclass), '0',
  'config.retain was updated to 0');

-- id (config.retain is 0, frontier 2501): THE WOULD-DROP GUARD'S BLIND SPOT. The current boundary is
-- floor(2501) = 2000. A retain of -400 gives floor(2901) = 2000: the same boundary, so nothing is newly
-- eligible and the guard alone would have ACCEPTED it. Then the frontier crosses 3000 and the -400 horizon
-- jumps to floor(3400) = 3000, dropping the partition the frontier is in. The sign check is what refuses it.
select throws_like(
  $$ select pgpm.set_retain('public.rs108i', '-400') $$,
  '%cannot be negative%', 'set_retain (id) refuses a negative p_retain whose boundary equals the current one');
select is((select retain from pgpm.config where parent_table = 'public.rs108i'::regclass), '0',
  'the refused call left the id table''s config.retain untouched');
select lives_ok(
  $$ select pgpm.set_retain('public.rs108i', '500') $$,
  'set_retain (id) accepts a positive retain shorter than the 1000 step');
select is((select retain from pgpm.config where parent_table = 'public.rs108i'::regclass), '500',
  'config.retain was updated to 500');
select is(
  (select pgpm._retain_boundary(c) from pgpm.config c where c.parent_table = 'public.rs108i'::regclass),
  '2000', 'retain 500 at a frontier of 2501 lands on the same floor zero did: 2000');
select lives_ok(
  $$ select pgpm.set_retain('public.rs108i', '0') $$,
  'set_retain (id) accepts zero (same boundary, nothing newly eligible)');
select is((select retain from pgpm.config where parent_table = 'public.rs108i'::regclass), '0',
  'config.retain was updated to 0');

-- what zero does after set_retain, too: the write partition survives a tick
call pgpm.maintain('public.rs108i') \gset
select ok(:'p_status' like 'archived=0 dropped=0%' and :'p_status' not like '%deferred%',
  'a tick against retain 0, with nothing left behind the write partition, drops nothing and defers nothing: ' || :'p_status');
select ok(
  (select attached from pgpm.part where parent_table = 'public.rs108i'::regclass and child_name = :'i_live'),
  'the partition holding the frontier survives the tick under retain 0');

-- ======================= (C) defence in depth: a config.retain written by hand =======================
-- The issue's shape: obtain 3, so the grid is [0, 1000) with ids 1..7, [1000, 2000) with 3 rows, [2000, 3000)
-- empty and [3000, 4000) holding the frontier row 3500. With the legitimate retain of 1500 the boundary is
-- floor(2000) = 2000 and exactly the first two are aged. The value is then edited by hand to -5000, which is
-- what neither transmute nor set_retain can prevent: that boundary is floor(8500) = 8000, above every
-- partition there is, and pre-fix the tick dropped all four and left the table empty and unwritable.
create table public.rs108h (id bigint generated by default as identity primary key, payload text);
insert into public.rs108h (payload) select 'x' from generate_series(1, 7);
call pgpm.transmute('public.rs108h', 'id', 1000, p_retain => 1500, p_paused => false, p_obtain => 3);
insert into public.rs108h (id, payload) select g, 'y' from generate_series(1001, 1003) g;
insert into public.rs108h (id, payload) values (3500, 'frontier');

create table pgpm_test108.h_before as
  select lo, child_name from pgpm.part where parent_table = 'public.rs108h'::regclass and attached;
select is((select array_agg(lo order by lo::numeric) from pgpm_test108.h_before), array['0', '1000', '2000', '3000'],
  'setup: four attached partitions, two of them below the legitimate horizon (the tick has real work to refuse)');

update pgpm.config set retain = '-5000' where parent_table = 'public.rs108h'::regclass;   -- THE HAND EDIT

select throws_like(
  $$ select pgpm._retain_boundary(c) from pgpm.config c where c.parent_table = 'public.rs108h'::regclass $$,
  '%is negative%', '_retain_boundary refuses to compute a horizon from a negative config.retain');

call pgpm.maintain('public.rs108h') \gset
select ok(:'p_status' like 'archived=0 dropped=0%write_block_deferred%retain_deferred%',
  'the tick deferred both the write-block and the retain step: ' || :'p_status');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rs108h'::regclass and action = 'skip_write_block' and method like '%is negative%'),
  1, 'skip_write_block was logged once, carrying the refusal');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rs108h'::regclass and action = 'skip_retain' and method like '%is negative%'),
  1, 'skip_retain was logged once, carrying the refusal');
select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.rs108h'::regclass and action = 'retain_drop'),
  0, 'nothing was dropped');
select is(
  (select array_agg(child_name order by lo::numeric) from pgpm.part
    where parent_table = 'public.rs108h'::regclass and attached),
  (select array_agg(child_name order by lo::numeric) from pgpm_test108.h_before),
  'every partition that was attached before the tick is attached after it, by name');
select is((select array_agg(id order by id) from public.rs108h),
  array[1, 2, 3, 4, 5, 6, 7, 1001, 1002, 1003, 3500]::bigint[],
  'every row is still there, the aged ones included');
select lives_ok(
  $$ insert into public.rs108h (id, payload) values (3501, 'still live') $$,
  'the table is live: a write at the frontier is accepted');
select is((select count(*) from public.rs108h where id = 3501), 1::bigint,
  'and it landed');

-- status() is the diagnostic, so it must not be the thing that dies
select ok((select count(*) from pgpm.status()) = (select count(*) from pgpm.config),
  'status() still returns a row for every managed table');
select is((select retain from pgpm.status() where parent = 'public.rs108h'::regclass), '-5000',
  'status() shows the offending value');
select is((select retain_backlog from pgpm.status() where parent = 'public.rs108h'::regclass), null::bigint,
  'status().retain_backlog is null for it: there is no honest count of what such a horizon makes eligible');

-- the repair path is open: set_retain works from the bad state (a loose value, which drops nothing)
select lives_ok(
  $$ select pgpm.set_retain('public.rs108h', '500000') $$,
  'set_retain repairs a hand-edited negative retain');
select is((select retain from pgpm.config where parent_table = 'public.rs108h'::regclass), '500000',
  'config.retain was repaired');

-- POSITIVE CONTROL: the same table, the same tick, only the sign differs. Put back by hand because
-- set_retain, by its own rule, refuses to arm a value that would drop [0, 1000) and [1000, 2000) from a
-- state that has kept everything.
update pgpm.config set retain = '1500' where parent_table = 'public.rs108h'::regclass;
call pgpm.maintain('public.rs108h') \gset
select ok(:'p_status' like 'archived=0 dropped=2%' and :'p_status' not like '%deferred%',
  'with the sign right the tick drops the two aged partitions and defers nothing: ' || :'p_status');
select is(
  (select array_agg(lo order by lo::numeric) from pgpm.log
    where parent_table = 'public.rs108h'::regclass and action = 'retain_drop'),
  array['0', '1000'], 'retain_drop was logged for exactly [0, 1000) and [1000, 2000)');
select is(
  (select array_agg(child_name order by lo::numeric) from pgpm.part
    where parent_table = 'public.rs108h'::regclass and attached),
  (select array_agg(child_name order by lo::numeric) from pgpm_test108.h_before where lo::numeric >= 2000),
  'exactly the partitions at or above the horizon remain attached, by name');
select is((select array_agg(id order by id) from public.rs108h), array[3500, 3501]::bigint[],
  'exactly the frontier rows survive');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rs108h'::regclass and action in ('skip_write_block', 'skip_retain')),
  2, 'no further skip was logged: the two from the refused tick are the only ones');

-- ======================= (C) defence in depth: regrain_step has its own copy of the horizon =======================
-- regrain skips sub-ranges entirely below the horizon and discards their rows with the coarse source at the
-- swap, never copied. Against a future horizon that is every sub-range: the whole monolith, discarded.
create table public.rs108r (id bigint generated by default as identity primary key, payload text);
insert into public.rs108r (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
call pgpm.transmute('public.rs108r', 'id', 10000, p_retain => 30000);   -- monolith [0, 60000)
select pgpm.obtain('public.rs108r');
insert into public.rs108r (id, payload) values (65000, 'frontier');    -- the monolith is frozen

select child_name as r_mono from pgpm.part where parent_table = 'public.rs108r'::regclass and lo = '0' \gset

update pgpm.config set retain = '-30000' where parent_table = 'public.rs108r'::regclass;   -- THE HAND EDIT

select is(pgpm.regrain_step('public.rs108r', :'r_mono'), 'prepared',
  'setup: the first regrain_step call installs change capture, which happens before the horizon is computed');
-- (built with format(): psql does not interpolate :'r_mono' inside a dollar-quoted string)
select throws_like(
  format($$ select pgpm.regrain_step('public.rs108r', %L) $$, :'r_mono'),
  '%is negative%', 'regrain_step refuses to compute a horizon from a negative config.retain');
select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rs108r'::regclass and action in ('regrain_aged', 'regrain_copy')),
  0, 'no sub-range was marked aged and none was copied');
select ok(
  (select attached from pgpm.part where parent_table = 'public.rs108r'::regclass and child_name = :'r_mono'),
  'the monolith is still attached');
select is(
  (select array_agg(id order by id) from public.rs108r where id in (1, 29999, 30000, 50000, 65000)),
  array[1, 29999, 30000, 50000, 65000]::bigint[],
  'the sentinel rows on both sides of the legitimate horizon are all still there');

-- POSITIVE CONTROL: the same regrain with the sign right (tests/07's shape): the 3 within-horizon
-- sub-ranges are copied, the 3 below it are skipped as aged and their rows discarded with the source.
update pgpm.config set retain = '30000' where parent_table = 'public.rs108r'::regclass;
select is(pgpm.regrain_history('public.rs108r'), 3,
  'with the sign right, regrain copies exactly the 3 within-horizon sub-ranges');
select is(
  (select array_agg(distinct lo order by lo) from pgpm.log
    where parent_table = 'public.rs108r'::regclass and action = 'regrain_aged'),
  array['0', '10000', '20000'], 'the 3 below-horizon sub-ranges were skipped as aged, by lo');
select is(
  (select array_agg(id order by id) from public.rs108r where id in (1, 29999, 30000, 50000, 65000)),
  array[30000, 50000, 65000]::bigint[],
  'the rows below the legitimate horizon are gone and the rest remain');

select * from finish();
