-- Both pgpm triggers fire regardless of session_replication_role (issue #450).
--
-- CREATE TRIGGER alone leaves a trigger ENABLE ORIGIN (pg_trigger.tgenabled = 'O'): it fires for an
-- ordinary session and is skipped for one running as session_replication_role = replica, which is what
-- a logical-replication apply worker runs as and what several bulk loaders set to silence triggers.
-- That is the right default for a trigger that is a replication SIDE EFFECT (an audit row, a notify).
-- Neither pgpm trigger is one. The write block is retention's fence: a row that lands behind it goes
-- into a partition whose archive coverage is already complete and is dropped unarchived. The regrain
-- capture is what keeps a mid-regrain write from being reverted, lost or resurrected at the swap. Both
-- must therefore be ENABLE ALWAYS (tgenabled = 'A'), and this file asserts that state directly rather
-- than inferring it.
--
-- Every negative is paired with its witness. The session's replica mode is read back from
-- current_setting, a control write under replica role into an UNBLOCKED sibling is shown to land (so
-- the refusals are the trigger's, not the role's), and the capture part copies the sub-range FIRST and
-- writes into it afterwards: written before any copy, the changes would be picked up by the copy
-- itself and the post-swap assertions would pass with capture doing nothing at all.
-- `set session_replication_role` needs superuser, which the harness's postgres role is.
create extension if not exists pgtap;
select plan(31);

create schema pgpm_test110;

-- ======================= A. the write block =======================
-- Same fixture as tests/61: boundary = grid_floor(110000 - 30000, step 10000) = 80000, so the monolith
-- [0,60000), [60000,70000) and [70000,80000) are eligible and get blocked on the first tick.
create table public.wb110 (id bigint generated by default as identity primary key, payload text);
insert into public.wb110 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
call pgpm.transmute('public.wb110', 'id', 10000, p_retain => 30000, p_paused => false);   -- monolith [0, 60000)
select pgpm.obtain('public.wb110');
update pgpm.config set retain_batch = 0 where parent_table = 'public.wb110'::regclass;   -- retain() drops nothing
insert into public.wb110 (id, payload) values (110000, 'frontier');

create table pgpm_test110.names as
  select lo, child_name from pgpm.part where parent_table = 'public.wb110'::regclass;

call pgpm.maintain('public.wb110');

select ok(
  exists (select 1 from pg_trigger t where t.tgname = 'pgpm_write_block'
            and t.tgrelid = ('public.' || (select child_name from pgpm_test110.names where lo = '0'))::regclass),
  'setup: the maintain tick installed the write block on the monolith');

select is(
  (select t.tgenabled::text from pg_trigger t where t.tgname = 'pgpm_write_block'
     and t.tgrelid = ('public.' || (select child_name from pgpm_test110.names where lo = '0'))::regclass),
  'A', 'the write block is ENABLE ALWAYS (tgenabled = A), not the origin-only default');

set session_replication_role = replica;
select is(current_setting('session_replication_role'), 'replica',
  'witness: this session is in replica mode, the mode an origin-only trigger is skipped in');

select throws_like(
  $$ insert into public.wb110 (id, payload) values (65000, 'replica-backdated') $$,
  '%past its retention boundary%',
  'a replica-role INSERT routed through the parent into a write-blocked range is refused');

select throws_like(
  format($$ insert into public.%I (id, payload) values (55000, 'replica-backdated-direct') $$,
    (select child_name from pgpm_test110.names where lo = '0')),
  '%past its retention boundary%',
  'a replica-role INSERT addressed directly to the write-blocked child is refused too');

select throws_like(
  $$ update public.wb110 set payload = 'replica-edited' where id = 42 $$,
  '%past its retention boundary%',
  'a replica-role UPDATE of a row behind the block is refused');

select throws_like(
  $$ delete from public.wb110 where id = 42 $$,
  '%past its retention boundary%',
  'a replica-role DELETE of a row behind the block is refused');

-- control: the role is not what refused those. The same session writes an UNBLOCKED sibling fine.
select lives_ok(
  $$ insert into public.wb110 (id, payload) values (85000, 'replica-control') $$,
  'witness: the same replica-role session can write into a sibling that is not write-blocked');
select is((select payload from public.wb110 where id = 85000), 'replica-control',
  'witness: and that control row landed, so replica mode itself refuses nothing here');

select is(
  (select count(*)::int from public.wb110 where id in (55000, 65000)),
  0, 'neither refused replica-role INSERT landed');
select is((select payload from public.wb110 where id = 42), 'x',
  'the refused UPDATE and DELETE changed nothing: row 42 is still there, unedited');

-- ======================= B. the upgrade path =======================
-- An install that predates this fix already carries write blocks in the origin-only state, and
-- re-running install.sql touches no trigger. _enforce_write_blocks revisits every attached child every
-- tick and _install_write_block returns early when the trigger exists, so that early return is where an
-- existing block is repaired: for the triggers, the first maintain tick after the upgrade IS the upgrade.
reset session_replication_role;
select is(current_setting('session_replication_role'), 'origin', 'witness: back in origin mode');

do $$ begin
  execute format('alter table public.%I enable trigger pgpm_write_block',
                 (select child_name from pgpm_test110.names where lo = '0'));
end $$;
select is(
  (select t.tgenabled::text from pg_trigger t where t.tgname = 'pgpm_write_block'
     and t.tgrelid = ('public.' || (select child_name from pgpm_test110.names where lo = '0'))::regclass),
  'O', 'witness: the monolith''s block is back in the origin-only state an older pgpm left it in');

call pgpm.maintain('public.wb110');
select is(
  (select t.tgenabled::text from pg_trigger t where t.tgname = 'pgpm_write_block'
     and t.tgrelid = ('public.' || (select child_name from pgpm_test110.names where lo = '0'))::regclass),
  'A', 'the next maintain tick repairs an existing origin-only block to ENABLE ALWAYS');
select is(
  (select count(*)::int from pg_trigger t where t.tgname = 'pgpm_write_block'
     and t.tgrelid = ('public.' || (select child_name from pgpm_test110.names where lo = '0'))::regclass),
  1, 'and it repaired the trigger in place rather than stacking a second one');

-- ======================= C. the regrain capture =======================
-- Same fixture as tests/69: 250 rows at ids 10..2500 in a monolith [0,3000), frozen by a frontier row.
create table public.rc110 (id bigint primary key, payload text);
insert into public.rc110 select g * 10, 'x' from generate_series(1, 250) g;
call pgpm.transmute('public.rc110', 'id', 1000);
insert into public.rc110 values (20000, 'frontier');

create table pgpm_test110.rc as
  select child_name from pgpm.part where parent_table = 'public.rc110'::regclass and lo = '0';

select is(
  pgpm.regrain_step('public.rc110', (select child_name from pgpm_test110.rc), '100', 50),
  'prepared', 'setup: the first regrain tick installs change capture on the frozen monolith');

select ok(
  exists (select 1 from pg_trigger t where t.tgname = 'pgpm_regrain_capture'
            and t.tgrelid = ('public.' || (select child_name from pgpm_test110.rc))::regclass),
  'setup: the source child carries the capture trigger');

select is(
  (select t.tgenabled::text from pg_trigger t where t.tgname = 'pgpm_regrain_capture'
     and t.tgrelid = ('public.' || (select child_name from pgpm_test110.rc))::regclass),
  'A', 'the capture trigger is ENABLE ALWAYS (tgenabled = A)');

-- Copy sub-range [0,100) (9 rows, one 50-row batch) BEFORE writing into it. This is what makes the
-- post-swap assertions mean something: a change to an already-copied key reaches the fine child only
-- through capture and reconcile.
select ok(
  pgpm.regrain_step('public.rc110', (select child_name from pgpm_test110.rc), '100', 50) like 'copied:%',
  'setup: the second tick copies');
select cmp_ok(
  (select regrain_cursor::numeric from pgpm.config where parent_table = 'public.rc110'::regclass),
  '>=', 100::numeric,
  'witness: the cursor is past 100, so sub-range [0,100), holding keys 20, 25 and 30, is already copied');
select is((select count(*)::int from public.rc110_pgpm_regrain_delta), 0,
  'witness: the delta is empty before the replica-role writes');

set session_replication_role = replica;
select is(current_setting('session_replication_role'), 'replica', 'witness: replica mode again');

-- asymmetric: one UPDATE (key 20), one INSERT (key 25), one DELETE (key 30). Three keys and three
-- operations, so a capture that missed one cannot be masked by another.
update public.rc110 set payload = 'replica-edit' where id = 20;
insert into public.rc110 values (25, 'replica-insert');
delete from public.rc110 where id = 30;

select is((select payload from public.rc110 where id = 20), 'replica-edit',
  'witness: the replica-role UPDATE landed in the source');
select ok(exists (select 1 from public.rc110 where id = 25),
  'witness: the replica-role INSERT landed in the source');
select ok(not exists (select 1 from public.rc110 where id = 30),
  'witness: the replica-role DELETE landed in the source');

select is(
  (select string_agg(id::text, ',' order by id, pgpm_seq) from public.rc110_pgpm_regrain_delta),
  '20,20,25,30',
  'the capture trigger recorded every replica-role change by key: UPDATE old+new (20,20), INSERT 25, DELETE 30');

reset session_replication_role;
select is(current_setting('session_replication_role'), 'origin', 'witness: origin mode again');

-- drive to the swap: the captured keys are reconciled from the source, then the fine children go live
do $$ declare s text; n int := 0; begin
  loop s := pgpm.regrain_step('public.rc110', (select child_name from pgpm_test110.rc), '100', 50);
    exit when s like 'swapped:%'; n := n + 1;
    if n > 500 then raise exception 'no convergence, last status %', s; end if;
  end loop;
end $$;

select is((select payload from public.rc110 where id = 20), 'replica-edit',
  'after the swap the replica-role UPDATE is still there (not reverted)');
select ok(exists (select 1 from public.rc110 where id = 25),
  'after the swap the replica-role INSERT is still there (not lost)');
select ok(not exists (select 1 from public.rc110 where id = 30),
  'after the swap the replica-role DELETE is still honoured (not resurrected)');
select is((select count(*)::int from public.rc110 where id < 3000), 250,
  'and the history is otherwise intact: 250 rows, less the one deleted, plus the one inserted');

select * from finish();
