-- Issue #512: _is_write_blocked and _regrain_capture_active looked the parent's schema up by NAME and then
-- cast that raw name back with `v_nsp::regnamespace`. regnamespace input parses its text as an SQL
-- identifier, so a schema whose name needs quoting ("Sales", "my schema") is downcased or fails to parse:
-- with no lower-case twin the cast raises `schema "sales" does not exist`, and with one it silently
-- answers for the twin's same-named child instead. The archive step calls _is_write_blocked for every
-- candidate child, so a managed table with an archive_fn in such a schema logged skip_archive on every
-- maintain() tick, nothing was ever archived and retain() never dropped the aged partition; a regrain in
-- such a schema could not prepare (skip_regrain) and the janitor logged skip_regrain_capture per child.
-- The identical table in a lower-case schema archived, retired and regrained in the same ticks. Both
-- functions now compare the child's relnamespace against the parent's relnamespace OID and never
-- re-parse a name.
--
-- The cast was only reached when a trigger row of the right name met it: at plan time while plpgsql still
-- used a custom plan, and at run time only for a pg_trigger row whose relname matched. A schema with no
-- same-named child under a trigger anywhere could therefore go quiet, which is what made the defect
-- intermittent across sessions. Every negative below is paired with the condition that forces the cast to
-- be evaluated, so it cannot pass by never having been asked: the control table archived and retired in
-- the same ticks (A), a same-named child in a lower-case schema carried the capture trigger throughout the
-- regrain ticks (B), and the lower-case twin's child really is under the write block (C).
create extension if not exists pgtap;
select plan(17);

-- ============================================== (A) archive and retire in a schema that needs quoting
create schema "Sales";
create table "Sales".ag (id bigint primary key, payload text);
insert into "Sales".ag select g, 'sales' from generate_series(1, 3) g;                 -- monolith [0, 1000)
call pgpm.transmute('"Sales".ag', 'id', 1000, p_retain => 1000::bigint, p_paused => false);
insert into "Sales".ag values (20000, 'frontier');                                     -- horizon 19000
select pgpm.set_archive_fn('"Sales".ag', 'pgpm._archive_noop(regclass,name,text,text)');

-- control: the same table in a schema whose name needs no quoting
create schema sales_ctl;
create table sales_ctl.ag (id bigint primary key, payload text);
insert into sales_ctl.ag select g, 'ctl' from generate_series(1, 3) g;
call pgpm.transmute('sales_ctl.ag', 'id', 1000, p_retain => 1000::bigint, p_paused => false);
insert into sales_ctl.ag values (20000, 'frontier');
select pgpm.set_archive_fn('sales_ctl.ag', 'pgpm._archive_noop(regclass,name,text,text)');

call pgpm.maintain('sales_ctl.ag');
call pgpm.maintain('sales_ctl.ag');
call pgpm.maintain('"Sales".ag');
call pgpm.maintain('"Sales".ag');

-- LIVENESS: the pipeline works for the control table, so the fixture really is archive-and-drop ready
select ok(exists (select 1 from pgpm.archive_ledger where parent_table = 'sales_ctl.ag'::regclass and lo = '0'),
          'LIVENESS: the control table''s aged monolith was archived');
select is((select array_agg(id order by id) from sales_ctl.ag), array[20000::bigint],
          'LIVENESS: and retired: only its frontier row remains');

-- the defect
select is((select array_agg(distinct method) from pgpm.log
            where parent_table = '"Sales".ag'::regclass and action = 'skip_archive'),
          null, 'no archive tick on "Sales".ag failed');
select ok(exists (select 1 from pgpm.archive_ledger where parent_table = '"Sales".ag'::regclass and lo = '0'),
          'the "Sales".ag monolith was archived');
select is((select array_agg(id order by id) from "Sales".ag), array[20000::bigint],
          'and retired: rows 1..3 gone, the frontier row 20000 remains');

-- ============================================== (B) a maintain-driven auto-regrain in the same schema
-- tests/46's fixture, in "Sales" and again in sales_ctl: 200 rows in a [0, 250) monolith, step 50, batch
-- 30. The control is prepared by hand first, so that a child of exactly the name the janitor and
-- regrain_step will ask about carries pgpm_regrain_capture (in the other schema) for the whole run.
create table "Sales".rg (id bigint generated by default as identity primary key, payload text);
insert into "Sales".rg (payload) select 'x' from generate_series(1, 200);                -- ids 1..200
call pgpm.transmute('"Sales".rg', 'id', 50, p_regrain_batch => 30, p_paused => false);   -- monolith [0, 250)
select pgpm.obtain('"Sales".rg');
insert into "Sales".rg (id, payload) values (1000, 'frontier');                          -- freezes the monolith
select pgpm.set_regrain('"Sales".rg', '50');

create table sales_ctl.rg (id bigint generated by default as identity primary key, payload text);
insert into sales_ctl.rg (payload) select 'x' from generate_series(1, 200);
call pgpm.transmute('sales_ctl.rg', 'id', 50, p_regrain_batch => 30, p_paused => true);
select pgpm.obtain('sales_ctl.rg');
insert into sales_ctl.rg (id, payload) values (1000, 'frontier');

select is((select child_name from pgpm.part where parent_table = '"Sales".rg'::regclass and lo = '0'),
          (select child_name from pgpm.part where parent_table = 'sales_ctl.rg'::regclass and lo = '0'),
          'LIVENESS: the two monoliths carry the same child name, so only the schema tells them apart');
select is(pgpm.regrain_step('sales_ctl.rg', 'rg_p0000000000000000000_to_0000000000000000250', '50', 30),
          'prepared', 'LIVENESS: the control''s monolith now carries the capture trigger, under the same name');
select is((select coarse_partitions from pgpm.status() where parent = '"Sales".rg'::regclass),
          1::bigint, 'LIVENESS: a coarse monolith awaits regraining in "Sales" before any tick');

do $$ declare v_status text; begin for i in 1..42 loop call pgpm.maintain('"Sales".rg', v_status); end loop; end $$;

select is((select array_agg(distinct action order by action) from pgpm.log
            where parent_table = '"Sales".rg'::regclass and action in ('skip_regrain', 'skip_regrain_capture')),
          null, 'no regrain tick or janitor pass on "Sales".rg failed');
select is((select coarse_partitions from pgpm.status() where parent = '"Sales".rg'::regclass),
          0::bigint, 'the maintain ticks completed the regrain: no coarse partition remains');
select is((select array_agg(child_name order by lo::bigint) from pgpm.part
            where parent_table = '"Sales".rg'::regclass and attached and lo::bigint < 250),
          array['rg_p0000000000000000000', 'rg_p0000000000000000050', 'rg_p0000000000000000100',
                'rg_p0000000000000000150', 'rg_p0000000000000000200']::name[],
          'the monolith was replaced by the five step-50 children');
select is((select array_agg(id order by id) from "Sales".rg),
          (select array_agg(g) from generate_series(1, 200) g) || 1000::bigint,
          'every history row 1..200 and the frontier row survived the regrain, by identity');
select ok(pgpm._regrain_capture_active('sales_ctl.rg', 'rg_p0000000000000000000_to_0000000000000000250'),
          'LIVENESS: the control''s same-named capture trigger was there for every tick and is untouched');

-- ============================================== (C) a lower-case twin: the cast answers for the wrong table
-- `'Sales'::regnamespace` is `sales` once that schema exists. Two managed tables of the same name and grid
-- have children of the same name, so the cast would report the TWIN's write block as ours. Only the twin is
-- blocked here, and it is blocked directly rather than through retire so that it stays put to be asked about.
create schema sales;
create table "Sales".wb (id bigint primary key, payload text);
insert into "Sales".wb select g, 'quoted' from generate_series(1, 3) g;
call pgpm.transmute('"Sales".wb', 'id', 1000, p_retain => 1000::bigint, p_paused => true);
create table sales.wb (id bigint primary key, payload text);
insert into sales.wb select g, 'twin' from generate_series(1, 3) g;
call pgpm.transmute('sales.wb', 'id', 1000, p_retain => 1000::bigint, p_paused => true);
select pgpm._install_write_block('sales.wb', 'wb_p0000000000000000000');

select is((select array_agg(child_name order by child_name) from pgpm.part where parent_table = '"Sales".wb'::regclass),
          (select array_agg(child_name order by child_name) from pgpm.part where parent_table = 'sales.wb'::regclass),
          'LIVENESS: the two tables'' children carry identical names, so only the schema tells them apart');
select is((select array_agg(n.nspname::text order by n.nspname) from pg_trigger t
             join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
            where t.tgname = 'pgpm_write_block' and c.relname = 'wb_p0000000000000000000'),
          array['sales'], 'LIVENESS: exactly one wb child carries the write block, and it is the twin''s');
select ok(pgpm._is_write_blocked('sales.wb', 'wb_p0000000000000000000'),
          'LIVENESS: the twin''s child answers blocked');
select ok(not pgpm._is_write_blocked('"Sales".wb', 'wb_p0000000000000000000'),
          'the quoted schema''s same-named child answers NOT blocked: the twin''s trigger is not ours');

select * from finish();
