-- Online adopt: build_pk_concurrently() builds the default's composite PK index
-- online (via a pg_cron worker) BEFORE adopt, and adopt() then reuses (promotes) it
-- instead of building it under ACCESS EXCLUSIVE. build_pk_concurrently is a procedure
-- (it COMMITs while polling) and drives an async cron job, so it can't run inside this
-- test's transaction -- but the REUSE path it feeds works for any matching unique
-- index, so we build a plain one and prove adopt promotes that exact index object.
create extension if not exists pgtap;

begin;
select plan(7);

-- 1. the cron-driven online builder is installed as a procedure
select ok(
  exists(select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
          where n.nspname = 'pgpm' and p.proname = 'build_pk_concurrently' and p.prokind = 'p'),
  'pgpm.build_pk_concurrently(...) procedure is installed'
);

-- a table shaped like a real candidate: simple PK on id, time control column
create table public.pa (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  payload    text
);
insert into public.pa (created_at, payload)
select now() - (random() * interval '90 days'), md5(g::text) from generate_series(1, 5000) g;

-- stand in for the online build (CIC can't run in a txn): a matching unique index
create unique index pa_prebuilt on public.pa (created_at, id);
create temp table _preoid as select 'public.pa_prebuilt'::regclass::oid as oid;

select pgpm.adopt('public.pa', 'created_at', interval '1 month', 2);

-- 2. adopt reused the pre-built index AS the PK (same physical index object / oid)
select is(
  (select i.indexrelid from pg_index i
     where i.indrelid = 'public.pa_default'::regclass and i.indisprimary),
  (select oid from _preoid),
  'adopt promoted the pre-built index (same oid) to the default PK -- no in-txn rebuild'
);

-- 3. the resulting PK is the composite (partition key, id)
select is(
  (select array_agg(a.attname::text order by k.ord)
     from pg_constraint con
     cross join lateral unnest(con.conkey) with ordinality as k(attnum, ord)
     join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k.attnum
    where con.conrelid = 'public.pa_default'::regclass and con.contype = 'p'),
  array['created_at', 'id'],
  'default PK is the composite (created_at, id)'
);

-- 4. no rows lost in the conversion
select is(
  (select count(*) from public.pa)::int,
  5000,
  'all rows conserved through adopt'
);

-- 5. adopt() does the cutover ONLY -- it does not premake inside its ACCESS EXCLUSIVE
-- transaction (that would scan the default and block). The DEFAULT is the only partition.
select is(
  (select count(*)::int from pg_inherits where inhparent = 'public.pa'::regclass),
  1,
  'adopt() leaves only the DEFAULT partition (no in-transaction premake)'
);

-- 6. premake(), run separately afterward, builds the future partitions
select pgpm.premake('public.pa');
select ok(
  (select count(*) from pg_inherits where inhparent = 'public.pa'::regclass) > 1,
  'premake() (run after adopt) adds the future partitions'
);

-- 7. adopt advanced the freshly-recreated parent identity sequence past the existing data,
-- using the max(id) captured BEFORE the original id index was dropped -- so a post-adopt insert
-- to the parent gets max+1 (5001), with no collision and no full-table scan at the cutover.
insert into public.pa (created_at, payload) values (now(), 'seqtest');
select is(
  (select id from public.pa where payload = 'seqtest')::bigint,
  5001::bigint,
  'post-adopt insert gets id = max(id)+1 from the advanced identity sequence (captured pre-PK-swap)'
);

select * from finish();
rollback;
