-- Covered-case PK reuse: partitioning a table on its own bigint id primary key must NOT
-- drop and rebuild that primary key. The existing index already includes the partition key,
-- so adopt reuses it in place (the one-time "setup" cost center collapses to zero). See
-- DESIGN.md section 8 ("reuse the existing PK when the partition key already covers it").
create extension if not exists pgtap;

begin;
select plan(6);

create table public.reuse_pk (id bigint generated by default as identity primary key, payload text);
insert into public.reuse_pk (payload) select 'x' from generate_series(1, 500);

-- the identity of the PK index BEFORE adopt; reuse means this same index object survives
create temporary table _pk_before on commit drop as
  select i.indexrelid::oid as idx_oid
    from pg_index i where i.indrelid = 'public.reuse_pk'::regclass and i.indisprimary;

select pgpm.adopt('public.reuse_pk', 'id', 100000);

select is(
  (select relkind::text from pg_class where oid = 'public.reuse_pk'::regclass),
  'p', 'reuse_pk became a partitioned table');

select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.reuse_pk'::regclass and contype = 'p'),
  1, 'parent has a primary key');

select is(
  (select i.indexrelid::oid from pg_index i
     where i.indrelid = 'public.reuse_pk_default'::regclass and i.indisprimary),
  (select idx_oid from _pk_before),
  'default PK index was reused, not rebuilt (oid preserved)');

select is(
  (select count(*)::int from pg_index i
     where i.indrelid = 'public.reuse_pk_default'::regclass and i.indisunique),
  1, 'exactly one unique index on the default (no rebuilt duplicate)');

select throws_ok(
  $$ insert into public.reuse_pk (id, payload) values (1, 'dup') $$,
  '23505', NULL, 'duplicate id rejected (PK enforced through the cutover)');

select is(
  (select count(*)::int from public.reuse_pk), 500, 'all rows conserved');

select * from finish();
rollback;
