-- pgpm.check_time_monotonic: how co-monotonic is an id column with a timestamp column? It samples
-- rows, orders them by id, and reports the fraction of adjacent pairs whose time is non-decreasing.
-- This is the tier-2 safety check for the key->time retention bridge (DESIGN.md section 8): mapping
-- "older than T" to an id boundary is only sound when id and time co-increase (~1.0). Backfills and
-- out-of-order arrival drive the fraction down.
create extension if not exists pgtap;

begin;
select plan(4);

-- co-monotonic: id ascends together with created_at
create table public.cm (id bigint generated by default as identity primary key, created_at timestamptz);
insert into public.cm (created_at)
  select timestamptz '2024-01-01' + g * interval '1 hour' from generate_series(1, 1000) g;

-- decorrelated: created_at is random relative to id
create table public.dm (id bigint generated by default as identity primary key, created_at timestamptz);
insert into public.dm (created_at)
  select timestamptz '2024-01-01' + (random() * 1000)::int * interval '1 hour' from generate_series(1, 1000);

select is(
  (select fraction from pgpm.check_time_monotonic('public.cm', 'id', 'created_at', 500)),
  1.0000::numeric, 'co-monotonic id/time gives fraction 1.0');

select cmp_ok(
  (select sampled from pgpm.check_time_monotonic('public.cm', 'id', 'created_at', 500))::int,
  '>=', 100, 'check sampled a meaningful number of adjacent pairs');

select cmp_ok(
  (select fraction from pgpm.check_time_monotonic('public.dm', 'id', 'created_at', 500)),
  '<', 0.95::numeric, 'decorrelated id/time falls below the 0.95 threshold');

-- empty table: no adjacent pairs, returns zero without crashing
create table public.em (id bigint primary key, created_at timestamptz);
select is(
  (select sampled from pgpm.check_time_monotonic('public.em', 'id', 'created_at', 500))::int,
  0, 'empty table yields zero sampled pairs (no crash)');

select * from finish();
rollback;
