-- Block-budgeted batching, on the drain. A drain microbatch's footprint should be bounded by
-- BLOCKS, not a fixed ROW count, so wide rows (large jsonb/bytea) can't make one batch tens of GB. When
-- config drain_max_blocks is set, drain_step caps the batch at ~that many heap+TOAST blocks (translated
-- to a row limit via the table's avg bytes/row); when null it falls back to the row cap (drain_batch),
-- unchanged. Here the rows being drained are wide backdated STRAYS in the DEFAULT. See REDESIGN.md.
create extension if not exists pgtap;

begin;
select plan(3);

-- ~1.8 KB/row, forced inline (storage plain) so the on-disk size is deterministic. ~4 rows/block.
create table public.wide (created_at timestamptz not null, id bigint generated by default as identity,
                          pad text, primary key (created_at, id));
alter table public.wide alter column pad set storage plain;
insert into public.wide (created_at, pad)
  select now() - (g || ' minutes')::interval, repeat('x', 1800) from generate_series(1, 20) g;   -- recent -> monolith
select pgpm.transmute('public.wide', 'created_at', interval '1 month', p_paused => false);
-- 3000 wide strays in one closed interval (3 months ago) land in the DEFAULT for the drain to drain
insert into public.wide (created_at, pad)
  select date_trunc('month', now()) - interval '3 months' + interval '10 days', repeat('x', 1800)
  from generate_series(1, 3000) g;
analyze public.wide_default;                               -- fresh reltuples for the estimate

-- (1) block budget binds: 20 blocks, but a huge 100000-row cap
update pgpm.config set drain_batch = 100000, drain_max_blocks = 20 where parent_table = 'public.wide'::regclass;
create temp table _c1 on commit drop as select count(*)::int n from public.wide_default;
select pgpm.drain_step('public.wide', p_include_open => true);
select cmp_ok((select n from _c1) - (select count(*)::int from public.wide_default), '<', 500,
  'block budget (20 blocks) bounds the batch far below the 100000-row cap');
select cmp_ok((select n from _c1) - (select count(*)::int from public.wide_default), '>', 0,
  'block-budgeted step still makes progress');

-- (2) block budget off: the row cap binds exactly (backward compatible with today's behavior)
update pgpm.config set drain_batch = 250, drain_max_blocks = null where parent_table = 'public.wide'::regclass;
create temp table _c2 on commit drop as select count(*)::int n from public.wide_default;
select pgpm.drain_step('public.wide', p_include_open => true);
select is((select n from _c2) - (select count(*)::int from public.wide_default), 250,
  'with no block budget, a step moves exactly drain_batch rows (unchanged)');

select * from finish();
rollback;
