-- Orphaned-child guard: a drain creates each child partition as a standalone table
-- (CREATE TABLE ... LIKE) and only ATTACHes it at the end of that child's drain. While
-- mid-drain the child is un-attached, so DROP TABLE <parent> CASCADE does NOT drop it (an
-- un-attached child has no dependency on the parent). If the table is then recreated/reloaded
-- and re-adopted, the next drain finds the orphan by name, reuses it, and INSERTs rows whose
-- ids already live in the orphan -> a cryptic mid-drain "duplicate key" deep in drain_step.
--
-- adopt() must instead refuse UP FRONT with a clear, actionable error when an orphaned table
-- matching the child-partition naming already exists. See DESIGN.md section 8.
create extension if not exists pgtap;

begin;
select plan(6);

-- ---- build the orphan via a real, partially-completed drain --------------------------------
create table public.og (id bigint generated by default as identity primary key, payload text);
insert into public.og (payload) select 'x' from generate_series(1, 300);
-- small drain_batch so a single step does NOT finish the range (child stays un-attached)
select pgpm.adopt('public.og', 'id', 100000, p_drain_batch => 100);
select pgpm.drain_step('public.og', p_include_open => true);   -- moves 100 rows into og_p0000...0

select ok(
  (select count(*) = 0 from pg_inherits where inhrelid = 'public.og_p0000000000000000000'::regclass),
  'precondition: the in-progress child is a standalone table, not yet an attached partition');

-- destructive "reset" that forgets the orphan: drop the parent (CASCADE) + pgpm metadata.
delete from pgpm.part   where parent_table = 'public.og'::regclass;
delete from pgpm.config where parent_table = 'public.og'::regclass;
drop table public.og cascade;

select has_table('public', 'og_p0000000000000000000',
  'the un-attached child SURVIVES DROP TABLE <parent> CASCADE (the orphan)');

-- recreate the table fresh (ids restart at 1) and try to re-adopt over the lurking orphan
create table public.og (id bigint generated by default as identity primary key, payload text);
insert into public.og (payload) select 'x' from generate_series(1, 300);

select throws_ok(
  $$ select pgpm.adopt('public.og', 'id', 100000) $$,
  'P0001', null,
  'adopt refuses when an orphaned child-partition table already exists (no cryptic later dup-key)');

select is(
  (select relkind::text from pg_class where oid = 'public.og'::regclass),
  'r', 'the refusal mutated nothing: og is still a plain (un-partitioned) table');

-- remedy: drop the orphan, then the same adopt succeeds
drop table public.og_p0000000000000000000;
select lives_ok(
  $$ select pgpm.adopt('public.og', 'id', 100000) $$,
  'once the orphan is dropped, adopt succeeds');

-- ---- no false positive: a sibling whose name merely shares the <rel>_p prefix but is not a
-- ---- partition-shaped name (no digits) must NOT trip the guard ----------------------------
create table public.sib (id bigint generated by default as identity primary key, payload text);
insert into public.sib (payload) select 'x' from generate_series(1, 50);
create table public.sib_promotions (note text);   -- starts with sib_p, but 'romotions' are not digits
select lives_ok(
  $$ select pgpm.adopt('public.sib', 'id', 100000) $$,
  'a sibling named <rel>_promotions does not trip the guard (requires <rel>_p<digits>)');

select * from finish();
rollback;
