-- Incoming-FK preservation on the id/uuidv7 happy path. When the partition key already is the
-- referenced single-column PK, the parent keeps that single-column unique key, so an incoming FK
-- need not be denormalized into a composite FK (unlike the widening time case). adopt(...,
-- p_incoming_fks => 'preserve') records and DROPS the incoming FK so the drain can run (the drain
-- moves rows through an unattached child, which a live NO ACTION FK would reject), then
-- restore_incoming_fks() re-adds it verbatim against the new parent (NOT VALID + VALIDATE) once the
-- table is drained. The referencing table is never touched. See DESIGN.md section 8.
create extension if not exists pgtap;

begin;
select plan(6);

-- id is the table's single-column PK; we partition by id -> the happy path
create table public.m (id bigint generated by default as identity primary key, body text);
insert into public.m (body) select 'x' from generate_series(1, 300);

-- another table with an incoming single-column FK -> m(id)
create table public.ref (rid bigint generated by default as identity primary key,
                         m_id bigint references public.m(id));
insert into public.ref (m_id) select 1 + floor(random() * 300)::int from generate_series(1, 100);

-- adopt by id, preserving the incoming FK; small batch so the drain takes several steps
select pgpm.adopt_by_id('public.m', 'id', 100000000, p_drain_batch => 50, p_incoming_fks => 'preserve');

select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.ref'::regclass and contype = 'f'),
  0, 'preserve dropped the incoming FK for the duration of the conversion');

select is(
  (select count(*)::int from pgpm.dropped_fk where parent_table = 'public.m'::regclass),
  1, 'the dropped FK was recorded for restoration');

-- convert to completion (synchronous path), then restore
select pgpm.drain_all('public.m', p_include_open => true);

select is(
  (select pgpm.restore_incoming_fks('public.m')),
  1, 'restore_incoming_fks re-added one FK');

select is(
  (select count(*)::int from pg_constraint
     where conrelid = 'public.ref'::regclass and contype = 'f' and confrelid = 'public.m'::regclass),
  1, 'the FK exists again and references the new partitioned parent');

select throws_ok(
  $$ insert into public.ref (m_id) values (999999999) $$,
  '23503', NULL, 'the restored FK is enforced (a dangling reference is rejected)');

select is(
  (select count(*)::int from pgpm.dropped_fk
     where parent_table = 'public.m'::regclass and restorable and restored_at is null),
  0, 'no preserved FK left pending (the record is kept, marked live)');

select * from finish();
rollback;
