-- Incoming-FK preservation, scheduled path: maintenance() restores the preserved FK on its own once
-- the closed tail has drained. restore_incoming_fks self-gates on quiescence, so it is a no-op while
-- closed rows remain and fires only when the drain is idle. See DESIGN.md section 8.
create extension if not exists pgtap;

begin;
select plan(7);

-- step 100 with ids 1..300 => intervals [0,100),[100,200),[200,300) are CLOSED (need draining),
-- [300,400) is the open frontier interval; id=300 stays in the DEFAULT.
create table public.m (id bigint generated by default as identity primary key, body text);
insert into public.m (body) select 'x' from generate_series(1, 300);
create table public.ref (rid bigint generated by default as identity primary key,
                         m_id bigint references public.m(id));
insert into public.ref (m_id) select 1 + floor(random() * 300)::int from generate_series(1, 100);

select pgpm.adopt('public.m', 'id', 100, p_premake => 2, p_drain_batch => 500,
                        p_paused => false, p_incoming_fks => 'preserve');

select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.ref'::regclass and contype = 'f'),
  0, 'preserve dropped the incoming FK at adopt');
select is(
  (select count(*)::int from pgpm.dropped_fk where parent_table = 'public.m'::regclass),
  1, 'the FK was recorded for restoration');

-- gate: while the closed tail is still in the DEFAULT, restore is a no-op
select is(
  (select pgpm.restore_incoming_fks('public.m')),
  0, 'restore is a no-op while closed rows remain in the DEFAULT');

-- drive the scheduled path: a handful of maintenance ticks drain the closed tail and then auto-restore
do $$ begin for i in 1..12 loop perform pgpm.maintenance('public.m'); end loop; end $$;

select is(
  (select closed_rows from pgpm.check_default('public.m')),
  0::bigint, 'maintenance drained the closed tail');
select is(
  (select count(*)::int from pg_constraint
     where conrelid = 'public.ref'::regclass and contype = 'f' and confrelid = 'public.m'::regclass),
  1, 'maintenance auto-restored the FK against the new parent');
select throws_ok(
  $$ insert into public.ref (m_id) values (999999999) $$,
  '23503', NULL, 'the auto-restored FK is enforced');
select is(
  (select count(*)::int from pgpm.dropped_fk
     where parent_table = 'public.m'::regclass and restored_at is null),
  0, 'no preserved FK left pending after the auto-restore (record kept, marked live)');

select * from finish();
rollback;
