-- Incoming-FK preservation on the id happy path: since pgpm never rewrites the PK, the referenced
-- unique key always survives, so several incoming FKs are all preserved and restored together. The
-- companion case -- a table whose PK excludes the control column -- is refused before any FK handling
-- (pgpm does not partition it at all); we check that too. See DESIGN.md section 8.
create extension if not exists pgtap;

begin;
select plan(5);

-- ---- a table whose PK excludes the control column is refused (so its FKs are never touched) -------
create table public.mt (id bigint generated by default as identity primary key,
                        created_at timestamptz not null default now(), body text);
insert into public.mt (body) select 'x' from generate_series(1, 50);
create table public.reft (rid bigint generated by default as identity primary key,
                          m_id bigint references public.mt(id));
insert into public.reft (m_id) select 1 + floor(random() * 50)::int from generate_series(1, 20);

select throws_ok(
  $$ select pgpm.adopt('public.mt', 'created_at', interval '1 month', p_incoming_fks => 'preserve') $$,
  'P0001', NULL,
  'adopt refuses a table whose primary key (id) excludes the control column (created_at)');
select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.reft'::regclass and contype = 'f'),
  1, 'the refusal mutated nothing: the incoming FK is intact');
select is(
  (select relkind::text from pg_class where oid = 'public.mt'::regclass),
  'r', 'the refusal mutated nothing: mt is still a plain table');

-- ---- id happy path with TWO incoming FKs: both preserved and restored ----------------------------
create table public.m (id bigint generated by default as identity primary key, body text);
insert into public.m (body) select 'x' from generate_series(1, 200);
create table public.ref_a (rid bigint generated by default as identity primary key,
                           m_id bigint references public.m(id));
create table public.ref_b (rid bigint generated by default as identity primary key,
                           m_id bigint references public.m(id));
insert into public.ref_a (m_id) select 1 + floor(random() * 200)::int from generate_series(1, 30);
insert into public.ref_b (m_id) select 1 + floor(random() * 200)::int from generate_series(1, 30);

select pgpm.adopt('public.m', 'id', 100000000, p_drain_batch => 50, p_incoming_fks => 'preserve');
select pgpm.drain_all('public.m', p_include_open => true);

select is(
  (select pgpm.restore_incoming_fks('public.m')),
  2, 'both eligible incoming FKs are restored');
select is(
  (select count(*)::int from pg_constraint
     where conrelid in ('public.ref_a'::regclass, 'public.ref_b'::regclass)
       and contype = 'f' and confrelid = 'public.m'::regclass),
  2, 'both FKs reference the new parent again');

select * from finish();
rollback;
