-- Incoming-FK preservation carries the FK's attributes. Because 'preserve' records the FK's full
-- definition (pg_get_constraintdef) and restore_incoming_fks re-adds it verbatim, the referential
-- action (ON DELETE CASCADE / SET NULL / ...) and DEFERRABLE-ness ride along unchanged. See
-- DESIGN.md section 8.
create extension if not exists pgtap;

begin;
select plan(4);

-- ON DELETE CASCADE: preserved and still fires after restore
create table public.mc (id bigint generated by default as identity primary key, body text);
insert into public.mc (body) select 'x' from generate_series(1, 50);
create table public.refc (rid bigint generated by default as identity primary key,
                          m_id bigint references public.mc(id) on delete cascade);
insert into public.refc (m_id) select 1 from generate_series(1, 10);   -- all reference id=1
select pgpm.adopt('public.mc', 'id', 100000000, p_drain_batch => 20, p_incoming_fks => 'preserve');
select pgpm.drain_all('public.mc', p_include_open => true);
select pgpm.restore_incoming_fks('public.mc');
select is(
  (select confdeltype from pg_constraint where conrelid = 'public.refc'::regclass and contype = 'f' limit 1),
  'c', 'ON DELETE CASCADE is preserved through preserve/restore');
delete from public.mc where id = 1;
select is(
  (select count(*)::int from public.refc),
  0, 'the restored CASCADE fires: children removed with their parent');

-- ON DELETE SET NULL: preserved
create table public.msn (id bigint generated by default as identity primary key, body text);
insert into public.msn (body) select 'x' from generate_series(1, 50);
create table public.refn (rid bigint generated by default as identity primary key,
                          m_id bigint references public.msn(id) on delete set null);
insert into public.refn (m_id) select 1 from generate_series(1, 10);
select pgpm.adopt('public.msn', 'id', 100000000, p_drain_batch => 20, p_incoming_fks => 'preserve');
select pgpm.drain_all('public.msn', p_include_open => true);
select pgpm.restore_incoming_fks('public.msn');
select is(
  (select confdeltype from pg_constraint where conrelid = 'public.refn'::regclass and contype = 'f' limit 1),
  'n', 'ON DELETE SET NULL is preserved');

-- DEFERRABLE INITIALLY DEFERRED: preserved (and the re-add syntax accepts it)
create table public.md (id bigint generated by default as identity primary key, body text);
insert into public.md (body) select 'x' from generate_series(1, 50);
create table public.refd (rid bigint generated by default as identity primary key,
                          m_id bigint references public.md(id) deferrable initially deferred);
insert into public.refd (m_id) select 1 + floor(random() * 50)::int from generate_series(1, 10);
-- fire the deferred FK checks now: in this single test transaction they would otherwise stay pending,
-- and a constraint cannot be dropped while its table has pending trigger events (a non-issue in real
-- autocommit use, where the insert commits before adopt is called).
set constraints all immediate;
select pgpm.adopt('public.md', 'id', 100000000, p_drain_batch => 20, p_incoming_fks => 'preserve');
select pgpm.drain_all('public.md', p_include_open => true);
select pgpm.restore_incoming_fks('public.md');
select is(
  (select condeferrable from pg_constraint where conrelid = 'public.refd'::regclass and contype = 'f' limit 1),
  true, 'DEFERRABLE is preserved');

select * from finish();
rollback;
