-- Incoming-FK preservation handles a self-referential FK (e.g. employees.mgr_id -> employees.id).
-- It is detected as an incoming FK (confrelid = the adopted table), recorded, and dropped; after the
-- drain it is re-added against the new parent. Because the referencing side is now partitioned,
-- Postgres rejects a NOT VALID re-add, so restore_incoming_fks adds it validating in one step. The FK
-- ends up on the parent and is enforced across all partitions. See DESIGN.md section 8.
create extension if not exists pgtap;

begin;
select plan(5);

create table public.emp (id bigint generated by default as identity primary key,
                         mgr_id bigint references public.emp(id), name text);
insert into public.emp (mgr_id, name) values (null, 'root');             -- id = 1
insert into public.emp (mgr_id, name) select 1, 'e' || g from generate_series(2, 60) g;

select pgpm.adopt('public.emp', 'id', 100000000, p_drain_batch => 20, p_incoming_fks => 'preserve');

select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.emp'::regclass and contype = 'f'),
  0, 'the self-referential FK is dropped for the conversion');
select is(
  (select count(*)::int from pgpm.dropped_fk where parent_table = 'public.emp'::regclass),
  1, 'the self-referential FK is recorded for restoration');

select pgpm.drain_all('public.emp', p_include_open => true);

select is(
  (select pgpm.restore_incoming_fks('public.emp')),
  1, 'the self-referential FK is restored');
select is(
  (select count(*)::int from pg_constraint
     where conrelid = 'public.emp'::regclass and confrelid = 'public.emp'::regclass and contype = 'f'),
  1, 'the restored FK is on the partitioned parent, referencing itself');
select throws_ok(
  $$ insert into public.emp (id, mgr_id, name) values (999999, 12345678, 'bad') $$,
  '23503', NULL, 'the restored self-referential FK is enforced across partitions');

select * from finish();
rollback;
