-- Managed-FK lifecycle: once an incoming FK is restored, a LATER drain (e.g. a premake miss drops
-- rows into the DEFAULT for an interval that then closes) must not move referenced rows past the live
-- FK. With a live ON DELETE CASCADE FK that would silently cascade-delete the referencing rows. So
-- maintenance suspends the managed FK whenever the closed tail has work and restores it once drained:
-- a managed FK is live iff the closed tail is empty. See DESIGN.md section 8.
create extension if not exists pgtap;

begin;
select plan(6);

-- explicit ids so we can stage a "late-arriving" closed-tail row deterministically; step 100
create table public.m (id bigint primary key, body text);
insert into public.m select g, 'x' from generate_series(1, 50) g;          -- ids 1..50, interval [0,100)
create table public.refx (rid bigint generated by default as identity primary key,
                          m_id bigint references public.m(id) on delete cascade);

select pgpm.adopt('public.m', 'id', 100, p_premake => 2, p_drain_batch => 500,
                        p_paused => false, p_incoming_fks => 'preserve');
-- convert the backlog and restore the FK (now live)
select pgpm.drain_all('public.m', p_include_open => true);
select pgpm.restore_incoming_fks('public.m');
-- count only the top-level FK (conparentid = 0): an FK to a partitioned table has internal
-- per-partition clone rows in pg_constraint too.
select is(
  (select count(*)::int from pg_constraint
     where conrelid = 'public.refx'::regclass and contype = 'f' and conparentid = 0),
  1, 'the incoming CASCADE FK is live after the backlog drain + restore');

-- premake miss: a referenced row lands in the DEFAULT for an interval that is now closed
insert into public.m (id, body) values (305, 'frontier');   -- advances the frontier
insert into public.m (id, body) values (150, 'late');        -- [100,200) is now closed; no partition -> DEFAULT
insert into public.refx (m_id) values (150);                 -- a live CASCADE reference to that row
select cmp_ok(
  (select closed_rows from pgpm.check_default('public.m')), '>', 0::bigint,
  'a referenced row sits in the closed tail of the DEFAULT (premake miss)');

-- maintenance must suspend the FK before draining, drain the tail, then re-restore
do $$ begin for i in 1..8 loop perform pgpm.maintenance('public.m'); end loop; end $$;

select is(
  (select count(*)::int from public.refx where m_id = 150),
  1, 'the referenced row was NOT cascade-deleted by the catch-up drain');
select is(
  (select closed_rows from pgpm.check_default('public.m')),
  0::bigint, 'the catch-up drain completed');
select is(
  (select count(*)::int from pg_constraint
     where conrelid = 'public.refx'::regclass and contype = 'f'
       and confrelid = 'public.m'::regclass and conparentid = 0),
  1, 'the managed FK is restored again after the catch-up drain');
select throws_ok(
  $$ insert into public.refx (m_id) values (88888888) $$,
  '23503', NULL, 'the re-restored FK is enforced');

select * from finish();
rollback;
