-- pgpm never rewrites the primary key (DESIGN.md sec 8). adopt reuses the existing PK when the
-- control column is a MEMBER of it (Postgres requires a partitioned PK only to INCLUDE the partition
-- key, not lead it), works on a table with no PK at all, and refuses a table whose PK excludes the
-- control column rather than widening it.
create extension if not exists pgtap;

begin;
select plan(6);

-- (A) broadening: composite PK (tenant_id, id), partitioned by id -- id is IN the PK but does not
--     lead it. The existing PK index is reused in place (no rebuild).
create table public.multi (tenant_id bigint not null, id bigint generated by default as identity,
                           body text, primary key (tenant_id, id));
insert into public.multi (tenant_id, body) select 1, 'x' from generate_series(1, 100);
create temporary table _pk_before on commit drop as
  select i.indexrelid::oid as idx from pg_index i
   where i.indrelid = 'public.multi'::regclass and i.indisprimary;
select lives_ok(
  $$ select pgpm.adopt('public.multi', 'id', 100000) $$,
  'adopt accepts a composite PK partitioned by a non-leading member of it');
select is(
  (select relkind::text from pg_class where oid = 'public.multi'::regclass),
  'p', 'multi became a partitioned table');
select is(
  (select i.indexrelid::oid from pg_index i
     where i.indrelid = 'public.multi_default'::regclass and i.indisprimary),
  (select idx from _pk_before),
  'the existing PK index was reused in place (oid preserved, never rebuilt)');

-- (B) no-PK table: nothing to preserve, adopt is fine and invents no primary key
create table public.nopk (id bigint, body text);
insert into public.nopk (id, body) select g, 'x' from generate_series(1, 100) g;
select lives_ok(
  $$ select pgpm.adopt('public.nopk', 'id', 100000) $$,
  'adopt accepts a table with no primary key');
select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.nopk'::regclass and contype = 'p'),
  0, 'the no-PK parent has no primary key (none is invented)');

-- (C) refusal: a PK that excludes the control column is refused (no widening)
create table public.idpk (id bigint generated by default as identity primary key,
                          created_at timestamptz not null default now(), body text);
insert into public.idpk (body) select 'x' from generate_series(1, 50);
select throws_ok(
  $$ select pgpm.adopt('public.idpk', 'created_at', interval '1 month') $$,
  'P0001', NULL,
  'adopt refuses when the primary key excludes the control column');

select * from finish();
rollback;
