-- pgpm never rewrites the primary key (REDESIGN.md). transmute reuses the existing PK when the
-- control column is a MEMBER of it (Postgres requires a partitioned PK only to INCLUDE the partition
-- key, not lead it), and refuses a table whose PK excludes the control column rather than widening it.
-- (A keyless table is now accepted when the control column is NOT NULL -- see tests/52; here the no-key
-- table has a nullable control column, so it is refused for the NOT NULL requirement.)
create extension if not exists pgtap;

begin;
select plan(6);

-- (A) broadening: composite PK (tenant_id, id), partitioned by id -- id is IN the PK but does not
--     lead it. The existing PK index is reused in place (no rebuild).
create table public.multi (tenant_id bigint not null, id bigint generated by default as identity,
                           body text, primary key (tenant_id, id));
insert into public.multi (tenant_id, body) select 1, 'x' from generate_series(1, 100);
create temporary table _pk_before on commit drop as
  select i.indexrelid::oid as idx from pg_index i
   where i.indrelid = 'public.multi'::regclass and i.indisprimary;
select lives_ok(
  $$ select pgpm.transmute('public.multi', 'id', 100000) $$,
  'transmute accepts a composite PK partitioned by a non-leading member of it');
select is(
  (select relkind::text from pg_class where oid = 'public.multi'::regclass),
  'p', 'multi became a partitioned table');
select is(
  (select count(*)::int from pg_index where indexrelid = (select idx from _pk_before)),
  1, 'the existing PK index object survives (reused in place on the monolith, never rebuilt)');

-- (B) no-key table with a NULLABLE control column: refused up front -- a keyless table is partitionable
--     only when the control column is NOT NULL (a partition key cannot be null, and pgpm never scans).
create table public.nopk (id bigint, body text);   -- id is nullable, and there is no key
insert into public.nopk (id, body) select g, 'x' from generate_series(1, 100) g;
select throws_like(
  $$ select pgpm.transmute('public.nopk', 'id', 100000) $$,
  'pg_partition_magician:%NOT NULL%',
  'transmute refuses a keyless table whose control column is nullable, naming NOT NULL');
select is(
  (select relkind::text from pg_class where oid = 'public.nopk'::regclass),
  'r', 'the refusal is up front: nopk is left a plain table, not transmuted');

-- (C) refusal: a PK that excludes the control column is refused (no widening)
create table public.idpk (id bigint generated by default as identity primary key,
                          created_at timestamptz not null default now(), body text);
insert into public.idpk (body) select 'x' from generate_series(1, 50);
select throws_ok(
  $$ select pgpm.transmute('public.idpk', 'created_at', interval '1 month') $$,
  'P0001', NULL,
  'transmute refuses when the primary key excludes the control column');

select * from finish();
rollback;
