-- Adaptive closed-loop feathering (DESIGN.md section 8, mode 2). The drain row budget is no longer a
-- fixed constant: when drain_adaptive is on, maintenance senses checkpoint pressure (a forced/requested
-- checkpoint since the last tick = over-driving the disk) and rides the budget just under supply via
-- AIMD -- additive-increase on a calm tick, halve on congestion. Off by default (mode 1, fixed rate).
create extension if not exists pgtap;

begin;
select plan(13);

-- ---- the pure controller: AIMD arithmetic, independent of any server state -------------------------
select is(pgpm._aimd_next(10000, false, 1000, 64000, 1000), 11000,
          'calm tick: additive-increase by the increment');
select is(pgpm._aimd_next(10000, true, 1000, 64000, 1000), 5000,
          'congested tick: multiplicative-decrease (halve)');
select is(pgpm._aimd_next(1500, true, 1000, 64000, 1000), 1000,
          'decrease clamps at the floor (never starves forward progress)');
select is(pgpm._aimd_next(64000, false, 1000, 64000, 1000), 64000,
          'increase clamps at the ceiling (never over-probes)');

-- ---- the sensor: version-aware forced-checkpoint counter -------------------------------------------
select cmp_ok(pgpm._forced_checkpoints(), '>=', 0::bigint,
              'forced-checkpoint sensor returns a non-negative counter on this PG version');

-- ---- fixture: an id-kind table with many closed intervals to drain --------------------------------
-- step 100, ids 1..1000 => intervals [0,100)..[900,1000) -- the lower ones are CLOSED (need draining),
-- the highest is the open frontier. One maintenance tick drains one interval, so the loop below has
-- plenty of intervals to exercise the controller across many ticks.
create table public.evt (id bigint generated by default as identity primary key, body text);
insert into public.evt (body) select 'x' from generate_series(1, 1000);
select pgpm.adopt('public.evt', 'id', 100, p_premake => 2, p_drain_batch => 8000, p_paused => false);

-- ---- default is mode 1 (fixed): adaptive off, controller state untouched ---------------------------
select is((select drain_adaptive from pgpm.config where parent_table = 'public.evt'::regclass),
          false, 'adaptive is off by default (mode 1, fixed rate)');
select lives_ok($$ select pgpm.maintenance('public.evt') $$, 'a fixed-mode maintenance tick runs');
select is((select drain_budget from pgpm.config where parent_table = 'public.evt'::regclass),
          NULL, 'fixed mode never populates the adaptive budget');

-- ---- the setter flips the mode on --------------------------------------------------------------------
select pgpm.set_drain_adaptive('public.evt', true);
select is((select drain_adaptive from pgpm.config where parent_table = 'public.evt'::regclass),
          true, 'set_drain_adaptive(true) turns mode 2 on');

-- ---- a calm tick (baseline == current counter => no congestion) recovers the budget UP toward the
--      ceiling (start below it; drain_batch=8000 is the ceiling, recovery step is 8000/8=1000) --------
update pgpm.config set drain_budget = 4000, drain_ckpt_seen = pgpm._forced_checkpoints()
  where parent_table = 'public.evt'::regclass;
select pgpm.maintenance('public.evt');
select cmp_ok((select drain_budget from pgpm.config where parent_table = 'public.evt'::regclass),
              '>', 4000, 'calm tick: the controller recovers the budget upward toward the ceiling');

-- ---- a congested tick (baseline below current counter => +delta) backs the budget OFF (halves) -----
update pgpm.config set drain_budget = 8000, drain_ckpt_seen = pgpm._forced_checkpoints() - 1
  where parent_table = 'public.evt'::regclass;
select pgpm.maintenance('public.evt');
select cmp_ok((select drain_budget from pgpm.config where parent_table = 'public.evt'::regclass),
              '<', 8000, 'congested tick: the controller backs the budget off (forced checkpoint sensed)');

-- ---- correctness is preserved: adaptive still drains the closed tail to zero -----------------------
do $$ begin for i in 1..40 loop perform pgpm.maintenance('public.evt'); end loop; end $$;
select is((select closed_rows from pgpm.check_default('public.evt')),
          0::bigint, 'adaptive mode still drains the closed tail to zero');

-- ---- the safety invariant: the budget NEVER exceeds drain_batch (the ceiling). A bigger batch would
--      mean a bigger WAL spike, so adaptive only ever feathers DOWN from the operator's tuned rate. ---
select cmp_ok((select drain_budget from pgpm.config where parent_table = 'public.evt'::regclass),
              '<=', 8000, 'budget never exceeds drain_batch: adaptive only throttles down (cannot worsen the tail)');

select * from finish();
rollback;
