-- untransmute reverses a transmute while it is still reversible. transmute moves no data: the original
-- table is renamed and attached as the bounded MONOLITH child, holding the whole table, while a fresh
-- empty DEFAULT and (after obtain) empty forward partitions sit alongside it. untransmute detaches the
-- monolith, drops the childless parent (cascading the empty default and forward partitions), renames the
-- monolith back, and restores what transmute changed (identity moved to the parent, preserved incoming
-- FKs). It stays reversible through obtain (forward partitions are empty); it is a one-way door once a
-- row lands OUTSIDE the monolith (past B, in a forward partition) or regraining splits the monolith.
create extension if not exists pgtap;

select plan(21);

-- (A) round trip: a live table with data, a composite PK, an identity column, and a secondary index
--     comes back exactly as it was.
create table public.rt (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
create index rt_body_idx on public.rt (body);
insert into public.rt (created_at, body)
  select now() - (g || ' minutes')::interval, 'b' || g from generate_series(1, 100) g;

call pgpm.transmute('public.rt', 'created_at', interval '1 month');
select pass('transmute converts the table');
select is(
  (select relkind::text from pg_class where oid = 'public.rt'::regclass),
  'p', 'rt is a partitioned table after transmute');

select lives_ok(
  $$ select pgpm.untransmute('public.rt') $$,
  'untransmute reverses it');
select is(
  (select relkind::text from pg_class where oid = 'public.rt'::regclass),
  'r', 'rt is an ordinary (un-partitioned) table again');
select is(
  (select count(*)::int from public.rt),
  100, 'all rows are preserved');
select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.rt'::regclass and contype = 'p'),
  1, 'the primary key is restored');
select is(
  (select count(*)::int from pg_attribute
    where attrelid = 'public.rt'::regclass and attname = 'id' and attidentity in ('a', 'd')),
  1, 'the identity column is restored');
select is(
  (select count(*)::int from pg_class where oid = 'public.rt_body_idx'::regclass),
  1, 'the secondary index is restored under its original name');
insert into public.rt (created_at, body) values (now(), 'z');   -- relies on the restored identity
select is(
  (select max(id)::bigint from public.rt),
  101::bigint, 'the identity sequence is reseeded, the next insert lands at max+1 (no collision)');
select is(
  (select count(*)::int from pgpm.config where parent_table = 'public.rt'::regclass),
  0, 'the config registration is removed');

-- (B) the gate (REDESIGN.md section 13): transmute + obtain is STILL reversible -- the forward
--     partitions obtain builds are empty and the monolith holds the whole table.
create table public.gated (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.gated (created_at, body)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 50) g;
call pgpm.transmute('public.gated', 'created_at', interval '1 month');
select pass('transmute the gated table');
select lives_ok(
  $$ select pgpm.obtain('public.gated') $$,
  'obtain builds empty forward partitions ahead of the frontier');
select lives_ok(
  $$ select pgpm.untransmute('public.gated') $$,
  'transmute + obtain is still reversible (forward partitions empty, the monolith holds everything)');
select is(
  (select relkind::text from pg_class where oid = 'public.gated'::regclass),
  'r', 'gated is an ordinary table again after the reversal');

-- (B2) the one-way door: a row lands OUTSIDE the monolith (past B, in a forward partition), so a
--      metadata-only reverse would lose it and untransmute refuses (Tier 2 foldback is not built).
create table public.gated2 (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.gated2 (created_at, body)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 50) g;
call pgpm.transmute('public.gated2', 'created_at', interval '1 month');
select pass('transmute the gated2 table');
select lives_ok(
  $$ select pgpm.obtain('public.gated2') $$,
  'obtain builds empty forward partitions');
insert into public.gated2 (created_at, body) values (now() + interval '45 days', 'future');  -- past B
select throws_ok(
  $$ select pgpm.untransmute('public.gated2') $$,
  'P0001', NULL,
  'untransmute refuses once a row lands outside the monolith (past B)');

-- (C) a preserved incoming FK survives the round trip: dropped by transmute, re-added by untransmute
--     against the rebuilt parent.
create table public.cparent (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.cparent (created_at, body)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 20) g;
create table public.cchild (
  id          bigint primary key,
  ref_created timestamptz,
  ref_id      bigint,
  foreign key (ref_created, ref_id) references public.cparent (created_at, id)
);
call pgpm.transmute('public.cparent', 'created_at', interval '1 month', p_incoming_fks => 'preserve');
select pass('transmute the FK-referenced parent, preserving the incoming FK');
select lives_ok(
  $$ select pgpm.untransmute('public.cparent') $$,
  'untransmute the FK-referenced parent');
select is(
  (select count(*)::int from pg_constraint
    where conrelid = 'public.cchild'::regclass and contype = 'f'
      and confrelid = 'public.cparent'::regclass),
  1, 'the incoming FK is restored against the rebuilt parent');

-- (D) a table pgpm does not manage cannot be untransmuted.
create table public.unmanaged (id bigint primary key, body text);
select throws_ok(
  $$ select pgpm.untransmute('public.unmanaged') $$,
  'P0001', NULL,
  'untransmute refuses a table pgpm does not manage');

select * from finish();
