-- untransmute reverses a transmute while it is still reversible. transmute moves no data and creates
-- no real partitions (attain does that, later), so until maintenance/attain runs the DEFAULT still
-- holds the whole table and the original table is sitting there untouched, merely renamed and
-- attached. untransmute detaches the DEFAULT, drops the childless parent, renames the DEFAULT back,
-- and restores what transmute changed (identity moved to the parent, autovacuum knobs, preserved
-- incoming FKs). It is a one-way door the moment a real partition exists.
create extension if not exists pgtap;

begin;
select plan(17);

-- (A) round trip: a live table with data, a composite PK, an identity column, and a secondary index
--     comes back exactly as it was.
create table public.rt (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
create index rt_body_idx on public.rt (body);
insert into public.rt (created_at, body)
  select now() - (g || ' minutes')::interval, 'b' || g from generate_series(1, 100) g;

select lives_ok(
  $$ select pgpm.transmute('public.rt', 'created_at', interval '1 month') $$,
  'transmute converts the table');
select is(
  (select relkind::text from pg_class where oid = 'public.rt'::regclass),
  'p', 'rt is a partitioned table after transmute');

select lives_ok(
  $$ select pgpm.untransmute('public.rt') $$,
  'untransmute reverses it');
select is(
  (select relkind::text from pg_class where oid = 'public.rt'::regclass),
  'r', 'rt is an ordinary (un-partitioned) table again');
select is(
  (select count(*)::int from public.rt),
  100, 'all rows are preserved');
select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.rt'::regclass and contype = 'p'),
  1, 'the primary key is restored');
select is(
  (select count(*)::int from pg_attribute
    where attrelid = 'public.rt'::regclass and attname = 'id' and attidentity in ('a', 'd')),
  1, 'the identity column is restored');
select is(
  (select count(*)::int from pg_class where oid = 'public.rt_body_idx'::regclass),
  1, 'the secondary index is restored under its original name');
insert into public.rt (created_at, body) values (now(), 'z');   -- relies on the restored identity
select is(
  (select max(id)::bigint from public.rt),
  101::bigint, 'the identity sequence is reseeded, the next insert lands at max+1 (no collision)');
select is(
  (select count(*)::int from pgpm.config where parent_table = 'public.rt'::regclass),
  0, 'the config registration is removed');

-- (B) the gate: once attain has created real partitions, the DEFAULT no longer holds the whole
--     table, so untransmute refuses (one-way door).
create table public.gated (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.gated (created_at, body)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 50) g;
select lives_ok(
  $$ select pgpm.transmute('public.gated', 'created_at', interval '1 month') $$,
  'transmute the gated table');
select lives_ok(
  $$ select pgpm.attain('public.gated') $$,
  'attain builds real partitions ahead of the frontier');
select throws_ok(
  $$ select pgpm.untransmute('public.gated') $$,
  'P0001', NULL,
  'untransmute refuses once real partitions exist');

-- (C) a preserved incoming FK survives the round trip: dropped by transmute, re-added by untransmute
--     against the rebuilt parent.
create table public.cparent (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.cparent (created_at, body)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 20) g;
create table public.cchild (
  id          bigint primary key,
  ref_created timestamptz,
  ref_id      bigint,
  foreign key (ref_created, ref_id) references public.cparent (created_at, id)
);
select lives_ok(
  $$ select pgpm.transmute('public.cparent', 'created_at', interval '1 month', p_incoming_fks => 'preserve') $$,
  'transmute the FK-referenced parent, preserving the incoming FK');
select lives_ok(
  $$ select pgpm.untransmute('public.cparent') $$,
  'untransmute the FK-referenced parent');
select is(
  (select count(*)::int from pg_constraint
    where conrelid = 'public.cchild'::regclass and contype = 'f'
      and confrelid = 'public.cparent'::regclass),
  1, 'the incoming FK is restored against the rebuilt parent');

-- (D) a table pgpm does not manage cannot be untransmuted.
create table public.unmanaged (id bigint primary key, body text);
select throws_ok(
  $$ select pgpm.untransmute('public.unmanaged') $$,
  'P0001', NULL,
  'untransmute refuses a table pgpm does not manage');

select * from finish();
rollback;
