-- transmute registers a table PAUSED by default (the cautious two-step: convert, inspect, then go
-- live). pause()/resume() are the first-class way to flip that flag, so operators never hand-edit
-- pgpm.config. maintenance is a no-op while paused and acts once resumed.
create extension if not exists pgtap;

begin;
select plan(10);

create table public.pr (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.pr (created_at, body)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 30) g;

-- transmute with no p_paused: the default is paused (cautious).
select lives_ok(
  $$ select pgpm.transmute('public.pr', 'created_at', interval '1 month') $$,
  'transmute the table (paused by default)');
select is(
  (select paused from pgpm.config where parent_table = 'public.pr'::regclass),
  true, 'transmute registers the table paused by default');
select is(
  pgpm.maintenance('public.pr'),
  'paused', 'maintenance is a no-op while paused');

-- resume: scheduled maintenance acts.
select lives_ok(
  $$ select pgpm.resume('public.pr') $$,
  'resume the table');
select is(
  (select paused from pgpm.config where parent_table = 'public.pr'::regclass),
  false, 'resume clears the paused flag');
select isnt(
  pgpm.maintenance('public.pr'),
  'paused', 'maintenance acts once resumed');

-- pause: back to a no-op.
select lives_ok(
  $$ select pgpm.pause('public.pr') $$,
  'pause the table');
select is(
  (select paused from pgpm.config where parent_table = 'public.pr'::regclass),
  true, 'pause sets the paused flag');
select is(
  pgpm.maintenance('public.pr'),
  'paused', 'maintenance is a no-op again while paused');

-- a table pgpm does not manage cannot be paused/resumed.
create table public.pr_unmanaged (id bigint primary key, body text);
select throws_ok(
  $$ select pgpm.resume('public.pr_unmanaged') $$,
  'P0001', NULL,
  'resume refuses a table pgpm does not manage');

select * from finish();
rollback;
