-- transmute exposes p_drain_adaptive (default false) so the operator chooses adaptive feathering at
-- conversion time, alongside p_obtain / p_retain / p_drain_batch, instead of a separate post-transmute
-- set_drain_adaptive() call. The default stays false (the predictable fixed-gentle rate).
create extension if not exists pgtap;

begin;
select plan(3);

-- (A) time overload, opt in: the flag lands in config.
create table public.a_on (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  body text, primary key (created_at, id)
);
insert into public.a_on (created_at, body)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 20) g;
select pgpm.transmute('public.a_on', 'created_at', interval '1 month', p_drain_adaptive => true);
select is(
  (select drain_adaptive from pgpm.config where parent_table = 'public.a_on'::regclass),
  true, 'transmute(..., p_drain_adaptive => true) registers the table with adaptive on');

-- (B) default: adaptive stays off.
create table public.a_off (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  body text, primary key (created_at, id)
);
insert into public.a_off (created_at, body)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 20) g;
select pgpm.transmute('public.a_off', 'created_at', interval '1 month');
select is(
  (select drain_adaptive from pgpm.config where parent_table = 'public.a_off'::regclass),
  false, 'adaptive is off by default (the fixed-gentle rate)');

-- (C) id overload also accepts the flag.
create table public.a_id (
  id bigint generated by default as identity primary key,
  body text
);
insert into public.a_id (body) select 'x' from generate_series(1, 20);
select pgpm.transmute('public.a_id', 'id', 100000, p_drain_adaptive => true);
select is(
  (select drain_adaptive from pgpm.config where parent_table = 'public.a_id'::regclass),
  true, 'the id overload accepts p_drain_adaptive too');

select * from finish();
rollback;
