-- The drain visibility gap, made concrete, and the snapshot() escape hatch. regrain() (bulk) never opens
-- the gap -- it copies and swaps atomically. The ASSISTANT drain, evacuating strays in microbatches,
-- still can: during a multi-batch drain the already-moved rows live in an unattached child, so
-- `select from parent` UNDERCOUNTS the interval being drained. pgpm.snapshot(null::<parent>) UNIONs the
-- parent with the in-flight child, giving a consistency-sensitive reader the complete set inline.
create extension if not exists pgtap;

begin;
select plan(5);

create table public.snap (
  id bigint generated by default as identity,
  created_at timestamptz not null,
  body text, primary key (created_at, id)
);
insert into public.snap (created_at, body)
  select now() - (g || ' minutes')::interval, 'recent' from generate_series(1, 10) g;   -- recent -> monolith
-- small batch so one interval needs several microbatches
select pgpm.transmute('public.snap', 'created_at', interval '1 month', p_drain_batch => 10, p_paused => false);
-- 30 strays, all in one CLOSED past interval (two months ago), land in the DEFAULT
insert into public.snap (created_at, body)
  select date_trunc('month', now()) - interval '2 months' + (g || ' seconds')::interval, 'stray'
  from generate_series(1, 30) g;

select is((select count(*)::int from public.snap), 40, 'all 40 rows are visible through the parent before any drain');

select ok(pgpm.drain_step('public.snap') like 'moved:%',
  'first drain step moves a batch but does not attach (interval not yet empty)');

select cmp_ok(
  (select count(*)::int from public.snap), '<', 40,
  'mid-drain, a plain read of the parent UNDERCOUNTS (moved rows are in the unattached child)');

select is(
  (select count(*)::int from pgpm.snapshot(null::public.snap)),
  40, 'snapshot() restores the complete row set during the drain');

select pgpm.drain_all('public.snap');
select is(
  (select count(*)::int from public.snap),
  40, 'after the interval fully drains and attaches, the parent is whole again');

select * from finish();
rollback;
