-- The drain visibility gap, made concrete, and the snapshot() escape hatch. During a multi-batch
-- drain the already-moved rows live in an unattached child, so `select from parent` UNDERCOUNTS the
-- interval being drained. pgpm.snapshot(null::<parent>) is a set-returning function that UNIONs the
-- parent with the in-flight child, giving a consistency-sensitive reader the complete set inline.
-- Read-only; no fix exists for writes.
create extension if not exists pgtap;

begin;
select plan(5);

-- 30 rows, all in one CLOSED past interval (two months ago), so the drain will work it.
create table public.snap (
  id bigint generated by default as identity,
  created_at timestamptz not null,
  body text, primary key (created_at, id)
);
insert into public.snap (created_at, body)
  select date_trunc('month', now()) - interval '2 months' + (g || ' seconds')::interval, 'x'
  from generate_series(1, 30) g;

-- transmute with a small batch so one interval needs several microbatches.
select pgpm.transmute('public.snap', 'created_at', interval '1 month', p_drain_batch => 10);
select is((select count(*)::int from public.snap), 30, 'all 30 rows are visible through the parent before any drain');

-- one drain step: moves a batch into a standalone, not-yet-attached child (interval not yet empty).
select ok(pgpm.drain_step('public.snap') like 'moved:%', 'first drain step moves a batch but does not attach');

-- THE GAP: the moved rows are durable in the unattached child, but the parent now undercounts.
select cmp_ok(
  (select count(*)::int from public.snap), '<', 30,
  'mid-drain, a plain read of the parent UNDERCOUNTS (moved rows are in the unattached child)');

-- snapshot() unions the parent with the in-flight child, restoring the complete set, queried inline.
select is(
  (select count(*)::int from pgpm.snapshot(null::public.snap)),
  30, 'snapshot() restores the complete row set during the drain');

-- and no rows were lost: parent + snapshot agree once the rest drains and attaches.
select pgpm.drain_all('public.snap');
select is(
  (select count(*)::int from public.snap),
  30, 'after the interval fully drains and attaches, the parent is whole again');

select * from finish();
rollback;
