-- Regression test for issue #90. A non-PK UNIQUE secondary index is no longer silently dropped.
-- transmute CARRIES it onto the parent as a partitioned unique index when its key includes the
-- partition key (global uniqueness genuinely preserved, exactly as the PK is reused), and REFUSES with
-- guidance when it excludes the partition key (global uniqueness cannot be enforced on a partitioned
-- table) -- the same refuse-or-preserve contract as the PK and incoming-FK cases.
create extension if not exists pgtap;

begin;
select plan(5);

-- (A) UNIQUE(email) excludes the partition key (created_at) -> cannot be preserved -> refuse up front
create table public.u_excl (
  created_at timestamptz not null,
  id         bigint generated by default as identity,
  email      text not null,
  primary key (created_at, id)
);
create unique index u_excl_email on public.u_excl (email);
insert into public.u_excl (created_at, email)
  select now() - (g || ' days')::interval, 'u' || g || '@x' from generate_series(1, 10) g;

select throws_like(
  $$ select pgpm.transmute('public.u_excl', 'created_at', interval '1 month') $$,
  'pg_partition_magician:%UNIQUE%',
  'transmute refuses a unique secondary whose key excludes the partition key');
select is(
  (select relkind::text from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'u_excl'),
  'r', 'the refusal is up front: u_excl is left a plain table');

-- (B) UNIQUE(created_at, sku) includes the partition key -> carried onto the partitioned parent
create table public.u_incl (
  created_at timestamptz not null,
  id         bigint generated by default as identity,
  sku        text not null,
  primary key (created_at, id)
);
create unique index u_incl_sku on public.u_incl (created_at, sku);
insert into public.u_incl (created_at, sku)
  values (date_trunc('month', now()) - interval '2 months' + interval '5 days', 'DUP');
insert into public.u_incl (created_at, sku)
  select date_trunc('month', now()) - interval '3 months' + (g || ' days')::interval, 'sku' || g
  from generate_series(1, 10) g;

select lives_ok(
  $$ select pgpm.transmute('public.u_incl', 'created_at', interval '1 month', p_paused => false) $$,
  'transmute carries a unique secondary whose key includes the partition key');

-- the carried index exists on the partitioned parent as a (non-PK) partitioned unique index
select is(
  (select count(*)::int from pg_index i join pg_class c on c.oid = i.indrelid
     where c.relname = 'u_incl' and i.indisunique and not i.indisprimary),
  1, 'the unique secondary was carried onto the partitioned parent');

-- materialize the months as real partitions, then a duplicate of (created_at, sku) is rejected by the
-- carried index on the materialized partition (it propagated to the new child on attach)
select pgpm.drain_all('public.u_incl', p_include_open => true);
select throws_ok(
  $$ insert into public.u_incl (created_at, sku)
       values (date_trunc('month', now()) - interval '2 months' + interval '5 days', 'DUP') $$,
  '23505', NULL,
  'the carried unique index enforces global uniqueness on the materialized partition');

select * from finish();
rollback;
