-- Regression test for issue #91, carried into the monolith model. Retention bounds storage even when
-- strays land in the DEFAULT below the horizon: the drain DELETEs an interval entirely below
-- the retention horizon straight out of the DEFAULT (retain_reclaim) instead of materializing a doomed
-- partition that retain() would immediately drop. Within-horizon strays are materialized as normal.
create extension if not exists pgtap;

begin;
select plan(4);

create table public.ret_t (
  created_at timestamptz not null,
  id         bigint generated by default as identity,
  body       text,
  primary key (created_at, id)
);
insert into public.ret_t (created_at) select now() - (g || ' minutes')::interval from generate_series(1, 10) g;  -- recent -> monolith
select pgpm.transmute('public.ret_t', 'created_at', interval '1 month',
                  p_retain => interval '2 months', p_paused => false);

-- strays in the DEFAULT: 30 aged (months 3,4,5 ago, BELOW the 2-month horizon) and 10 within-horizon
-- (month 1 ago). The recent rows live in the monolith, not the DEFAULT.
insert into public.ret_t (created_at, body)
  select date_trunc('month', now()) - make_interval(months => m) + interval '10 days', 'm' || m
  from generate_series(3, 5) m, generate_series(1, 10) g;
insert into public.ret_t (created_at, body)
  select date_trunc('month', now()) - interval '1 month' + interval '10 days', 'within'
  from generate_series(1, 10) g;

select is(
  (select count(*)::int from public.ret_t_default
     where created_at < date_trunc('month', now()) - interval '2 months'),
  30, 'setup: 30 aged strays (below the horizon) sit in the DEFAULT');

select pgpm.drain_all('public.ret_t');

select is(
  (select count(*)::int from pgpm.snapshot(null::public.ret_t)
     where created_at < date_trunc('month', now()) - interval '2 months'),
  0, 'retention reclaimed the aged strays straight out of the DEFAULT (never materialized)');

select cmp_ok(
  (select count(*)::int from pgpm.log
     where parent_table = 'public.ret_t'::regclass and action = 'retain_reclaim'),
  '>', 0, 'the aged strays were reclaimed via direct DELETE (retain_reclaim), avoiding churn');

select is(
  (select count(*)::int from public.ret_t
     where created_at >= date_trunc('month', now()) - interval '2 months'),
  20, 'within-horizon rows survive (10 recent in the monolith + 10 within-horizon stray)');

select * from finish();
rollback;
