-- Regression test for issue #91. Retention bounds storage even when the drain lags. An interval
-- entirely below the retention horizon is DELETEd straight out of the DEFAULT by the (paced) drain,
-- instead of being materialized into a partition that retain() would immediately drop. So aged rows
-- that never made it out of the DEFAULT are still reclaimed, the within-horizon rows are untouched,
-- and no doomed partition is created for the aged tail (the materialize-then-drop churn is gone).
create extension if not exists pgtap;

begin;
select plan(4);

create table public.ret_t (
  created_at timestamptz not null,
  id         bigint generated by default as identity,
  body       text,
  primary key (created_at, id)
);
-- ten rows in each of the last six months (placed mid-month so each lands squarely in its interval);
-- nothing is drained yet, so it all lives in the DEFAULT. With retain '2 months' the boundary is
-- date_trunc('month', now()) - 2 months: months 0/1/2 are within the horizon (month 0 is the open
-- interval), months 3/4/5 are below it.
insert into public.ret_t (created_at, body)
  select date_trunc('month', now()) - make_interval(months => m) + interval '10 days', 'm' || m
  from generate_series(0, 5) m, generate_series(1, 10) g;

select pgpm.transmute('public.ret_t', 'created_at', interval '1 month',
                  p_retain => interval '2 months', p_paused => false);
select pgpm.obtain('public.ret_t');

select ok(
  (select count(*) from public.ret_t
     where created_at < date_trunc('month', now()) - interval '2 months') > 0,
  'setup: aged rows are present in the DEFAULT before draining');

-- one full pass over the closed intervals: below-horizon intervals are reclaimed, within-horizon ones
-- are materialized; the open (current) interval stays in the DEFAULT.
select pgpm.drain_all('public.ret_t');

-- the aged tail is reclaimed even though it was only ever in the DEFAULT (complete read via snapshot)
select is(
  (select count(*)::int from pgpm.snapshot(null::public.ret_t)
     where created_at < date_trunc('month', now()) - interval '2 months'),
  0, 'retention reclaimed the aged tail straight out of the un-drained DEFAULT');

-- the within-horizon rows (months 0, 1, 2 = 30 rows) are untouched
select is(
  (select count(*)::int from pgpm.snapshot(null::public.ret_t)
     where created_at >= date_trunc('month', now()) - interval '2 months'),
  30, 'within-horizon rows survive the reclaim');

-- the aged tail was reclaimed by a direct DELETE, not materialize-then-drop: the drain logged
-- retain_reclaim (and no drain_attach) for those intervals
select cmp_ok(
  (select count(*)::int from pgpm.log
     where parent_table = 'public.ret_t'::regclass and action = 'retain_reclaim'),
  '>', 0, 'the aged tail was reclaimed via direct DELETE (retain_reclaim), avoiding churn');

select * from finish();
rollback;
