-- Regression test for issue #92, in the monolith model. pgpm.status() surfaces the drain's
-- backlog (closed_rows -- strays awaiting evacuation) and a stall signal (last_drained + drain_skips),
-- so a WEDGED drain (closed_rows stuck > 0, no recent progress, climbing drain_skips) is distinguishable
-- from a merely slow one. The backlog here is a closed STRAY interval in the otherwise-empty DEFAULT.
create extension if not exists pgtap;

begin;
select plan(6);

create table public.s_t (
  created_at timestamptz not null,
  id         bigint generated by default as identity,
  body       text,
  primary key (created_at, id)
);
insert into public.s_t (created_at) select now() - (g || ' minutes')::interval from generate_series(1, 5) g;  -- recent -> monolith
select pgpm.transmute('public.s_t', 'created_at', interval '1 month', p_paused => false);
select pgpm.obtain('public.s_t');
-- a closed stray backlog in the DEFAULT (two past months, 20 rows); the recent rows are in the monolith
insert into public.s_t (created_at, body)
  select date_trunc('month', now()) - make_interval(months => m) + interval '10 days', 'x'
  from generate_series(1, 2) m, generate_series(1, 10) g;

-- (1) closed_rows is surfaced and matches the canonical check_default backlog
select is(
  (select closed_rows from pgpm.status() where parent = 'public.s_t'::regclass),
  (select closed_rows from pgpm.check_default('public.s_t')),
  'status() surfaces closed_rows, matching check_default');

-- (2) there is a drainable stray backlog before draining
select cmp_ok(
  (select closed_rows from pgpm.status() where parent = 'public.s_t'::regclass),
  '>', 0::bigint, 'closed_rows shows the drainable stray backlog before draining');

-- (3) no progress yet -> last_drained is null
select ok(
  (select last_drained from pgpm.status() where parent = 'public.s_t'::regclass) is null,
  'last_drained is null before any drain progress');

-- a wedged drain logs drain_skip without making progress; simulate one deferral
insert into pgpm.log (parent_table, action, method) values ('public.s_t'::regclass, 'drain_skip', 'simulated');

-- (4) the deferral is visible: closed_rows > 0 (above) + drain_skips > 0 + last_drained null = WEDGED
select cmp_ok(
  (select drain_skips from pgpm.status() where parent = 'public.s_t'::regclass),
  '>', 0::bigint, 'status() counts drain deferrals since the last progress (a wedge is visible)');

-- drain to completion: backlog clears and progress is recorded
select pgpm.drain_all('public.s_t', p_include_open => true);

-- (5) caught up: closed_rows back to 0
select is(
  (select closed_rows from pgpm.status() where parent = 'public.s_t'::regclass),
  0::bigint, 'after draining, closed_rows is 0 (caught up)');

-- (6) progress reset the stall signal: the earlier skip predates the last progress (lower log id)
select is(
  (select drain_skips from pgpm.status() where parent = 'public.s_t'::regclass),
  0::bigint, 'drain_skips resets to 0 once the drain makes progress');

select * from finish();
rollback;
