-- Regression test for issue #93, in the monolith model. drain_max_blocks bounds a microbatch by
-- heap+TOAST blocks. When the DEFAULT has no row stats yet (reltuples <= 0: a freshly created,
-- never-analyzed default with strays just inserted), the budget must NOT silently disable itself: it
-- estimates the average on-disk bytes/row by sampling pg_column_size (TOAST-aware, no fetch), so a
-- batch of wide INCOMPRESSIBLE strays is still capped tightly.
create extension if not exists pgtap;

select plan(2);

create table public.blk_t (
  created_at timestamptz not null,
  id         bigint generated by default as identity,
  doc        text not null,
  primary key (created_at, id)
);
-- STORAGE EXTERNAL = out-of-line, uncompressed, so each row really is ~12 KB on disk.
alter table public.blk_t alter column doc set storage external;
insert into public.blk_t (created_at, doc)
  select now() - (g || ' minutes')::interval, repeat('x', 12000) from generate_series(1, 3) g;   -- recent -> monolith
select pgpm.transmute('public.blk_t', 'created_at', interval '1 month', p_drain_batch => 5000, p_paused => false);
-- 40 wide strays in one CLOSED month land in the freshly created DEFAULT; do NOT analyze it
insert into public.blk_t (created_at, doc)
  select date_trunc('month', now()) - interval '40 days', repeat('x', 12000) from generate_series(1, 40) g;
update pgpm.config set drain_max_blocks = 1 where parent_table = 'public.blk_t'::regclass;

-- setup: the un-analyzed default has no usable row stats (so the old code would have skipped the budget)
select cmp_ok(
  (select c.reltuples
     from pg_class c
     join pgpm.config cfg on cfg.parent_table = 'public.blk_t'::regclass
    where c.oid = ('public.' || cfg.default_table)::regclass),
  '<=', 0::real,
  'setup: the default has no row stats yet (reltuples <= 0)');

-- one drain step: a 1-block budget over ~12 KB rows caps the microbatch to ~1 row, even before ANALYZE
select pgpm.drain_step('public.blk_t');
select cmp_ok(
  (select rows from pgpm.log
     where parent_table = 'public.blk_t'::regclass and action = 'drain_move'
     order by id desc limit 1),
  '<=', 3::bigint,
  'a 1-block budget caps the microbatch to a few wide rows even before ANALYZE');

select * from finish();
