-- Regression test for issue #95. transmute(..., p_incoming_fks => 'preserve') drops the incoming FK
-- for the drain and re-adds it after. An orphan written into the referencing table while the FK is
-- suspended no longer permanently BRICKS restoration: restore re-adds the FK as NOT VALID (which
-- already enforces every NEW write) and a failed VALIDATE leaves it that way -- surfaced via
-- status().fks_unvalidated and incoming_fk_orphans() -- instead of rolling the re-add back into a
-- silent, forever-deferred drop. validate_incoming_fks() finishes once the operator clears the orphans.
create extension if not exists pgtap;

begin;
select plan(10);

create table public.fk_m (id bigint generated by default as identity primary key, body text);
insert into public.fk_m (body) select 'x' from generate_series(1, 200);

create table public.fk_ref (
  rid  bigint generated by default as identity primary key,
  m_id bigint references public.fk_m(id)
);
insert into public.fk_ref (m_id) select 1 + floor(random() * 200)::int from generate_series(1, 50);

select pgpm.transmute('public.fk_m', 'id', 100000000,
                  p_drain_batch => 50, p_incoming_fks => 'preserve', p_paused => false);

-- the incoming FK is dropped for the conversion; status() surfaces RI as suspended (the P1 off-window)
select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.fk_ref'::regclass and contype = 'f'),
  0, 'preserve dropped the incoming FK for the conversion');
select is(
  (select fks_suspended from pgpm.status() where parent = 'public.fk_m'::regclass),
  1::bigint, 'status() surfaces the incoming FK as suspended (RI off during the drain)');

-- an orphan reference can be written while the FK is suspended (the inherent RI-off window)
select lives_ok(
  $$ insert into public.fk_ref (m_id) values (999999999) $$,
  'an orphan reference is accepted while the preserved FK is suspended (RI off)');

-- drain to completion, then restore: re-adds NOT VALID, does NOT brick on the pre-existing orphan
select pgpm.drain_all('public.fk_m', p_include_open => true);
select cmp_ok(
  (select pgpm.restore_incoming_fks('public.fk_m')), '>=', 1,
  'restore re-adds the FK (does not brick on the pre-existing orphan)');

-- the FK is back on fk_ref but NOT VALID (validation blocked by the orphan). Check the managed
-- constraint by name: an FK to a partitioned parent also spawns internal per-partition child rows.
select is(
  (select c.convalidated from pg_constraint c
     join pgpm.dropped_fk d on d.referencing_table = c.conrelid and d.constraint_name = c.conname
    where d.parent_table = 'public.fk_m'::regclass and c.contype = 'f'),
  false, 'the re-added FK is NOT VALID (validation blocked by the orphan)');

-- ...yet it ENFORCES new writes: a fresh dangling reference is rejected
select throws_ok(
  $$ insert into public.fk_ref (m_id) values (888888888) $$,
  '23503', NULL, 'the re-added NOT VALID FK still rejects a NEW dangling reference');

-- the blocked state is surfaced, with the orphan count
select is(
  (select fks_unvalidated from pgpm.status() where parent = 'public.fk_m'::regclass),
  1::bigint, 'status() surfaces the FK as re-added-but-unvalidated');
select is(
  (select orphan_rows from pgpm.incoming_fk_orphans('public.fk_m') limit 1),
  1::bigint, 'incoming_fk_orphans reports the blocking orphan row');

-- clear the orphan, then validation finishes
delete from public.fk_ref where m_id = 999999999;
select is(
  (select pgpm.validate_incoming_fks('public.fk_m')), 1,
  'validate_incoming_fks validates the FK once the orphan is cleared');
select is(
  (select fks_unvalidated from pgpm.status() where parent = 'public.fk_m'::regclass),
  0::bigint, 'status() shows no unvalidated FK after validation');

select * from finish();
rollback;
