-- Intended behavior (issue #97, closed as working-as-intended). Retention is a STANDING FLOOR on the
-- control column, not just an aging process: a row inserted with a control value already past the
-- retention horizon (a backdated or late-arriving event) is subject to retention immediately and is
-- reclaimed by the drain -- exactly as any retention system (a DELETE cron, pg_partman) drops such a
-- row. The INSERT still succeeds; a later maintenance transaction removes it per policy. This pins that
-- semantics so a future change cannot silently start *keeping* below-horizon data. (To keep
-- late-arriving data, retain on an ingestion timestamp or widen the window -- see docs/guide.md#retain.)
create extension if not exists pgtap;

begin;
select plan(2);

create table public.bd_t (
  created_at timestamptz not null,
  id         bigint generated by default as identity,
  body       text,
  primary key (created_at, id)
);
-- only recent data, all within the retention window
insert into public.bd_t (created_at, body)
  select now() - (g || ' days')::interval, 'recent' from generate_series(1, 10) g;

select pgpm.transmute('public.bd_t', 'created_at', interval '1 month',
                  p_retain => interval '2 months', p_paused => false);
select pgpm.obtain('public.bd_t');

-- a backdated insert well below the retention horizon: the INSERT itself succeeds
insert into public.bd_t (created_at, body)
  values (date_trunc('month', now()) - interval '6 months' + interval '5 days', 'backdated');
select is(
  (select count(*)::int from public.bd_t where body = 'backdated'),
  1, 'the backdated INSERT itself succeeds (the row is present immediately after)');

-- a maintenance cycle: the retention-aware drain reclaims the below-horizon row, by policy. snapshot()
-- gives the complete read (ruling out the drain visibility gap as the cause).
select pgpm.drain_all('public.bd_t', p_include_open => true);
select pgpm.retain('public.bd_t');
select is(
  (select count(*)::int from pgpm.snapshot(null::public.bd_t) where body = 'backdated'),
  0, 'a backdated row below the retention horizon is reclaimed by retention (a standing floor), as intended');

select * from finish();
rollback;
