-- status() surfaces the regraining backlog (REDESIGN.md section 14): coarse_partitions counts the
-- un-regrained coarse children (the monolith, and any coarser children from a partial regraining) and
-- history_unregrained flags that pruning and fine retention are suspended over that span. After regrain()
-- splits the monolith into fine children, both go to zero/false.
create extension if not exists pgtap;
select plan(4);

create table public.st (id bigint generated by default as identity primary key, payload text);
insert into public.st (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.st', 'id', 10000);   -- monolith [0, 60000) -- coarse, 6 steps
call pgpm.obtain('public.st');

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.st'::regclass),
  1::bigint, 'status() reports the coarse monolith as one coarse partition (the regraining backlog)');

select ok(
  (select history_unregrained from pgpm.status() where parent = 'public.st'::regclass),
  'status() flags history as unregrained while the monolith is coarse');

-- freeze the monolith and regrain it
insert into public.st (id, payload) values (65000, 'frontier');
select pgpm.regrain_history('public.st');

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.st'::regclass),
  0::bigint, 'after regrain, no coarse partitions remain');

select ok(
  not (select history_unregrained from pgpm.status() where parent = 'public.st'::regclass),
  'after regrain, history_unregrained is false (the backlog is cleared)');

select * from finish();
