-- refine() moves each sub-range in budget-sized microbatches (drain_batch, capped by drain_max_blocks),
-- not one statement per sub-range, so a wide sub-range can't become one giant copy. The whole call is one
-- transaction here (atomic, gap-free); the microbatching bounds per-statement footprint and reuses the
-- drain's budget so a maintain-driven auto-refine can pace it across ticks.
create extension if not exists pgtap;
begin;
select plan(4);

create table public.fw (id bigint generated by default as identity primary key, payload text);
insert into public.fw (payload) select 'x' from generate_series(1, 120);   -- ids 1..120
select pgpm.transmute('public.fw', 'id', 50, p_drain_batch => 10);   -- monolith [0, 150) -- 3 steps; batch 10
select pgpm.obtain('public.fw');
insert into public.fw (id, payload) values (5000, 'frontier');   -- advance frontier -> monolith frozen

select is(
  (select pgpm.refine_history('public.fw'))::int,
  3, 'refine splits the monolith into 3 fine children');

select cmp_ok(
  (select max(rows) from pgpm.log where parent_table = 'public.fw'::regclass and action = 'refine_move'),
  '<=', 10::bigint, 'every refine microbatch is bounded by drain_batch (10 rows)');

select cmp_ok(
  (select count(*) from pgpm.log where parent_table = 'public.fw'::regclass and action = 'refine_move'),
  '>=', 12::bigint, 'the copy is microbatched (many bounded moves, not one statement per sub-range)');

select is(
  (select count(*)::int from public.fw where id < 150),
  120, 'all 120 rows conserved across the feathered refine');

select * from finish();
rollback;
