-- Auto-refine must apply the same incoming-FK leash the drain does. A cross-tick refine moves historical
-- referenced rows out of the monolith through unattached children, so a live preserve-managed FK has to
-- be suspended first (else a new referencing write to a mid-move key would be spuriously rejected), and
-- restored once the refine completes. Regression test for the auto-refine/preserve-FK gap.
create extension if not exists pgtap;
begin;
select plan(6);

create table public.arf (id bigint generated by default as identity primary key, payload text);
insert into public.arf (payload) select 'x' from generate_series(1, 500);   -- ids 1..500
create table public.arf_ref (rid bigint generated by default as identity primary key,
                             m_id bigint references public.arf(id));
insert into public.arf_ref (m_id) select 1 + floor(random() * 500)::int from generate_series(1, 50);

select pgpm.transmute('public.arf', 'id', 100, p_paused => false, p_incoming_fks => 'preserve');  -- monolith [0,600); FK dropped + recorded
select pgpm.restore_incoming_fks('public.arf');   -- monolith holds every referenced row attached -> FK restored (live)

select is(
  (select count(*)::int from pg_constraint
     where conrelid = 'public.arf_ref'::regclass and contype = 'f' and confrelid = 'public.arf'::regclass),
  1, 'precondition: the preserve FK is live before auto-refine');

insert into public.arf (id, payload) values (10000, 'frontier');   -- advance frontier past B=600 -> monolith frozen
select pgpm.set_refine('public.arf', '100');                       -- enable auto-refine

-- one maintain tick: it must suspend the live FK before moving referenced rows out of the monolith
select pgpm.maintain('public.arf');
select is(
  (select count(*)::int from pg_constraint where conrelid = 'public.arf_ref'::regclass and contype = 'f'),
  0, 'auto-refine suspends the live preserve FK before moving referenced rows');
select cmp_ok(
  (select fks_suspended from pgpm.status() where parent = 'public.arf'::regclass),
  '>', 0::bigint, 'status() surfaces the suspended FK during the cross-tick refine');

-- drive the refine to completion across ticks
do $$ begin for i in 1..40 loop perform pgpm.maintain('public.arf'); end loop; end $$;

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.arf'::regclass),
  0::bigint, 'the refine completes across ticks (no coarse partitions remain)');
select is(
  (select count(*)::int from pg_constraint
     where conrelid = 'public.arf_ref'::regclass and contype = 'f' and confrelid = 'public.arf'::regclass),
  1, 'the preserve FK is restored once the refine completes');
select throws_ok(
  $$ insert into public.arf_ref (m_id) values (88888888) $$,
  '23503', NULL, 'the restored FK is enforced (a dangling reference is rejected)');

select * from finish();
rollback;
