-- The copy contract (REDESIGN.md sections 9 and 10): refine COPIES, it never moves. While a feathered
-- (cross-tick) refine is mid-flight, the source monolith still holds every row and stays attached, so:
--   (1) a plain read of the parent is NEVER short (no undercount),
--   (2) the source is never deleted from (no dead tuples, no bloat),
--   (3) snapshot() does not union the in-flight copies (they would double-count rows still in the source).
-- These three assertions encode exactly what the move-model implementation got wrong. refine never logs a
-- 'refine_move' (the delete-and-move action); it logs 'refine_copy'.
create extension if not exists pgtap;
begin;
select plan(8);

create table public.cc (id bigint generated by default as identity primary key, payload text);
insert into public.cc (payload) select 'x' from generate_series(1, 300);   -- history ids 1..300
select pgpm.transmute('public.cc', 'id', 50, p_drain_batch => 20, p_paused => false);  -- monolith [0,B); batch 20
select pgpm.obtain('public.cc');
insert into public.cc (id, payload) values (10000, 'frontier');   -- advance frontier past B -> monolith frozen
select pgpm.set_refine('public.cc', '50');                        -- enable feathered auto-refine to step 50

-- one maintain tick: a partial COPY (one budget microbatch), the refine is NOT finished and copies are in flight
select pgpm.maintain('public.cc');

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.cc'::regclass),
  1::bigint, 'mid-refine: the coarse monolith is still present (one tick does not finish the refine)');

select cmp_ok(
  (select count(*) from pgpm.log where parent_table = 'public.cc'::regclass and action = 'refine_copy'),
  '>', 0::bigint, 'mid-refine: at least one copy microbatch has run (action refine_copy)');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.cc'::regclass and action = 'refine_move'),
  0, 'refine never logs a move: it copies, it does not delete-and-move');

-- (1) NO UNDERCOUNT: every history row is still visible through the parent mid-refine
select is(
  (select count(*)::int from public.cc where id <= 300),
  300, 'mid-refine: a plain read of the parent returns all 300 history rows (no undercount)');

-- (2) NO DELETES: the source monolith table still holds all 300 history rows mid-refine
create temporary table _moncnt (n int);
do $$
declare v_rel text; v_n int;
begin
  select quote_ident(n.nspname) || '.' || quote_ident(p.child_name) into v_rel
    from pgpm.part p
    join pg_class c on c.oid = p.parent_table
    join pg_namespace n on n.oid = c.relnamespace
   where p.parent_table = 'public.cc'::regclass and p.attached
     and pgpm._native_gt('id', p.hi, pgpm._grid_next('id', '50', p.lo));   -- the coarse monolith
  execute 'select count(*) from ' || v_rel into v_n;
  insert into _moncnt values (v_n);
end $$;
select is((select n from _moncnt), 300, 'mid-refine: the monolith source still holds all 300 rows (never deleted from)');

-- (3) NO DOUBLE-COUNT: snapshot() does not union the in-flight copies (their rows are still in the source)
select is(
  (select count(*)::int from pgpm.snapshot(null::public.cc) where id <= 300),
  300, 'mid-refine: snapshot() returns 300 history rows, not 300 + the in-flight copies');

-- drive the refine to completion across ticks
do $$ begin for i in 1..60 loop perform pgpm.maintain('public.cc'); end loop; end $$;

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.cc'::regclass),
  0::bigint, 'the refine completes across ticks (no coarse partition remains)');

select is(
  (select count(*)::int from public.cc where id <= 300),
  300, 'all 300 history rows conserved across the feathered copy-refine');

select * from finish();
rollback;
