-- Exact identity-sequence preservation through transmute and untransmute. The reseed advances the identity
-- sequence past max(id), which is correct when the sequence sits at its max. But a sequence can be AHEAD of
-- max(id) -- from rolled-back inserts, sequence caching, or deleted high rows -- and seeding only to max(id)+1
-- would re-issue ids the sequence had already handed out. transmute (and untransmute, so a round trip does
-- not reopen the gap) now seed to the greater of max(id)+1 and the source sequence's own next value.
create extension if not exists pgtap;

begin;
select plan(3);

-- (A) transmute preserves a sequence sitting AHEAD of max(id)
create table public.seqp (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.seqp (created_at, body)
  select now() - (g || ' minutes')::interval, 'b' || g from generate_series(1, 100) g;
select setval(pg_get_serial_sequence('public.seqp', 'id'), 200);   -- is_called => next source value is 201
select pgpm.transmute('public.seqp', 'created_at', interval '1 month');
insert into public.seqp (created_at, body) values (now(), 'new');
select is(
  (select id from public.seqp where body = 'new'),
  201::bigint, 'transmute preserves the sequence position: the next id is 201, not max(id)+1 (101)');

-- (B) a transmute + untransmute round trip does not reopen the gap (untransmute preserves it too)
create table public.seqp2 (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.seqp2 (created_at, body)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 100) g;
select setval(pg_get_serial_sequence('public.seqp2', 'id'), 300);   -- next is 301
select pgpm.transmute('public.seqp2', 'created_at', interval '1 month');
select pgpm.untransmute('public.seqp2');
insert into public.seqp2 (created_at, body) values (now(), 'new');
select is(
  (select id from public.seqp2 where body = 'new'),
  301::bigint, 'untransmute preserves the sequence position across the reversal (next id is 301, not 101)');

-- (C) the common case is unchanged: a sequence sitting at its max still reseeds to max(id)+1
create table public.seqp3 (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  body       text,
  primary key (created_at, id)
);
insert into public.seqp3 (created_at, body)
  select now() - (g || ' minutes')::interval, 'y' from generate_series(1, 50) g;
select pgpm.transmute('public.seqp3', 'created_at', interval '1 month');
insert into public.seqp3 (created_at, body) values (now(), 'new');
select is(
  (select id from public.seqp3 where body = 'new'),
  51::bigint, 'a sequence at its max is unchanged: the next id is max(id)+1 (51)');

select * from finish();
rollback;
