-- Freshly minted + populated child partitions must carry real planner statistics before anything relies
-- on them. The drain and refine both CREATE TABLE LIKE a child and bulk-INSERT into it; until something
-- ANALYZEs it, pg_class.reltuples stays -1/0 (autovacuum has not run, and inside the test transaction it
-- never will), so any plan that touches the child misplans -- the same planner-blindness that made the
-- from_hypertable cutover reconcile an O(rows) seqscan (#164/#166). The drain ANALYZEs the child before it
-- attaches; refine ANALYZEs each fine child when its copy completes, both off any exclusive-lock window.
-- reltuples is the direct signal: ANALYZE sets it in place (visible immediately, even same-transaction),
-- so a child with reltuples > 0 was analyzed and one left at -1/0 was not.
create extension if not exists pgtap;
begin;
select plan(2);

-- ----- drain: the assistant evacuates a backdated stray into a freshly minted closed-interval child -----
create table public.an (
  id bigint generated by default as identity,
  created_at timestamptz not null,
  body text, primary key (created_at, id)
);
insert into public.an (created_at) select now() - (g || ' minutes')::interval from generate_series(1, 20) g;
select pgpm.transmute('public.an', 'created_at', interval '1 month', p_paused => false);
-- a backdated stray (3 months back) lands in the empty DEFAULT, in a closed interval below the monolith
insert into public.an (created_at, body)
  select date_trunc('month', now()) - interval '3 months' + interval '10 days', 'stray' from generate_series(1, 50) g;
select pgpm.drain_all('public.an', p_include_open => true);

select cmp_ok(
  (select c.reltuples::int from pg_class c
     where c.oid = ('public.an_p' || to_char(date_trunc('month', now()) - interval '3 months', 'YYYY_MM'))::regclass),
  '>', 0,
  'the drained child carries real planner stats (the drain ANALYZEd it before attach)');

-- ----- refine: split a frozen monolith into fine children by COPY-then-swap -----
create table public.rfa (id bigint generated by default as identity primary key, payload text);
insert into public.rfa (payload) select 'x' from generate_series(1, 50000);
select pgpm.transmute('public.rfa', 'id', 10000);   -- monolith [0, 60000)
select pgpm.obtain('public.rfa');
insert into public.rfa (id, payload) values (65000, 'frontier');   -- freeze the monolith
select pgpm.refine_history('public.rfa');

select cmp_ok(
  (select c.reltuples::int from pg_class c
     where c.oid = ('public.rfa_p' || lpad('0', 19, '0'))::regclass),
  '>', 0,
  'a refined fine child carries real planner stats (refine ANALYZEd it before the swap)');

select * from finish();
rollback;
