-- Freshly minted + populated child partitions must carry real planner statistics before anything relies
-- on them. The drain and regrain both CREATE TABLE LIKE a child and bulk-INSERT into it; until something
-- ANALYZEs it, pg_class.reltuples stays -1/0 (autovacuum has not run, and inside the test transaction it
-- never will), so any plan that touches the child misplans -- the same planner-blindness that made the
-- from_hypertable cutover reconcile an O(rows) seqscan (#164/#166). The drain ANALYZEs the child before it
-- attaches; regrain ANALYZEs each fine child when its copy completes, both off any exclusive-lock window.
-- reltuples is the direct signal: ANALYZE sets it in place (visible immediately, even same-transaction),
-- so a child with reltuples > 0 was analyzed and one left at -1/0 was not.
create extension if not exists pgtap;
select plan(1);

-- The drain half of this test is gone with the drain (#288). It asserted that a backdated stray, caught by
-- the DEFAULT and evacuated into a freshly minted child, carried planner stats before the attach. With no
-- DEFAULT there is no stray to catch and no child minted to hold one. regrain's half below is unaffected,
-- and is the surviving path that mints and populates a child.

-- ----- regrain: split a frozen monolith into fine children by COPY-then-swap -----
create table public.rfa (id bigint generated by default as identity primary key, payload text);
insert into public.rfa (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.rfa', 'id', 10000);   -- monolith [0, 60000)
select pgpm.obtain('public.rfa');
insert into public.rfa (id, payload) values (60000, 'frontier');   -- freeze the monolith
select pgpm.regrain_history('public.rfa');

select cmp_ok(
  (select c.reltuples::int from pg_class c
     where c.oid = ('public.rfa_p' || lpad('0', 19, '0'))::regclass),
  '>', 0,
  'a regrained fine child carries real planner stats (regrain ANALYZEd it before the swap)');

select * from finish();
