-- pgpm.hook: a lifecycle hook registry, first consumer is retain()'s 'pre_drop' event. The use case
-- this is built for is copying a partition's contents to long-term storage (e.g. S3) before it is
-- dropped -- an operator running that workload needs a hard guarantee that a failed copy never lets the
-- drop happen anyway. Each partition's hooks + drop are isolated in their own subtransaction inside
-- retain()'s loop (pgpm_core/install.sql), so:
--   * a hook always runs, and completes, before its partition's DROP TABLE;
--   * a raising hook blocks ONLY that partition's drop (logged retain_hook_fail, retried on the next
--     retain() call), without undoing drops already committed earlier in the SAME retain() call, and
--     without re-invoking hooks for those other, already-succeeded partitions (not assumed idempotent);
--   * multiple hooks on the same event run in registration order;
--   * a disabled hook never runs; a bad event name or a hook_fn with the wrong signature is refused at
--     pgpm.hook_register time, not discovered later when retain() tries to call it.
create extension if not exists pgtap;

begin;
select plan(15);

create schema pgpm_test;

-- records every pre_drop invocation, and whether the child partition still existed at call time (proof
-- the hook ran BEFORE the drop, not after).
create table pgpm_test.hook_calls (
  id            bigint generated always as identity primary key,
  hook_name     text     not null,
  child         name     not null,
  lo            text     not null,
  child_existed boolean  not null
);

-- hook_a: the "copy to long-term storage" stand-in. Raises for lo = 70000 to simulate that copy failing
-- (e.g. an S3 outage) for exactly one partition.
create function pgpm_test.hook_a(p_parent regclass, p_child name, p_lo text, p_hi text)
returns void language plpgsql as $$
declare v_nsp name; v_existed boolean;
begin
  select n.nspname into v_nsp from pg_class c join pg_namespace n on n.oid = c.relnamespace where c.oid = p_parent;
  v_existed := to_regclass(format('%I.%I', v_nsp, p_child)) is not null;
  insert into pgpm_test.hook_calls (hook_name, child, lo, child_existed) values ('hook_a', p_child, p_lo, v_existed);
  if p_lo = '70000' then
    raise exception 'simulated long-term-storage copy failure for %', p_child;
  end if;
end;
$$;

-- hook_b: a second hook on the same event, used only to prove registration-order execution against hook_a.
create function pgpm_test.hook_b(p_parent regclass, p_child name, p_lo text, p_hi text)
returns void language plpgsql as $$
begin
  insert into pgpm_test.hook_calls (hook_name, child, lo, child_existed) values ('hook_b', p_child, p_lo, true);
end;
$$;

-- hook_never: registered disabled; if it ever ran, this would fail the run (both via the insert becoming
-- visible below, and via its own unconditional raise).
create function pgpm_test.hook_never(p_parent regclass, p_child name, p_lo text, p_hi text)
returns void language plpgsql as $$
begin
  insert into pgpm_test.hook_calls (hook_name, child, lo, child_existed) values ('hook_never', p_child, p_lo, true);
  raise exception 'hook_never should never run (registered disabled)';
end;
$$;

create table public.hk8 (id bigint generated by default as identity primary key, payload text);
insert into public.hk8 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
select pgpm.transmute('public.hk8', 'id', 10000, p_retain => 30000);   -- monolith [0, 60000)
select pgpm.obtain('public.hk8');   -- attaches [60000,70000) [70000,80000) [80000,90000) [90000,100000), all empty

insert into public.hk8 (id, payload) select g, 'y' from generate_series(60001, 60005) g;  -- into [60000,70000)
insert into public.hk8 (id, payload) select g, 'z' from generate_series(70001, 70005) g;  -- into [70000,80000)
insert into public.hk8 (id, payload) values (110000, 'frontier');   -- advances the frontier to 110000

select throws_ok(
  $$ select pgpm.hook_register('public.hk8', 'post_attach', 'pgpm_test.hook_a(regclass,name,text,text)') $$,
  '23514', null, 'a hook event outside the known set is refused (check constraint), not silently accepted');

select throws_ok(
  $$ select pgpm.hook_register('public.hk8', 'pre_drop', 'pgpm_test.hook_a(regclass,name,text)') $$,
  '42883', null, 'a hook_fn reference with the wrong signature is refused at registration, not at drop time');

select lives_ok(
  $$ select pgpm.hook_register('public.hk8', 'pre_drop', 'pgpm_test.hook_a(regclass,name,text,text)') $$,
  'hook_a registers on pre_drop');
select lives_ok(
  $$ select pgpm.hook_register('public.hk8', 'pre_drop', 'pgpm_test.hook_b(regclass,name,text,text)') $$,
  'hook_b registers on pre_drop, after hook_a');
select lives_ok(
  $$ select pgpm.hook_register('public.hk8', 'pre_drop', 'pgpm_test.hook_never(regclass,name,text,text)', p_enabled => false) $$,
  'hook_never registers disabled');

-- boundary = grid_floor(110000 - 30000, step 10000) = 80000: eligible = monolith [0,60000), [60000,70000),
-- [70000,80000) (its hook_a call raises); [80000,90000) and [90000,100000) stay above the boundary.
select is(pgpm.retain('public.hk8'), 2,
  'retain() drops the 2 partitions whose hook succeeded; the one whose hook raised is skipped');

select ok(
  (select count(*)::int from pgpm.part where parent_table = 'public.hk8'::regclass and lo = '70000') = 1
    and to_regclass('public.' || (select child_name from pgpm.part
                                    where parent_table = 'public.hk8'::regclass and lo = '70000')) is not null,
  'the partition whose hook raised was NOT dropped -- still tracked and still a real table');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.hk8'::regclass and action = 'retain_drop'),
  2, 'the 2 successful drops were NOT rolled back by the 3rd partition''s hook failure (per-partition isolation)');

select ok(
  (select method from pgpm.log
     where parent_table = 'public.hk8'::regclass and action = 'retain_hook_fail' and lo = '70000')
    like 'simulated long-term-storage copy failure for hk8\_p%',
  'the failure is logged with the hook''s own error message');

select is(
  (select count(*)::int from pgpm_test.hook_calls where not child_existed),
  0, 'every hook_a invocation saw its child partition still present -- the hook always runs before the drop');

select ok(
  (select id from pgpm_test.hook_calls where hook_name = 'hook_a' and lo = '60000')
    < (select id from pgpm_test.hook_calls where hook_name = 'hook_b' and lo = '60000'),
  'hook_a and hook_b run in registration order for the same partition');

select is(
  (select count(*)::int from pgpm_test.hook_calls where hook_name = 'hook_never'),
  0, 'a disabled hook is never invoked');

select is(
  (select retain_hook_failures::int from pgpm.status() where parent = 'public.hk8'::regclass),
  1, 'status() surfaces the one outstanding pre_drop hook failure');

-- the outage is over: hook_a no longer raises for lo = 70000.
create or replace function pgpm_test.hook_a(p_parent regclass, p_child name, p_lo text, p_hi text)
returns void language plpgsql as $$
begin
  insert into pgpm_test.hook_calls (hook_name, child, lo, child_existed) values ('hook_a', p_child, p_lo, true);
end;
$$;

select is(pgpm.retain('public.hk8'), 1, 'once the hook stops failing, the deferred partition drops on the next retain() call');

select is(
  (select retain_hook_failures::int from pgpm.status() where parent = 'public.hk8'::regclass),
  0, 'status() backlog clears once the retry succeeds');

select * from finish();
rollback;
