-- pgpm.hook: as of issue #238, pgpm.retire() no longer consults this registry at all. It is kept,
-- unchanged, ONLY because pgpm_archive's existing gate-only architecture still registers
-- archive.file_gate through it -- removing hook_register/hook_unregister now would break that
-- before #239/#240 migrate pgpm_archive onto the archive_fn contract (see
-- docs/retention-write-block-and-merge.md, #242). hook_register/hook_unregister's OWN validation
-- (event check constraint, signature check) is unchanged; what changed is that retire()/retain()
-- never invoke a registered hook anymore, for any reason -- including one that always raises. This
-- used to be tests/58's "hooks gate a drop" scenario; it now proves the opposite, intentional
-- contract: a registered pre_drop hook is completely inert.
create extension if not exists pgtap;

begin;
select plan(9);

create schema pgpm_test;

-- if this ever ran, it would both record its own invocation AND unconditionally block every drop --
-- the exact old pre_drop contract, kept as a canary that nothing invokes it anymore.
create table pgpm_test.hook_calls (
  id        bigint generated always as identity primary key,
  hook_name text not null,
  child     name not null
);
create function pgpm_test.hook_always_fails(p_parent regclass, p_child name, p_lo text, p_hi text)
returns void language plpgsql as $$
begin
  insert into pgpm_test.hook_calls (hook_name, child) values ('hook_always_fails', p_child);
  raise exception 'this hook must never run -- retire() stopped consulting pgpm.hook as of #238';
end;
$$;

create table public.hk8 (id bigint generated by default as identity primary key, payload text);
insert into public.hk8 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
select pgpm.transmute('public.hk8', 'id', 10000, p_retain => 30000);   -- monolith [0, 60000)
select pgpm.obtain('public.hk8');   -- attaches [60000,70000) [70000,80000) [80000,90000) [90000,100000), all empty

insert into public.hk8 (id, payload) select g, 'y' from generate_series(60001, 60005) g;  -- into [60000,70000)
insert into public.hk8 (id, payload) select g, 'z' from generate_series(70001, 70005) g;  -- into [70000,80000)
insert into public.hk8 (id, payload) values (110000, 'frontier');   -- advances the frontier to 110000

-- hook_register/hook_unregister's own validation is entirely unchanged.
select throws_ok(
  $$ select pgpm.hook_register('public.hk8', 'post_attach', 'pgpm_test.hook_always_fails(regclass,name,text,text)') $$,
  '23514', null, 'a hook event outside the known set is still refused (check constraint), not silently accepted');

select throws_ok(
  $$ select pgpm.hook_register('public.hk8', 'pre_drop', 'pgpm_test.hook_always_fails(regclass,name,text)') $$,
  '42883', null, 'a hook_fn reference with the wrong signature is still refused at registration, not at drop time');

select lives_ok(
  $$ select pgpm.hook_register('public.hk8', 'pre_drop', 'pgpm_test.hook_always_fails(regclass,name,text,text)') $$,
  'a correctly-signed hook still registers fine -- hook_register itself is unchanged');

select ok(
  exists (select 1 from pgpm.hook
           where parent_table = 'public.hk8'::regclass and event = 'pre_drop' and enabled),
  'the registration is really there, enabled, in pgpm.hook');

-- boundary = grid_floor(110000 - 30000, step 10000) = 80000: eligible = monolith [0,60000),
-- [60000,70000), [70000,80000). Before #238, hook_always_fails would have blocked every one of
-- these drops (it unconditionally raises); now it is never even called.
select is(pgpm.retain('public.hk8'), 3,
  'retain() drops all 3 eligible partitions -- the registered pre_drop hook, though it always raises, no longer blocks anything');

select is(
  (select count(*)::int from pgpm_test.hook_calls),
  0, 'the hook was never invoked at all');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.hk8'::regclass and action = 'retain_drop'),
  3, 'all 3 drops are logged normally, as if no hook were registered at all');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.hk8'::regclass and action = 'retain_hook_fail'),
  0, 'retain_hook_fail is never logged -- retire() no longer has a code path that produces it');

select is(
  (select retain_drop_failures::int from pgpm.status() where parent = 'public.hk8'::regclass),
  0, 'status() shows no drop failures -- nothing failed, the hook just never ran');

select * from finish();
rollback;
