-- retain_batch (issue #189): cap how many eligible partitions ONE retain() call will attempt, so a
-- backlog of aged-out partitions paces across maintenance ticks (each tick is its own transaction via
-- pg_cron) instead of one call carrying the whole backlog -- the same shape the drain already solves
-- with drain_batch. The motivating case is a slow synchronous pre_drop hook (e.g. copying the partition
-- to long-term storage): retain_batch = 1 bounds each tick to one partition's hooks + drop. Semantics:
--   * null (the default) = unbounded = prior behavior, so existing installs and tests are unchanged;
--   * the cap bounds ATTEMPTS, not successes, oldest first (order by lo): with a failing pre_drop hook
--     at the head of the backlog, the partitions behind it are NOT attempted that call (bounded work
--     per tick is the whole point; the wedge is surfaced by status().retain_hook_failures);
--   * status() gains retain_backlog: eligible-but-undropped partitions. Non-zero is normal while a
--     paced backlog drains tick over tick; flat with retain_hook_failures climbing = wedged.
create extension if not exists pgtap;

begin;
select plan(15);

create schema pgpm_test;

-- fails unconditionally: the "long-term-storage copy is down" stand-in.
create function pgpm_test.hook_fail(p_parent regclass, p_child name, p_lo text, p_hi text)
returns void language plpgsql as $$
begin
  raise exception 'simulated long-term-storage copy failure for %', p_child;
end;
$$;

create table public.rb9 (id bigint generated by default as identity primary key, payload text);
insert into public.rb9 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
select pgpm.transmute('public.rb9', 'id', 10000, p_retain => 30000);   -- monolith [0, 60000)
select pgpm.obtain('public.rb9');   -- attaches [60000,70000) [70000,80000) [80000,90000) [90000,100000), all empty
insert into public.rb9 (id, payload) values (110000, 'frontier');   -- frontier 110000 -> boundary 80000

-- eligible now (hi <= 80000): the monolith [0,60000), [60000,70000), [70000,80000)

select ok(
  (select retain_batch is null from pgpm.config where parent_table = 'public.rb9'::regclass),
  'retain_batch defaults to null (unbounded, the prior behavior)');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  3, 'status().retain_backlog counts the eligible-but-undropped partitions before any retain() call');

update pgpm.config set retain_batch = 1 where parent_table = 'public.rb9'::regclass;

select is(pgpm.retain('public.rb9'), 1,
  'retain_batch = 1: one call drops exactly one partition, leaving the rest for later ticks');

select ok(
  not exists (select 1 from pgpm.part where parent_table = 'public.rb9'::regclass and lo = '0')
  and exists (select 1 from pgpm.part where parent_table = 'public.rb9'::regclass and lo = '60000'),
  'the oldest eligible partition (the monolith) is the one dropped: the cap takes them in lo order');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  2, 'the backlog falls by one per paced call');

update pgpm.config set retain_batch = null where parent_table = 'public.rb9'::regclass;

select is(pgpm.retain('public.rb9'), 2,
  'retain_batch back to null: the whole remaining backlog drops in one call (unbounded, prior behavior)');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  0, 'the backlog reads zero once retention has caught up');

-- advance the frontier so two more partitions age out: boundary = grid_floor(140000 - 30000) = 110000,
-- so [80000,90000) and [90000,100000) become eligible.
insert into public.rb9 (id, payload) values (140000, 'frontier2');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  2, 'the backlog reappears as the frontier advances past more partitions');

select pgpm.hook_register('public.rb9', 'pre_drop', 'pgpm_test.hook_fail(regclass,name,text,text)');
update pgpm.config set retain_batch = 1 where parent_table = 'public.rb9'::regclass;

select is(pgpm.retain('public.rb9'), 0,
  'a failing pre_drop hook at the head of the backlog: the paced call drops nothing');

select is(
  (select count(*)::int from pgpm.log where parent_table = 'public.rb9'::regclass and action = 'retain_hook_fail'),
  1, 'the cap bounds ATTEMPTS: only the head partition was attempted (one hook failure logged); the one behind it was not attempted, so its hooks never ran');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  2, 'nothing dropped, so the backlog holds -- flat backlog plus climbing retain_hook_failures = wedged');

select is(
  (select retain_hook_failures::int from pgpm.status() where parent = 'public.rb9'::regclass),
  1, 'status() surfaces the wedge via retain_hook_failures');

-- the outage is over: the hook stops failing.
create or replace function pgpm_test.hook_fail(p_parent regclass, p_child name, p_lo text, p_hi text)
returns void language plpgsql as $$
begin
  return;
end;
$$;

select is(pgpm.retain('public.rb9'), 1, 'once the hook clears, the paced calls resume: first partition drops');
select is(pgpm.retain('public.rb9'), 1, 'and the next tick takes the next one');

select ok(
  (select retain_backlog = 0 and retain_hook_failures = 0 from pgpm.status() where parent = 'public.rb9'::regclass),
  'backlog and hook failures both read zero once the paced backlog has fully drained');

select * from finish();
rollback;
