-- retain_batch (issue #189): cap how many eligible partitions ONE retain() call will attempt, so a
-- backlog of aged-out partitions paces across maintenance ticks (each tick is its own transaction via
-- pg_cron) instead of one call carrying the whole backlog -- the same shape the drain already solves
-- with drain_batch. Semantics:
--   * null (the default) = unbounded = prior behavior, so existing installs and tests are unchanged;
--   * the cap bounds ATTEMPTS, not successes, oldest first (order by lo);
--   * status() gains retain_backlog: eligible-but-undropped partitions. Non-zero is normal while a
--     paced backlog drains tick over tick, OR while chunked archiving is still catching up on a
--     write-blocked child (issue #238) -- neither is a failure.
--
-- As of #238, a not-yet-archive-covered child at the head of the backlog produces a flat-backlog
-- wedge shape: retain() just returns false and moves on, consuming its batch slot without dropping.
-- The one thing that's genuinely different from a real wedge (a repeatedly failing drop): this is
-- NOT a failure.
-- status().retain_drop_failures stays at zero throughout -- archiving still catching up is an
-- expected, retryable state, not a wedge to alert on.
create extension if not exists pgtap;

select plan(14);

create table public.rb9 (id bigint generated by default as identity primary key, payload text);
insert into public.rb9 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
call pgpm.transmute('public.rb9', 'id', 10000, p_retain => 30000, p_obtain => 8);   -- monolith [0, 60000)
select pgpm.obtain('public.rb9');   -- grid runs [60000,70000) .. [130000,140000), all empty
insert into public.rb9 (id, payload) values (110000, 'frontier');   -- frontier 110000 -> boundary 80000

-- eligible now (hi <= 80000): the monolith [0,60000), [60000,70000), [70000,80000)

select ok(
  (select retain_batch is null from pgpm.config where parent_table = 'public.rb9'::regclass),
  'retain_batch defaults to null (unbounded, the prior behavior)');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  3, 'status().retain_backlog counts the eligible-but-undropped partitions before any retain() call');

update pgpm.config set retain_batch = 1 where parent_table = 'public.rb9'::regclass;

select is(pgpm.retain('public.rb9'), 1,
  'retain_batch = 1: one call drops exactly one partition, leaving the rest for later ticks');

select ok(
  not exists (select 1 from pgpm.part where parent_table = 'public.rb9'::regclass and lo = '0')
  and exists (select 1 from pgpm.part where parent_table = 'public.rb9'::regclass and lo = '60000'),
  'the oldest eligible partition (the monolith) is the one dropped: the cap takes them in lo order');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  2, 'the backlog falls by one per paced call');

update pgpm.config set retain_batch = null where parent_table = 'public.rb9'::regclass;

select is(pgpm.retain('public.rb9'), 2,
  'retain_batch back to null: the whole remaining backlog drops in one call (unbounded, prior behavior)');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  0, 'the backlog reads zero once retention has caught up');

-- advance the frontier so two more partitions age out: boundary = grid_floor(130000 - 30000) = 100000,
-- so [80000,90000) and [90000,100000) become eligible. 130000 rather than 140000 because the frontier can
-- only advance into a partition that exists, and boundary 110000 would make a third one eligible.
insert into public.rb9 (id, payload) values (130000, 'frontier2');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  2, 'the backlog reappears as the frontier advances past more partitions');

-- configure a real archive strategy but do not run it yet -- the head of the backlog is provably
-- not yet archive-covered, a normal and expected (not a failure) reason for retain() to skip it.
update pgpm.config set archive_fn = 'pgpm._archive_noop(regclass,name,text,text)'::regprocedure
  where parent_table = 'public.rb9'::regclass;
update pgpm.config set retain_batch = 1 where parent_table = 'public.rb9'::regclass;

select is(pgpm.retain('public.rb9'), 0,
  'a not-yet-archive-covered partition at the head of the backlog: the paced call drops nothing');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  2, 'nothing dropped, so the backlog holds -- the same flat-backlog shape a wedge would show');

select is(
  (select retain_drop_failures::int from pgpm.status() where parent = 'public.rb9'::regclass),
  0, 'critically, this is NOT a failure: retain_drop_failures stays zero while archiving catches up (contrast a real wedge, which climbs this counter)');

-- the archiving "catches up": write-block both remaining eligible children (mirroring what
-- maintain() does every tick), then run one chunked-archiving pass -- the built-in no-op strategy
-- reports each child's whole range covered immediately.
select pgpm._enforce_write_blocks('public.rb9'::regclass);
select pgpm._archive_step('public.rb9'::regclass);

select is(pgpm.retain('public.rb9'), 1,
  'once archive coverage catches up, the paced call resumes: the head of the backlog drops');
select is(pgpm.retain('public.rb9'), 1, 'and the next paced call takes the next one');

select is(
  (select retain_backlog::int from pgpm.status() where parent = 'public.rb9'::regclass),
  0, 'the backlog is fully drained once archiving and retention are both caught up');

select * from finish();
