-- pgpm.retire (issue #195): the sanctioned single-partition drop -- retain()'s per-partition body
-- made public and claim-guarded, so an external assistant (e.g. an archive-then-drop scanner) or
-- several cooperating ones can drive retirement themselves through the same protocol retain() uses:
-- claim, pre_drop hooks in registration order, DROP, catalog + log. The contract under test:
--   * retire() never widens what retention may drop: it refuses (raises) an unmanaged table, a
--     table with no retention policy, a partition not entirely past the horizon, and an in-flight
--     (unattached) drain/regrain child -- a caller only picks WHICH eligible partition and WHEN;
--   * one owner per partition at a time: the pgpm.part row is claimed FOR UPDATE SKIP LOCKED
--     (issue #188), so a concurrent claimant makes retire() return false immediately -- no wait,
--     no error, no hook invocation, no spurious retain_hook_fail;
--   * an absent pgpm.part row (already retired by another actor) is a cooperative no-op (false);
--   * a raising pre_drop hook returns false, logs retain_hook_fail, and keeps the partition,
--     exactly the contract retain() has always had (tests/58);
--   * retain() is now a loop over retire() and behaves as before (tests/07/34/40/58/59).
--
-- NOTE: this file does NOT use the usual begin/rollback isolation. The concurrency assertions need
-- a second session (dblink) to see and lock the fixture's pgpm.part rows, which requires the
-- fixture to be COMMITTED. The file cleans up everything it created at the end instead.
create extension if not exists pgtap;
create extension if not exists dblink;

select plan(16);

create schema pgpm_test60;

create table pgpm_test60.calls (
  id            bigint generated always as identity primary key,
  hook_name     text    not null,
  child         name    not null,
  child_existed boolean not null
);

create function pgpm_test60.hook_rec(p_parent regclass, p_child name, p_lo text, p_hi text)
returns void language plpgsql as $$
declare v_nsp name; v_existed boolean;
begin
  select n.nspname into v_nsp from pg_class c join pg_namespace n on n.oid = c.relnamespace where c.oid = p_parent;
  v_existed := to_regclass(format('%I.%I', v_nsp, p_child)) is not null;
  insert into pgpm_test60.calls (hook_name, child, child_existed) values ('hook_rec', p_child, v_existed);
end;
$$;

create function pgpm_test60.hook_fail(p_parent regclass, p_child name, p_lo text, p_hi text)
returns void language plpgsql as $$
begin
  raise exception 'simulated archive failure for %', p_child;
end;
$$;

create table public.rt60 (id bigint generated by default as identity primary key, payload text);
insert into public.rt60 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
select pgpm.transmute('public.rt60', 'id', 10000, p_retain => 30000);   -- monolith [0, 60000)
select pgpm.obtain('public.rt60');   -- attaches [60000,70000) ... [90000,100000), all empty
insert into public.rt60 (id, payload) values (110000, 'frontier');   -- boundary 80000: eligible lo in (0, 60000, 70000)

-- a managed table WITHOUT a retention policy, to prove retire() refuses it
create table public.rt60b (id bigint generated by default as identity primary key);
insert into public.rt60b (id) values (1);
select pgpm.transmute('public.rt60b', 'id', 10000);

-- pgpm.part row names, captured before any drop so later assertions can still reference them
create table pgpm_test60.names as
  select lo, child_name from pgpm.part where parent_table = 'public.rt60'::regclass;

select throws_like(
  $$ select pgpm.retire('pgpm_test60.calls', 'whatever') $$,
  '%is not managed%', 'retire() refuses an unmanaged table');

select throws_like(
  $$ select pgpm.retire('public.rt60b', 'whatever') $$,
  '%no retention policy%', 'retire() refuses a table with no retention policy: it never drops what retention would not');

select throws_like(
  $$ select pgpm.retire('public.rt60',
       (select child_name from pgpm_test60.names where lo = '80000')) $$,
  '%retention horizon%', 'retire() refuses a partition whose range is not entirely past the horizon');

insert into pgpm.part (parent_table, child_name, lo, hi, attached)
  values ('public.rt60', 'rt60_pinflight', '200000', '210000', false);
select throws_like(
  $$ select pgpm.retire('public.rt60', 'rt60_pinflight') $$,
  '%not an attached partition%', 'retire() refuses an in-flight (unattached) drain/regrain child');
delete from pgpm.part where parent_table = 'public.rt60'::regclass and child_name = 'rt60_pinflight';

select pgpm.hook_register('public.rt60', 'pre_drop', 'pgpm_test60.hook_rec(regclass,name,text,text)');

select ok(
  pgpm.retire('public.rt60', (select child_name from pgpm_test60.names where lo = '0')),
  'retire() returns true when it drops the partition');

select ok(
  to_regclass('public.' || (select child_name from pgpm_test60.names where lo = '0')) is null
  and not exists (select 1 from pgpm.part where parent_table = 'public.rt60'::regclass and lo = '0'),
  'the partition table is gone and its pgpm.part row deleted');

select is(
  (select count(*)::int from pgpm_test60.calls where hook_name = 'hook_rec' and child_existed),
  1, 'the pre_drop hook ran, and before the drop (it saw the child still present)');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rt60'::regclass and action = 'retain_drop' and lo = '0'),
  1, 'the drop is logged as retain_drop, same as under retain()');

select ok(
  not pgpm.retire('public.rt60', (select child_name from pgpm_test60.names where lo = '0')),
  'retire() on an already-retired child is a cooperative no-op: false, not an error');

select is(
  (select count(*)::int from pgpm_test60.calls),
  1, 'the no-op retire invoked no hooks');

select pgpm.hook_register('public.rt60', 'pre_drop', 'pgpm_test60.hook_fail(regclass,name,text,text)');

select ok(
  not pgpm.retire('public.rt60', (select child_name from pgpm_test60.names where lo = '60000')),
  'a raising pre_drop hook makes retire() return false');

select ok(
  to_regclass('public.' || (select child_name from pgpm_test60.names where lo = '60000')) is not null
  and (select count(*)::int from pgpm.log
        where parent_table = 'public.rt60'::regclass and action = 'retain_hook_fail' and lo = '60000') = 1,
  'the partition is kept and the failure logged (retain_hook_fail), the same contract as under retain()');

select pgpm.hook_unregister('public.rt60', 'pre_drop', 'pgpm_test60.hook_fail(regclass,name,text,text)');

-- concurrency: a second session (dblink) claims the pgpm.part row and holds it in an open
-- transaction; retire() must yield immediately (SKIP LOCKED), not block and not error.
select dblink_connect('c60', 'dbname=' || current_database());
select dblink_exec('c60', 'begin');
select * from dblink('c60', format(
  'select child_name from pgpm.part where parent_table = %L::regclass and child_name = %L for update',
  'public.rt60', (select child_name from pgpm_test60.names where lo = '60000'))) as t(child name);

select ok(
  not pgpm.retire('public.rt60', (select child_name from pgpm_test60.names where lo = '60000')),
  'retire() returns false while another session holds the claim: no wait, no error');

select ok(
  to_regclass('public.' || (select child_name from pgpm_test60.names where lo = '60000')) is not null
  and (select count(*)::int from pgpm_test60.calls where hook_name = 'hook_rec') = 1,
  'the blocked retire invoked no hooks and dropped nothing');

select dblink_exec('c60', 'commit');
select dblink_disconnect('c60');

select ok(
  pgpm.retire('public.rt60', (select child_name from pgpm_test60.names where lo = '60000')),
  'once the claim is released, retire() proceeds and drops');

select is(pgpm.retain('public.rt60'), 1,
  'retain(), now a loop over retire(), drops the one remaining eligible partition');

-- cleanup (this file runs committed; see the NOTE up top)
delete from pgpm.hook   where parent_table = 'public.rt60'::regclass;
delete from pgpm.part   where parent_table in ('public.rt60'::regclass, 'public.rt60b'::regclass);
delete from pgpm.log    where parent_table in ('public.rt60'::regclass, 'public.rt60b'::regclass);
delete from pgpm.config where parent_table in ('public.rt60'::regclass, 'public.rt60b'::regclass);
drop table public.rt60 cascade;
drop table public.rt60b cascade;
drop schema pgpm_test60 cascade;

select * from finish();
