-- pgpm.retire (issue #195): the sanctioned single-partition drop -- retain()'s per-partition body
-- made public and claim-guarded, so an external assistant (e.g. an archive-then-drop scanner) or
-- several cooperating ones can drive retirement themselves through the same protocol retain() uses:
-- claim, ensure write-blocked, gate on archive coverage, DROP, catalog + log. The contract under
-- test:
--   * retire() never widens what retention may drop: it refuses (raises) an unmanaged table, a
--     table with no retention policy, a partition not entirely past the horizon, and an in-flight
--     (unattached) drain/regrain child -- a caller only picks WHICH eligible partition and WHEN;
--   * one owner per partition at a time: the pgpm.part row is claimed FOR UPDATE SKIP LOCKED
--     (issue #188), so a concurrent claimant makes retire() return false immediately -- no wait,
--     no error;
--   * an absent pgpm.part row (already retired by another actor) is a cooperative no-op (false);
--   * as of issue #238: retire() ENSURES the child is write-blocked (idempotent install) regardless
--     of whether it ends up dropping it, and GATES the actual drop on pgpm._archive_fully_covered --
--     a not-yet-covered child makes retire() return false, log NOTHING (a normal, retryable state,
--     not a failure), and keep the partition, until a later call finds it covered;
--   * pgpm.hook, the old pre_drop registry this superseded, is gone entirely (issue #240);
--   * retain() is now a loop over retire() and behaves as before (tests/07/34/40/59).
--
-- NOTE: this file does NOT use the usual begin/rollback isolation. The concurrency assertions need
-- a second session (dblink) to see and lock the fixture's pgpm.part rows, which requires the
-- fixture to be COMMITTED. The file cleans up everything it created at the end instead.
create extension if not exists pgtap;
create extension if not exists dblink;

select plan(16);

create schema pgpm_test60;

create table public.rt60 (id bigint generated by default as identity primary key, payload text);
insert into public.rt60 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
select pgpm.transmute('public.rt60', 'id', 10000, p_retain => 30000);   -- monolith [0, 60000)
select pgpm.obtain('public.rt60');   -- attaches [60000,70000) ... [90000,100000), all empty
insert into public.rt60 (id, payload) values (110000, 'frontier');   -- boundary 80000: eligible lo in (0, 60000, 70000)

-- a managed table WITHOUT a retention policy, to prove retire() refuses it
create table public.rt60b (id bigint generated by default as identity primary key);
insert into public.rt60b (id) values (1);
select pgpm.transmute('public.rt60b', 'id', 10000);

-- pgpm.part row names, captured before any drop so later assertions can still reference them
create table pgpm_test60.names as
  select lo, child_name from pgpm.part where parent_table = 'public.rt60'::regclass;

select throws_like(
  $$ select pgpm.retire('pgpm_test60.names', 'whatever') $$,
  '%is not managed%', 'retire() refuses an unmanaged table');

select throws_like(
  $$ select pgpm.retire('public.rt60b', 'whatever') $$,
  '%no retention policy%', 'retire() refuses a table with no retention policy: it never drops what retention would not');

select throws_like(
  $$ select pgpm.retire('public.rt60',
       (select child_name from pgpm_test60.names where lo = '80000')) $$,
  '%retention horizon%', 'retire() refuses a partition whose range is not entirely past the horizon');

insert into pgpm.part (parent_table, child_name, lo, hi, attached)
  values ('public.rt60', 'rt60_pinflight', '200000', '210000', false);
select throws_like(
  $$ select pgpm.retire('public.rt60', 'rt60_pinflight') $$,
  '%not an attached partition%', 'retire() refuses an in-flight (unattached) drain/regrain child');
delete from pgpm.part where parent_table = 'public.rt60'::regclass and child_name = 'rt60_pinflight';

-- rt60 has no archive strategy (archive_fn null, the default) throughout, so it is always
-- trivially archive-covered -- this section is purely about the claim/drop protocol itself.

select ok(
  pgpm.retire('public.rt60', (select child_name from pgpm_test60.names where lo = '0')),
  'retire() returns true when it drops the partition');

select ok(
  to_regclass('public.' || (select child_name from pgpm_test60.names where lo = '0')) is null
  and not exists (select 1 from pgpm.part where parent_table = 'public.rt60'::regclass and lo = '0'),
  'the partition table is gone and its pgpm.part row deleted');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rt60'::regclass and action = 'retain_drop' and lo = '0'),
  1, 'the drop is logged as retain_drop');

select ok(
  not pgpm.retire('public.rt60', (select child_name from pgpm_test60.names where lo = '0')),
  'retire() on an already-retired child is a cooperative no-op: false, not an error');

-- concurrency: a second session (dblink) claims the pgpm.part row and holds it in an open
-- transaction; retire() must yield immediately (SKIP LOCKED), not block and not error.
select dblink_connect('c60', 'dbname=' || current_database());
select dblink_exec('c60', 'begin');
select * from dblink('c60', format(
  'select child_name from pgpm.part where parent_table = %L::regclass and child_name = %L for update',
  'public.rt60', (select child_name from pgpm_test60.names where lo = '60000'))) as t(child name);

select ok(
  not pgpm.retire('public.rt60', (select child_name from pgpm_test60.names where lo = '60000')),
  'retire() returns false while another session holds the claim: no wait, no error');

select ok(
  to_regclass('public.' || (select child_name from pgpm_test60.names where lo = '60000')) is not null,
  'the blocked retire dropped nothing');

select dblink_exec('c60', 'commit');
select dblink_disconnect('c60');

select ok(
  pgpm.retire('public.rt60', (select child_name from pgpm_test60.names where lo = '60000')),
  'once the claim is released, retire() proceeds and drops');

select is(pgpm.retain('public.rt60'), 1,
  'retain(), now a loop over retire(), drops the one remaining eligible partition');

-- a dedicated table for the archive-coverage gate itself, kept separate from rt60's plain
-- claim/drop scenarios above so the two concerns don't entangle.
create table public.rt60c (id bigint generated by default as identity primary key, payload text);
insert into public.rt60c (payload) select 'x' from generate_series(1, 100);
select pgpm.transmute('public.rt60c', 'id', 1000, p_retain => 98000, p_paused => false);   -- monolith [0, 1000)
insert into public.rt60c (id, payload) values (100000, 'frontier');   -- boundary 2000: monolith eligible
update pgpm.config set archive_fn = 'pgpm._archive_noop(regclass,name,text,text)'::regprocedure
  where parent_table = 'public.rt60c'::regclass;

create table pgpm_test60.names_c as
  select lo, child_name from pgpm.part where parent_table = 'public.rt60c'::regclass;

select ok(
  not pgpm.retire('public.rt60c', (select child_name from pgpm_test60.names_c where lo = '0')),
  'retire() returns false (not raised) when past the horizon but not yet archive-covered');

select ok(
  pgpm._is_write_blocked('public.rt60c', (select child_name from pgpm_test60.names_c where lo = '0')),
  'retire() ENSURES write-blocking regardless of whether it ends up dropping the partition -- it ran before the archive-coverage check returned false');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.rt60c'::regclass and action in ('retain_drop', 'retain_drop_fail')),
  0, 'nothing drop-related is logged for a not-yet-covered partition -- a normal, retryable state, not a failure');

select pgpm._archive_step('public.rt60c'::regclass);   -- the archiving catches up

select ok(
  pgpm.retire('public.rt60c', (select child_name from pgpm_test60.names_c where lo = '0')),
  'once archive coverage completes, retire() proceeds and drops');

-- cleanup (this file runs committed; see the NOTE up top)
delete from pgpm.part   where parent_table in ('public.rt60'::regclass, 'public.rt60b'::regclass, 'public.rt60c'::regclass);
delete from pgpm.log    where parent_table in ('public.rt60'::regclass, 'public.rt60b'::regclass, 'public.rt60c'::regclass);
delete from pgpm.archive_ledger where parent_table = 'public.rt60c'::regclass;
delete from pgpm.config where parent_table in ('public.rt60'::regclass, 'public.rt60b'::regclass, 'public.rt60c'::regclass);
drop table public.rt60 cascade;
drop table public.rt60b cascade;
drop table public.rt60c cascade;
drop schema pgpm_test60 cascade;

select * from finish();
