-- Write-block on retain-eligibility (issue #235).
-- Chunked archiving can take several maintain() ticks to fully archive one large partition, and
-- for the whole span between crossing _retain_boundary() and the last chunk landing, the
-- partition sits attached and, absent anything to stop it, fully writable -- a backdated write in
-- that span silently diverges an already-archived copy from what is still live. This installs a
-- BEFORE INSERT OR UPDATE OR DELETE trigger on a child the instant it crosses the retention
-- boundary, independent of whether or how it is archived (that wiring is #236-#239, not this
-- issue): REVOKE only checks the parent's ACL on a parent-routed write, never the child's, and a
-- lock spanning the whole archiving span defeats the point of chunking -- a trigger on the specific
-- child is the one mechanism that is checked regardless of routing. pgpm.maintain() runs
-- _enforce_write_blocks ahead of retain()'s own drop logic every tick; retain_batch is pinned to 0
-- here so retain() never actually drops the eligible partitions out from under this test (that
-- coupling -- retire() itself refusing to drop before archiving is covered -- is #238).
create extension if not exists pgtap;

select plan(22);

create schema pgpm_test61;

create table public.wb61 (id bigint generated by default as identity primary key, payload text);
insert into public.wb61 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
call pgpm.transmute('public.wb61', 'id', 10000, p_retain => 30000, p_paused => false);   -- monolith [0, 60000)
select pgpm.obtain('public.wb61');   -- attaches [60000,70000) [70000,80000) [80000,90000) [90000,100000), all empty
update pgpm.config set retain_batch = 0 where parent_table = 'public.wb61'::regclass;   -- retain() attempts nothing

insert into public.wb61 (id, payload) select g, 'y' from generate_series(60001, 60005) g;  -- into [60000,70000)
insert into public.wb61 (id, payload) select g, 'z' from generate_series(70001, 70005) g;  -- into [70000,80000)
insert into public.wb61 (id, payload) values (110000, 'frontier');   -- advances the frontier to 110000

-- boundary = grid_floor(110000 - 30000, step 10000) = 80000: eligible (hi <= 80000) = the monolith
-- [0,60000), [60000,70000), [70000,80000); [80000,90000) and [90000,100000) stay above it.
create table pgpm_test61.names as
  select lo, child_name from pgpm.part where parent_table = 'public.wb61'::regclass;

select is(
  (select count(*)::int from pg_trigger t
     join pg_class c on c.oid = t.tgrelid
    where t.tgname = 'pgpm_write_block'
      and c.relname in (select child_name from pgpm.part where parent_table = 'public.wb61'::regclass)),
  0, 'before any maintain() tick, no child has the write-block trigger');

call pgpm.maintain('public.wb61');
select pass('a maintain() tick runs (retain_batch=0, so retain() attempts nothing this tick)');

select ok(
  exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test61.names where lo = '0'))::regclass),
  'the monolith [0,60000), now entirely past the boundary, gets the write-block trigger');
select ok(
  exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test61.names where lo = '60000'))::regclass),
  '[60000,70000), also past the boundary, gets the trigger');
select ok(
  exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test61.names where lo = '70000'))::regclass),
  '[70000,80000), also past the boundary, gets the trigger');
select ok(
  not exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test61.names where lo = '80000'))::regclass),
  '[80000,90000), still under the boundary, is unaffected');
select ok(
  not exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test61.names where lo = '90000'))::regclass),
  '[90000,100000), still under the boundary, is unaffected');

select throws_like(
  $$ insert into public.wb61 (id, payload) values (65000, 'backdated') $$,
  '%past its retention boundary%',
  'a parent-routed write into a write-blocked range is rejected regardless of routing');

select throws_like(
  format($$ insert into public.%I (id, payload) values (55000, 'backdated-direct') $$,
    (select child_name from pgpm_test61.names where lo = '0')),
  '%past its retention boundary%',
  'a write addressed directly to the write-blocked child (bypassing the parent) is rejected the same way');

select throws_like(
  $$ update public.wb61 set payload = 'edited' where id = 60001 $$,
  '%past its retention boundary%',
  'UPDATE is blocked too, not just INSERT');

select throws_like(
  $$ delete from public.wb61 where id = 60001 $$,
  '%past its retention boundary%',
  'DELETE is blocked too');

select lives_ok(
  $$ insert into public.wb61 (id, payload) values (85000, 'still writable') $$,
  'a sibling child still under the boundary is unaffected by another child''s write block');
select is(
  (select count(*)::int from public.wb61 where id = 85000),
  1, 'the write into the unaffected sibling actually landed');

select is(
  (select count(*)::int from public.wb61),
  50012, 'reads through the parent are unaffected by any child''s write block (50000 + 5 + 5 + 1 frontier + 1 sibling)');

select lives_ok(
  $$ select pgpm._install_write_block('public.wb61',
       (select child_name from pgpm_test61.names where lo = '0')) $$,
  '_install_write_block is idempotent when called directly on an already-blocked child');

select lives_ok(
  $$ select pgpm._remove_write_block('public.wb61',
       (select child_name from pgpm_test61.names where lo = '80000')) $$,
  '_remove_write_block is a no-op (not an error) on a child that was never blocked');

call pgpm.maintain('public.wb61');
select pass('re-running maintain() is idempotent: no duplicate-trigger error');

select is(
  (select count(*)::int from pg_trigger
    where tgname = 'pgpm_write_block'
      and tgrelid = ('public.' || (select child_name from pgpm_test61.names where lo = '0'))::regclass),
  1, 'the second tick left exactly one trigger on the monolith, not two');

-- loosen retention: boundary becomes grid_floor(110000 - 500000) -- far below every partition's lo,
-- so nothing stays eligible and every write block installed above should come back off.
update pgpm.config set retain = 500000 where parent_table = 'public.wb61'::regclass;
call pgpm.maintain('public.wb61');
select pass('maintain() runs after config.retain is loosened');

select ok(
  not exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test61.names where lo = '0'))::regclass),
  'loosening config.retain removes the trigger from the monolith, now no longer eligible');
select ok(
  not exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test61.names where lo = '70000'))::regclass),
  'and from [70000,80000), also no longer eligible');

select lives_ok(
  $$ insert into public.wb61 (id, payload) values (65001, 'now writable again') $$,
  'a write into the now-unblocked [60000,70000) succeeds');

select * from finish();
