-- Pluggable archive_fn contract (issue #236).
-- Narrowed pgpm.hook's old generic pre_drop registry (removed entirely, issue #240) to one archive
-- STRATEGY per managed table (config.archive_fn, nullable regprocedure -- null = strategy 'none',
-- immediately drop-ready) and defines the calling contract a real strategy (#237's chunked port,
-- #239's real S3 functions) implements: archive_fn(p_parent regclass, p_child name, p_lo text,
-- p_hi text) returns pgpm.archive_result, called once per tick, expected to make bounded
-- incremental progress and report how much of [lo, hi) is now durably archived (covered_hi), not to
-- finish the whole range in one call.
create extension if not exists pgtap;

select plan(8);

create schema pgpm_test62;

-- a harmless stand-in for a real chunked archiver: given ANY [p_lo, p_hi), reports the midpoint as
-- covered and the row count actually in [p_lo, midpoint) -- proving _run_archive_strategy passes a
-- partial-progress result through unmodified (the contract does not require covered_hi = p_hi).
create function pgpm_test62.half_archiver(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language plpgsql as $$
declare v_mid text; v_rows bigint; v_result pgpm.archive_result;
begin
  v_mid := ((p_lo::numeric + p_hi::numeric) / 2)::bigint::text;
  execute format('select count(*) from public.%I where id >= %L and id < %L', p_child, p_lo, v_mid) into v_rows;
  v_result.covered_hi := v_mid;
  v_result.rows_archived := v_rows;
  return v_result;
end;
$$;

create table public.af62 (id bigint generated by default as identity primary key, payload text);
insert into public.af62 (payload) select 'x' from generate_series(1, 1000);   -- ids 1..1000
call pgpm.transmute('public.af62', 'id', 2000, p_paused => false);   -- monolith covers all 1000 rows

create table pgpm_test62.bounds as
  select lo, hi, child_name from pgpm.part where parent_table = 'public.af62'::regclass order by lo::numeric limit 1;

select is(
  (select archive_fn from pgpm.config where parent_table = 'public.af62'::regclass),
  null::regprocedure, 'archive_fn defaults to null (strategy ''none'') on a freshly transmuted table');

select throws_ok(
  $$ update pgpm.config set archive_fn = 'pgpm._archive_noop(regclass,name,text)'::regprocedure
       where parent_table = 'public.af62'::regclass $$,
  '42883', null,
  'assigning archive_fn with the wrong signature is refused at assignment time (regprocedure resolves eagerly), not discovered later at call time');

select lives_ok(
  $$ update pgpm.config set archive_fn = 'pgpm._archive_noop(regclass,name,text,text)'::regprocedure
       where parent_table = 'public.af62'::regclass $$,
  'a correctly-signed archive_fn (the built-in no-op strategy) is accepted');

select ok(
  (select (r).covered_hi = (select (lo::numeric + 300)::text from pgpm_test62.bounds)
      and (r).rows_archived = 200
     from (select pgpm._run_archive_strategy('public.af62',
             (select child_name from pgpm_test62.bounds),
             (select (lo::numeric + 100)::text from pgpm_test62.bounds),
             (select (lo::numeric + 300)::text from pgpm_test62.bounds)) as r) s),
  '_archive_noop dispatched via _run_archive_strategy reports the whole requested sub-range covered and its actual row count (200), not the child''s full range');

update pgpm.config set archive_fn = null where parent_table = 'public.af62'::regclass;

select ok(
  (select (r).covered_hi = (select hi from pgpm_test62.bounds) and (r).rows_archived is null
     from (select pgpm._run_archive_strategy('public.af62',
             (select child_name from pgpm_test62.bounds),
             (select lo from pgpm_test62.bounds),
             (select hi from pgpm_test62.bounds)) as r) s),
  'archive_fn null (strategy ''none''): _run_archive_strategy treats the whole range as already fully covered, with no rows actually archived');

select lives_ok(
  $$ update pgpm.config set archive_fn = 'pgpm_test62.half_archiver(regclass,name,text,text)'::regprocedure
       where parent_table = 'public.af62'::regclass $$,
  'a user-authored archive_fn matching the contract signature is accepted');

select ok(
  (select (r).covered_hi = (select ((lo::numeric + hi::numeric) / 2)::bigint::text from pgpm_test62.bounds)
      and (r).rows_archived = (select count(*)::bigint from public.af62
                                 where id >= (select lo::numeric from pgpm_test62.bounds)
                                   and id < (select ((lo::numeric + hi::numeric) / 2)::bigint from pgpm_test62.bounds))
     from (select pgpm._run_archive_strategy('public.af62',
             (select child_name from pgpm_test62.bounds),
             (select lo from pgpm_test62.bounds),
             (select hi from pgpm_test62.bounds)) as r) s),
  'a partial-progress result (covered_hi short of the requested hi) passes through _run_archive_strategy unmodified -- the contract does not require finishing the range in one call');

select throws_like(
  $$ select pgpm._run_archive_strategy('pgpm_test62.bounds', 'whatever', '0', '10') $$,
  '%is not managed%',
  '_run_archive_strategy refuses an unmanaged relation, the same convention as every other pgpm entry point');

select * from finish();
