-- Byte-budget chunked archiving, ported onto the archive_fn contract (issue #237; see
-- docs/retention-write-block-and-merge.md, #242). archive._next_range_byte_budget/archive.ledger
-- (#213, #221) proved that archiving a large partition safely means never doing it as one giant
-- transaction; this ports that mechanism -- unchanged in intent -- onto pgpm.config.archive_fn
-- (#236) and pgpm._install_write_block's trigger (#235): pgpm._archive_step only ever picks up a
-- child the write-block trigger has ALREADY been installed on, chunks it via
-- pgpm._next_archive_chunk (same avg-row-width/probe-sample estimate as the original, now scoped to
-- one child's own [lo, hi) instead of spanning the whole table), and records progress in
-- pgpm.archive_ledger. pgpm._archive_fully_covered is retire()'s drop precondition (#238).
-- pgpm_archive's old archive.ledger/archive.tick, the paced worker this superseded, are deleted
-- entirely (#240); pgpm._archive_noop (#236) is enough to exercise the whole path end to end
-- without any real S3 code (#239).
create extension if not exists pgtap;

begin;
select plan(14);

create schema pgpm_test63;

create table public.ac63 (id bigint generated by default as identity primary key, payload text);
insert into public.ac63 (payload) select repeat('x', 100) from generate_series(1, 100);   -- ids 1..100
select pgpm.transmute('public.ac63', 'id', 1000, p_retain => 98000, p_paused => false);   -- monolith [0,1000)
select pgpm.obtain('public.ac63');   -- attaches forward partitions past 1000, all empty

create table pgpm_test63.bounds as
  select lo, hi, child_name from pgpm.part where parent_table = 'public.ac63'::regclass;

-- a stray row in a forward partition that will stay OUTSIDE the retention boundary throughout this
-- test (used below to prove archiving never touches a not-yet-write-blocked child).
insert into public.ac63 (id, payload)
  select (select lo::bigint + 10 from pgpm_test63.bounds where hi::numeric > 2000 order by lo::numeric limit 1), 'stray';

insert into public.ac63 (id, payload) values (100000, 'frontier');   -- boundary = grid_floor(100000-98000,1000) = 2000:
                                                                       -- monolith [0,1000) and [1000,2000) eligible;
                                                                       -- hi > 2000 partitions stay ineligible

update pgpm.config set retain_batch = 0 where parent_table = 'public.ac63'::regclass;         -- retain() drops nothing
update pgpm.config set archive_byte_budget = 2000 where parent_table = 'public.ac63'::regclass; -- force many small chunks
update pgpm.config set archive_fn = 'pgpm._archive_noop(regclass,name,text,text)'::regprocedure
  where parent_table = 'public.ac63'::regclass;

select is(
  pgpm._archive_fully_covered('public.ac63', (select child_name from pgpm_test63.bounds where lo = '0')),
  false, 'the monolith is not fully covered before any maintain() tick has archived it');

-- drive maintain() ticks until the monolith is fully covered (or a safety cap trips), counting how
-- many ticks it actually took.
create table pgpm_test63.progress (n int);
do $$
declare i int := 0; v_child name;
begin
  select child_name into v_child from pgpm_test63.bounds where lo = '0';
  while not pgpm._archive_fully_covered('public.ac63', v_child) and i < 100 loop
    perform pgpm.maintain('public.ac63');
    i := i + 1;
  end loop;
  insert into pgpm_test63.progress values (i);
end $$;

select cmp_ok(
  (select n from pgpm_test63.progress), '>', 1,
  'more than one maintain() tick was needed -- the byte budget forced bounded, incremental progress, not one giant call');
select cmp_ok(
  (select n from pgpm_test63.progress), '<', 100,
  'archiving actually converged within the safety cap (did not stall)');

select ok(
  pgpm._archive_fully_covered('public.ac63', (select child_name from pgpm_test63.bounds where lo = '0')),
  '_archive_fully_covered flips true once the last chunk has landed');

select is(
  (select sum(rows_archived)::int from pgpm.archive_ledger
    where parent_table = 'public.ac63'::regclass
      and child_name = (select child_name from pgpm_test63.bounds where lo = '0')),
  100, 'every one of the 100 rows was archived exactly once across all chunks -- no duplication, no gap');

select ok(
  not exists (
    select 1 from (
      select lo, lag(hi) over (order by lo::numeric) as prev_hi
        from pgpm.archive_ledger
       where parent_table = 'public.ac63'::regclass
         and child_name = (select child_name from pgpm_test63.bounds where lo = '0')
    ) s
    where prev_hi is not null and prev_hi <> lo
  ), 'resuming across ticks never duplicated or skipped a range: each chunk''s lo is exactly the prior chunk''s hi');

select is(
  (select min(lo) from pgpm.archive_ledger
    where parent_table = 'public.ac63'::regclass
      and child_name = (select child_name from pgpm_test63.bounds where lo = '0')),
  '0', 'the first chunk started exactly at the monolith''s own lo');

select is(
  (select max(hi::numeric)::text from pgpm.archive_ledger
    where parent_table = 'public.ac63'::regclass
      and child_name = (select child_name from pgpm_test63.bounds where lo = '0')),
  '1000', 'the last chunk ended exactly at the monolith''s own hi');

select is(
  (select count(*)::int from pgpm.archive_ledger
    where parent_table = 'public.ac63'::regclass
      and child_name = (select child_name from pgpm_test63.bounds where hi::numeric > 2000 order by lo::numeric limit 1)),
  0, 'a child past the byte budget''s reach but NOT YET write-blocked is never touched, even though it holds a real row and archive_fn is set for the whole table');

select throws_like(
  $$ select pgpm._archive_fully_covered('pgpm_test63.bounds', 'whatever') $$,
  '%is not managed%',
  '_archive_fully_covered refuses an unmanaged relation, the same convention as every other pgpm entry point');

-- a separate table with no archive strategy at all: strategy 'none' is immediately drop-ready,
-- with nothing ever recorded to the ledger.
create table public.ac63n (id bigint generated by default as identity primary key, payload text);
insert into public.ac63n (payload) select 'x' from generate_series(1, 50);
select pgpm.transmute('public.ac63n', 'id', 1000, p_retain => 0, p_paused => false);

select is(
  (select archive_fn from pgpm.config where parent_table = 'public.ac63n'::regclass),
  null::regprocedure, 'the comparison table has no archive strategy configured (archive_fn null, the default)');

select ok(
  pgpm._archive_fully_covered('public.ac63n', (select child_name from pgpm.part where parent_table = 'public.ac63n'::regclass limit 1)),
  'a partition with archive_fn null (strategy ''none'') is immediately fully covered, with no maintain() tick needed');

select lives_ok(
  $$ select pgpm.maintain('public.ac63n') $$,
  'maintain() runs fine on a none-strategy table');

select is(
  (select count(*)::int from pgpm.archive_ledger where parent_table = 'public.ac63n'::regclass),
  0, 'a none-strategy table never gets a ledger entry -- there is nothing to chunk');

select * from finish();
rollback;
