-- Full lifecycle test for issue #238:
-- pgpm.retire()'s drop precondition is now write-blocked + pgpm._archive_fully_covered, not a
-- pre_drop hook (pgpm.hook itself is gone entirely, issue #240). This is the issue's own test plan:
-- a child crosses the retention boundary, becomes write-blocked immediately, but stays UNDROPPED
-- while chunked archiving is still catching up, and drops on the very first maintain() tick once
-- coverage completes; a none-strategy child (no archiving configured at all -- the common case)
-- drops on the very next eligible cycle, exactly as retain() always behaved before this stack
-- existed.
create extension if not exists pgtap;

begin;
select plan(8);

create schema pgpm_test64;

-- Scenario A: chunked archiving gates the drop across several ticks.
create table public.rg64a (id bigint generated by default as identity primary key, payload text);
insert into public.rg64a (payload) select repeat('x', 100) from generate_series(1, 100);   -- ids 1..100
select pgpm.transmute('public.rg64a', 'id', 1000, p_retain => 98000, p_paused => false);   -- monolith [0,1000)
select pgpm.obtain('public.rg64a');

create table pgpm_test64.bounds_a as
  select lo, hi, child_name from pgpm.part where parent_table = 'public.rg64a'::regclass order by lo::numeric limit 1;

insert into public.rg64a (id, payload) values (100000, 'frontier');   -- boundary 2000: monolith eligible

update pgpm.config set archive_byte_budget = 2000 where parent_table = 'public.rg64a'::regclass;   -- force many small chunks
update pgpm.config set archive_fn = 'pgpm._archive_noop(regclass,name,text,text)'::regprocedure
  where parent_table = 'public.rg64a'::regclass;

-- one tick: write-blocked immediately, but archiving has only made partial (bounded) progress.
select pgpm.maintain('public.rg64a');

select ok(
  pgpm._is_write_blocked('public.rg64a', (select child_name from pgpm_test64.bounds_a)),
  'the monolith is write-blocked the moment it crosses the retention boundary');

select ok(
  exists (select 1 from pgpm.part where parent_table = 'public.rg64a'::regclass
           and child_name = (select child_name from pgpm_test64.bounds_a)),
  'but NOT dropped yet -- archive coverage is still incomplete after just one tick');

select throws_like(
  $$ insert into public.rg64a (id, payload) values (500, 'backdated') $$,
  '%past its retention boundary%',
  'and a write into it is rejected, exactly as the write-block trigger promises');

-- drive maintain() until the partition is gone (mirrors tests/63's own loop). NOTE: coverage
-- completing and the drop happen in the SAME tick (_archive_step runs before retain() within one
-- maintain() call), so once the child is gone, checking _archive_fully_covered on it further would
-- raise (it is no longer a tracked partition) rather than return true -- loop on existence instead.
create table pgpm_test64.progress_a (n int);
do $$
declare i int := 0; v_child name;
begin
  select child_name into v_child from pgpm_test64.bounds_a;
  while exists (select 1 from pgpm.part where parent_table = 'public.rg64a'::regclass and child_name = v_child)
        and i < 100
  loop
    perform pgpm.maintain('public.rg64a');
    i := i + 1;
  end loop;
  insert into pgpm_test64.progress_a values (i);
end $$;

select cmp_ok(
  (select n from pgpm_test64.progress_a), '>', 1,
  'dropping took more than one additional tick -- the byte budget really did force bounded, incremental archiving first, not an immediate drop');
select cmp_ok(
  (select n from pgpm_test64.progress_a), '<', 100, 'and it actually converged within the safety cap (did not stall)');

select ok(
  not exists (select 1 from pgpm.part where parent_table = 'public.rg64a'::regclass
               and child_name = (select child_name from pgpm_test64.bounds_a)),
  'once archive coverage completes, the partition drops -- in the very same tick coverage finishes');

-- Scenario B: no archive strategy at all (archive_fn null, the default and common case) drops on
-- the very next eligible cycle, exactly as retain() always did before this stack existed.
create table public.rg64b (id bigint generated by default as identity primary key, payload text);
insert into public.rg64b (payload) select 'x' from generate_series(1, 50);
select pgpm.transmute('public.rg64b', 'id', 1000, p_retain => 98000, p_paused => false);   -- monolith [0,1000)

create table pgpm_test64.bounds_b as
  select lo, hi, child_name from pgpm.part where parent_table = 'public.rg64b'::regclass order by lo::numeric limit 1;

insert into public.rg64b (id, payload) values (100000, 'frontier');   -- boundary 2000: monolith eligible

select is(
  (select archive_fn from pgpm.config where parent_table = 'public.rg64b'::regclass),
  null::regprocedure, 'no archive strategy is configured for this table');

select pgpm.maintain('public.rg64b');   -- ONE tick: write-block, "archive" (trivially covered), retain -- all in it

select ok(
  not exists (select 1 from pgpm.part where parent_table = 'public.rg64b'::regclass
               and child_name = (select child_name from pgpm_test64.bounds_b)),
  'a none-strategy child drops on the very next eligible cycle, exactly as retain() always did before this stack');

select * from finish();
rollback;
