-- pgpm.set_archive_fn: the operator switch for config.archive_fn (issue #236's contract), matching
-- the same set_X(parent, ...) convention as set_regrain/set_drain_adaptive/set_drain_ambient --
-- an operator should never need a raw `update pgpm.config set archive_fn = ...` for normal use.
create extension if not exists pgtap;

begin;
select plan(5);

create schema pgpm_test66;
create function pgpm_test66.stub_archiver(p_parent regclass, p_child name, p_lo text, p_hi text)
returns pgpm.archive_result language sql as $$ select null::pgpm.archive_result $$;

create table public.af66 (id bigint generated by default as identity primary key, payload text);
insert into public.af66 (payload) select 'x' from generate_series(1, 100);
select pgpm.transmute('public.af66', 'id', 1000, p_paused => false);

select is(
  (select archive_fn from pgpm.config where parent_table = 'public.af66'::regclass),
  null::regprocedure, 'archive_fn defaults to null before set_archive_fn is ever called');

select pgpm.set_archive_fn('public.af66', 'pgpm_test66.stub_archiver(regclass,name,text,text)'::regprocedure);

select is(
  (select archive_fn from pgpm.config where parent_table = 'public.af66'::regclass),
  'pgpm_test66.stub_archiver(regclass,name,text,text)'::regprocedure,
  'set_archive_fn assigns the named strategy');

select pgpm.set_archive_fn('public.af66');   -- p_archive_fn defaults to null: turns archiving back off

select is(
  (select archive_fn from pgpm.config where parent_table = 'public.af66'::regclass),
  null::regprocedure, 'set_archive_fn with no second argument clears the strategy back to none');

create table public.unmanaged66 (id int);

select throws_like(
  $$ select pgpm.set_archive_fn('public.unmanaged66') $$,
  '%is not managed%',
  'set_archive_fn refuses an unmanaged relation, the same convention as set_regrain/set_drain_adaptive');

select throws_ok(
  $$ select pgpm.set_archive_fn('public.af66', 'pgpm_test66.stub_archiver(regclass,name,text)'::regprocedure) $$,
  '42883', null,
  'a wrongly-signed archive_fn is refused at the regprocedure cast, before set_archive_fn ever runs');

select * from finish();
rollback;
