-- The pg_cron dispatch contract for retiring a REFERENCED partition (issue #268).
--
-- Retirement of a referenced partition needs `ALTER TABLE ... DETACH PARTITION ... CONCURRENTLY`: the
-- plain form holds ACCESS EXCLUSIVE on the MANAGED PARENT for the whole O(referencing table) scan, so
-- a concurrent read of the parent dies with 55P03. But PostgreSQL refuses the concurrent form in every
-- context pgpm has ("cannot be executed from a function") -- not from a procedure that has already
-- committed, not from a DO block, not via dynamic EXECUTE. pgpm is pure SQL, so it cannot issue the
-- statement at all. It DISPATCHES it instead: a pg_cron job's command runs as a top-level statement in
-- its own session, where the statement is legal.
--
-- tests/77 owns the state machine and performs the detach by hand at the top level, exactly as cron
-- would. THIS file owns the handoff: that pgpm asks cron for precisely the right statement, and puts
-- the job back to idle afterwards. It needs pg_cron, which on these images can only be created in the
-- database named by cron.database_name, so like tests/31 it runs against `postgres` rather than a
-- per-file clone (see test.sh).
--
-- The schedule used below is deliberately one that will not fire during the run. The assertions are
-- about the COMMAND pgpm writes, and a job actually firing mid-test would race the hand-run detach.
create extension if not exists pgtap;

select plan(9);

select pgpm.schedule('0 0 1 1 *');

-- LIVENESS. Every assertion below about the job's command says "retire() put this here". That is
-- satisfied by a run where the command was already the right thing, so pin the idle starting state.
select is(
  (select command from cron.job where jobname = 'pgpm_detach' and database = current_database()),
  'select 1', 'LIVENESS: schedule() creates the pgpm_detach job IDLE');

-- 50000 rows -> monolith [0,60000); the frontier write puts the horizon at 80000. The referencing row
-- points at a LIVE row, so there is no crossing and nothing blocks the detach.
create table public.dp78 (id bigint generated by default as identity primary key, payload text);
insert into public.dp78 (payload) select 'x' from generate_series(1, 50000);
call pgpm.transmute('public.dp78', 'id', 10000, p_retain => 30000);
select pgpm.obtain('public.dp78');
insert into public.dp78 (id, payload) values (110000, 'frontier');
create table public.dpref78 (id bigint primary key, p_id bigint not null references public.dp78(id));
insert into public.dpref78 values (1, 110000);

select child_name as doomed from pgpm.part
  where parent_table = 'public.dp78'::regclass and lo = '0' \gset

select ok(not pgpm.retire('public.dp78', :'doomed'),
  'retire() reports the partition as not yet dropped: the detach it needs happens elsewhere');

select is(
  (select command from cron.job where jobname = 'pgpm_detach' and database = current_database()),
  format('alter table public.dp78 detach partition public.%I concurrently', :'doomed'),
  'and points the standing job at exactly this partition''s concurrent detach, fully qualified');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.dp78'::regclass and action = 'retain_detach'),
  1, 'logged as exactly retain_detach');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.dp78'::regclass and action = 'fail_retain_detach'),
  0, 'and nothing failed to dispatch: the job was found and rewritten');

select is(
  (select retain_detaching from pgpm.status() where parent = 'public.dp78'::regclass),
  1::bigint, 'status() surfaces the retirement as in flight');

-- Run the dispatched command exactly as cron will: read it back out of the job and execute it at the
-- top level. If pgpm ever writes a command cron could not run, this fails here.
select command from cron.job where jobname = 'pgpm_detach' and database = current_database() \gexec

select ok(pgpm.retire('public.dp78', :'doomed'),
  'the next call finds it detached and completes the drop');

select is(
  (select command from cron.job where jobname = 'pgpm_detach' and database = current_database()),
  'select 1', 'and returns the job to idle, so it does not re-run a detach that already happened');

select is(pgpm.unschedule(), 2, 'unschedule() removes both jobs');

-- This file shares the `postgres` database with tests/31 and the uninstall check, so it cleans up its
-- catalog rows too, not just its tables: a pgpm.config row pointing at a dropped relation would break
-- pgpm.status() for anything that ran after it.
delete from pgpm.part   where parent_table = 'public.dp78'::regclass;
delete from pgpm.config where parent_table = 'public.dp78'::regclass;
drop table if exists public.dpref78, public.dp78 cascade;

select * from finish();
