-- transmute carries the table's OUTGOING foreign keys onto the new parent (issue #263).
--
-- THE BUG. A foreign key follows the table it is defined ON, and the conversion renames the original aside
-- to become the monolith child. So the constraint landed on the monolith and never on the new parent. It
-- kept enforcing there, which is exactly what made the loss easy to miss: a row routed into the monolith
-- was still checked, and only a row in a FORWARD partition escaped. Measured before the fix, an insert
-- referencing a row that does not exist was ACCEPTED, with no error and nothing in pgpm.log.
--
-- Partial enforcement is worse than none. The obvious post-conversion check -- "is my foreign key still
-- there?" -- passes, because the constraint genuinely exists; it is just scoped to one partition. So the
-- assertion that matters here is enforcement in a forward partition, not the presence of a catalog row.
--
-- THE FIX is metadata-only. PostgreSQL ADOPTS a partition's equivalent already-validated foreign key when
-- the same constraint is added at the parent, rather than rescanning: measured at 0.8 ms against a
-- 200,000-row monolith. That is why the conversion can re-add the key inside the same transaction as the
-- attach without holding a data-coupled lock -- and why a NOT VALID key is refused instead, since over one
-- of those the same ADD scans (89 ms at 2M rows, seq_tup_read +400,000 at 200k).
create extension if not exists pgtap;

select plan(11);

-- ============================ the fixture, with real referential integrity ============================
create table public.ofk_ref (id bigint primary key, label text);
insert into public.ofk_ref values (1, 'referenced'), (2, 'also referenced');

create table public.ofk (id bigint generated by default as identity primary key,
                         ref_id bigint not null references public.ofk_ref(id),
                         payload text);
insert into public.ofk (ref_id, payload) select (g % 2) + 1, 'x' from generate_series(1, 500) g;

-- LIVENESS. Every "it still enforces" assertion below is satisfied by a fixture that never enforced
-- anything, so prove the plain table rejected an orphan BEFORE the conversion.
select throws_ok(
  $$ insert into public.ofk (ref_id, payload) values (424242, 'orphan') $$,
  '23503', NULL,
  'LIVENESS: the plain table enforces its outgoing key before transmute');

call pgpm.transmute('public.ofk', 'id', 1000, p_paused => false);

-- ============================ the key is on the PARENT, not just the monolith ============================
select is(
  (select count(*)::int from pg_constraint
    where contype = 'f' and confrelid = 'public.ofk_ref'::regclass
      and conrelid = 'public.ofk'::regclass and conparentid = 0),
  1, 'the outgoing key is present on the PARENT');

select is(
  (select convalidated from pg_constraint
    where contype = 'f' and confrelid = 'public.ofk_ref'::regclass
      and conrelid = 'public.ofk'::regclass and conparentid = 0),
  true, 'and it is VALIDATED -- adopted from the monolith''s copy, not re-scanned');

-- The monolith's original constraint is demoted to a child of the parent's, rather than left standalone.
select is(
  (select conparentid <> 0 from pg_constraint
    where contype = 'f' and confrelid = 'public.ofk_ref'::regclass
      and conrelid = (select format('public.%I', child_name)::regclass from pgpm.part
                       where parent_table = 'public.ofk'::regclass and lo = '0')),
  true, 'the monolith''s own copy became a child of the parent constraint');

-- ============================ and it ENFORCES, in both places ============================
select throws_ok(
  $$ insert into public.ofk (ref_id, payload) values (424242, 'orphan') $$,
  '23503', NULL,
  'an orphan routed into the monolith is rejected');

-- THE assertion. This is the one that fails against the pre-fix code, where the constraint existed on the
-- monolith and the row simply landed somewhere it did not cover.
select throws_ok(
  format($$ insert into public.ofk (id, ref_id, payload) values (%s, 424242, 'orphan') $$,
         (select max(hi::bigint) - 1 from pgpm.part where parent_table = 'public.ofk'::regclass)),
  '23503', NULL,
  'and an orphan routed into a FORWARD partition is rejected too');

select lives_ok(
  $$ insert into public.ofk (ref_id, payload) values (2, 'valid reference') $$,
  'while a valid reference is still accepted: it enforces, rather than merely existing');

select is((select count(*)::int from public.ofk), 501,
  'every row survived the conversion, plus the one valid insert');

-- ============================ fidelity: the definition is replayed verbatim ============================
-- Composite keys and referential actions come along because the definition is replayed from
-- pg_get_constraintdef rather than reconstructed.
create table public.ofk2_ref (a bigint, b text, primary key (a, b));
insert into public.ofk2_ref values (1, 'x');
create table public.ofk2 (id bigint generated by default as identity primary key,
                          a bigint, b text,
                          foreign key (a, b) references public.ofk2_ref(a, b) on delete cascade);
insert into public.ofk2 (a, b) select 1, 'x' from generate_series(1, 100);
call pgpm.transmute('public.ofk2', 'id', 1000, p_paused => false);

select is(
  (select confdeltype from pg_constraint
    where contype = 'f' and conrelid = 'public.ofk2'::regclass and conparentid = 0),
  'c', 'a composite key keeps its ON DELETE CASCADE across the conversion');

-- the cascade actually fires through the parent
delete from public.ofk2_ref where a = 1;
select is((select count(*)::int from public.ofk2), 0,
  'and the cascade fires: deleting the referenced row clears the referencing rows');

-- ============================ a NOT VALID outgoing key is refused ============================
-- Re-adding it at the parent could not be metadata-only: PostgreSQL would rescan the whole table under a
-- lock that blocks writes on it and on the referenced table.
create table public.ofk3_ref (id bigint primary key);
create table public.ofk3 (id bigint generated by default as identity primary key, ref_id bigint);
insert into public.ofk3 (ref_id) select null from generate_series(1, 10);
alter table public.ofk3 add constraint ofk3_fk foreign key (ref_id) references public.ofk3_ref(id) not valid;

select throws_like(
  $$ call pgpm.transmute('public.ofk3', 'id', 1000) $$,
  '%are NOT VALID%',
  'a NOT VALID outgoing key is refused, with the VALIDATE CONSTRAINT remedy');

select * from finish();
