-- GENERATED ALWAYS survives the conversion (#308). transmute moves identity from the original table to
-- the new parent, and re-added it unconditionally as GENERATED BY DEFAULT -- so an ALWAYS column came
-- back BY DEFAULT.
--
-- That is not a cosmetic catalog difference. ALWAYS REJECTS an insert that supplies the column unless the
-- statement says OVERRIDING SYSTEM VALUE; BY DEFAULT accepts it. The downgrade therefore starts silently
-- accepting writes the operator's schema was written to refuse, with no error, no log line, and nothing
-- in status() to show for it. The first evidence is a row that should not exist.
--
-- Every assertion below is on the BEHAVIOUR (does the insert fail?), not on pg_attribute.attidentity.
-- A catalog assertion would pass against code that set the flag without restoring the semantics, which
-- is exactly the kind of green-for-the-wrong-reason this suite exists to avoid. The flag is checked once,
-- as a supporting detail, never as the proof.
create extension if not exists pgtap;

select plan(7);

create table public.ia (
  id         bigint      generated always as identity,
  created_at timestamptz not null default now(),
  payload    text,
  primary key (created_at, id)
);
insert into public.ia (created_at, payload)
  select now() - (g || ' minutes')::interval, 'x' from generate_series(1, 100) g;

-- LIVENESS WITNESS for the fixture: prove ALWAYS is actually in force BEFORE the conversion. Without
-- this, a fixture that had silently been created BY DEFAULT would make every assertion below pass while
-- testing nothing at all.
select throws_ok(
  $$ insert into public.ia (id, created_at, payload) values (9001, now(), 'supplied') $$,
  '428C9', null,
  'precondition: ALWAYS rejects a supplied value before the conversion');

call pgpm.transmute('public.ia', 'created_at', interval '1 day');

select throws_ok(
  $$ insert into public.ia (id, created_at, payload) values (9002, now(), 'supplied') $$,
  '428C9', null,
  'ALWAYS still rejects a supplied value after the conversion');

select lives_ok(
  $$ insert into public.ia (id, created_at, payload)
     overriding system value values (9003, now(), 'override') $$,
  'OVERRIDING SYSTEM VALUE is still the documented way through');

select lives_ok(
  $$ insert into public.ia (created_at, payload) values (now(), 'generated') $$,
  'an ordinary insert still gets a generated id');

select is(
  (select attidentity::text from pg_attribute
    where attrelid = 'public.ia'::regclass and attname = 'id'),
  'a', 'the parent records the column as ALWAYS');

-- The reversal must not quietly re-introduce the downgrade on the way back out.
select pgpm.untransmute('public.ia');

select throws_ok(
  $$ insert into public.ia (id, created_at, payload) values (9004, now(), 'supplied') $$,
  '428C9', null,
  'ALWAYS survives the round trip back through untransmute');

-- Control: do not over-correct. A BY DEFAULT column must stay BY DEFAULT, which is what every other
-- fixture in this suite relies on.
create table public.idflt (
  id         bigint      generated by default as identity,
  created_at timestamptz not null default now(),
  payload    text,
  primary key (created_at, id)
);
insert into public.idflt (created_at, payload) select now(), 'x' from generate_series(1, 10) g;

call pgpm.transmute('public.idflt', 'created_at', interval '1 day');

select lives_ok(
  $$ insert into public.idflt (id, created_at, payload) values (9005, now(), 'supplied') $$,
  'BY DEFAULT still accepts a supplied value');

select * from finish();
