-- _enforce_write_blocks isolates each child's install/remove attempt (issue #360).
--
-- Before this fix, the function's per-child loop had no per-iteration exception handling: a
-- failure installing (or removing) the write-block trigger on any one child raised out of the
-- whole loop, leaving every child after it in iteration order untouched for that tick --
-- regardless of whether those later children had any problem of their own. In production this
-- turned one recurring point of lock contention on one old partition into a stalled retention
-- backlog spanning many unrelated partitions.
--
-- This test proves isolation directly rather than via real lock contention (pgTAP wraps each file
-- in one transaction, so a genuine multi-session lock-timeout probe belongs in bench/, not here,
-- per this project's own established convention): a middle-ordered eligible child's underlying
-- table is dropped directly (bypassing pgpm entirely), leaving its pgpm.part row attached but
-- pointing at nothing. _install_write_block's `create trigger ... on <that child>` then fails
-- deterministically with a real "relation does not exist" error -- the same shape of failure a
-- lock timeout would produce (an exception raised mid-loop), without needing real contention.
create extension if not exists pgtap;

select plan(9);

create schema pgpm_test94;

create table public.wb94 (id bigint generated by default as identity primary key, payload text);
insert into public.wb94 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
call pgpm.transmute('public.wb94', 'id', 10000, p_retain => 30000, p_paused => false);   -- monolith [0, 60000)
select pgpm.obtain('public.wb94');   -- attaches [60000,70000) [70000,80000) [80000,90000) [90000,100000), all empty
update pgpm.config set retain_batch = 0 where parent_table = 'public.wb94'::regclass;

insert into public.wb94 (id, payload) select g, 'y' from generate_series(60001, 60005) g;  -- into [60000,70000)
insert into public.wb94 (id, payload) select g, 'z' from generate_series(70001, 70005) g;  -- into [70000,80000)
insert into public.wb94 (id, payload) values (110000, 'frontier');   -- advances the frontier to 110000

-- boundary = grid_floor(110000 - 30000, step 10000) = 80000: eligible (hi <= 80000, oldest to
-- newest by hi) = the monolith [0,60000), [60000,70000), [70000,80000).
create table pgpm_test94.names as
  select lo, child_name from pgpm.part where parent_table = 'public.wb94'::regclass;

-- Poison the MIDDLE eligible child by hi -- [60000,70000), hi=70000, sits between the monolith
-- (hi=60000, processed first) and [70000,80000) (hi=80000, processed last). Dropping its
-- underlying table directly (not via pgpm) leaves the pgpm.part row attached=true but pointing at
-- a relation that no longer exists.
do $$
begin
  execute format('drop table public.%I', (select child_name from pgpm_test94.names where lo = '60000'));
end $$;

select ok(
  exists (select 1 from pgpm.part where parent_table = 'public.wb94'::regclass
            and child_name = (select child_name from pgpm_test94.names where lo = '60000') and attached),
  'setup: the poisoned child''s pgpm.part row is still attached despite its table being gone');

select lives_ok(
  $$ select pgpm._enforce_write_blocks('public.wb94'::regclass) $$,
  '_enforce_write_blocks itself does not raise even though one child fails internally');

select ok(
  exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test94.names where lo = '0'))::regclass),
  'the monolith (oldest eligible child, processed before the poison) still gets write-blocked');

select ok(
  exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test94.names where lo = '70000'))::regclass),
  '[70000,80000) (newest eligible child, processed AFTER the poison) also still gets write-blocked -- '
  || 'the whole point of the fix: one child''s failure does not stop the rest of that tick''s pass');

select is(
  (select count(*)::int from pgpm.log
    where parent_table = 'public.wb94'::regclass and action = 'skip_write_block' and hi = '70000'),
  1, 'the poisoned child''s own failure is logged individually, attributed to its own hi');

select ok(
  (select method from pgpm.log
    where parent_table = 'public.wb94'::regclass and action = 'skip_write_block' and hi = '70000')
    like '%does not exist%',
  'the logged error is the real underlying failure (relation does not exist), not a generic message');

select ok(
  not exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test94.names where lo = '80000'))::regclass),
  '[80000,90000), still under the boundary, is correctly left unblocked'); -- regression: ordering/eligibility unaffected

select ok(
  not exists (select 1 from pg_trigger where tgname = 'pgpm_write_block'
    and tgrelid = ('public.' || (select child_name from pgpm_test94.names where lo = '90000'))::regclass),
  '[90000,100000), still under the boundary, is correctly left unblocked');

select lives_ok(
  $$ select pgpm._enforce_write_blocks('public.wb94'::regclass) $$,
  're-running _enforce_write_blocks is idempotent: no duplicate-trigger error on the already-blocked children, '
  || 'and no unhandled error from the still-poisoned child');

select * from finish();
