-- issue #341: set_regrain(parent, p_target_step) must refuse a p_target_step coarser than the
-- table's own config.partition_step. Accepting one silently wedges auto-regrain forever: the
-- candidate query in maintain() calls anything wider than one partition_step "coarse", but
-- regrain_step's own 'nosubdiv' guard refuses to split a child already at (or narrower than) the
-- target step -- so once a coarse child is split down to a regrain_to wider than partition_step,
-- every subsequent tick reselects it and makes no further progress, forever, with no error.
-- Equal-or-finer targets (and null, disabling auto-regrain) must remain unconditionally allowed.
create extension if not exists pgtap;
select plan(6);

create table public.sr (id bigint generated by default as identity primary key, payload text);
insert into public.sr (payload) select 'x' from generate_series(1, 10);
call pgpm.transmute('public.sr', 'id', 50, p_paused => false);   -- config.partition_step = '50'

-- coarser than partition_step: refused at call time, before it can ever wedge maintenance.
select throws_ok(
  $$ select pgpm.set_regrain('public.sr', '100') $$,
  'P0001', NULL, 'set_regrain refuses a target step coarser than partition_step');

select is(
  (select regrain_to from pgpm.config where parent_table = 'public.sr'::regclass),
  NULL, 'the refused call left regrain_to untouched (no partial wedge state)');

-- equal to partition_step: allowed (the guard does not just reject everything).
select lives_ok(
  $$ select pgpm.set_regrain('public.sr', '50') $$,
  'set_regrain allows a target step equal to partition_step');

select is(
  (select regrain_to from pgpm.config where parent_table = 'public.sr'::regclass),
  '50', 'regrain_to was set to the equal-step target');

-- finer than partition_step: allowed.
select lives_ok(
  $$ select pgpm.set_regrain('public.sr', '25') $$,
  'set_regrain allows a target step finer than partition_step');

-- disabling auto-regrain (null) stays unconditionally allowed regardless of any prior coarse attempt.
select lives_ok(
  $$ select pgpm.set_regrain('public.sr', null) $$,
  'set_regrain(parent, null) always succeeds (disable stays unconditional)');

select * from finish();
