-- Issue #290: obtain() is pgpm's ONLY defence against a write with nowhere to go now that the DEFAULT
-- partition is gone (#288), and for an `id` grid the frontier is DATA-driven and can jump arbitrarily far
-- past obtain's lookahead ceiling with no way to recover -- the write that would advance the frontier is
-- the write that fails. pgpm.extend_to(parent, value) is the relief valve: pre-extend the grid to cover a
-- known future value, without moving the frontier or touching data.
create extension if not exists pgtap;

select plan(13);

-- ==================== (A) id grid: extend far past a small lookahead =======================
create table public.et_id (id bigint primary key, body text);
insert into public.et_id (id, body) values (5, 'only');
call pgpm.transmute('public.et_id', 'id', 100::bigint, p_obtain => 2);
select pgpm.obtain('public.et_id');

-- LIVENESS WITNESS: the gap this guard exists to close is really there before extend_to runs.
select throws_like(
  $$ insert into public.et_id (id, body) values (5000, 'too far') $$,
  '%no partition of relation%found for row%',
  'setup: id 5000 is genuinely beyond the forward grid -- the write is refused before extend_to'
);

-- snapshot, BEFORE the call, exactly which of the 100-wide steps from the grid start through 5000 are
-- still missing -- so the assertion below is an IDENTITY check (the exact right count), not a loose bound.
create temporary table et_id_expect as
  select count(*)::int as n from generate_series(0, 5000, 100) g
   where not exists (
     select 1 from pgpm.part where parent_table = 'public.et_id'::regclass and attached and lo::numeric = g
   );

select is(
  pgpm.extend_to('public.et_id', '5000'),
  (select n from et_id_expect),
  'extend_to creates exactly the previously-missing grid steps from the current edge through 5000'
);

select is(
  (select count(*)::int from generate_series(0, 5000, 100) g
    where not exists (
      select 1 from pgpm.part where parent_table = 'public.et_id'::regclass and attached and lo::numeric = g
    )),
  0,
  'no gaps remain: every 100-wide step from the grid start through 5000 now has an attached partition'
);

select lives_ok(
  $$ insert into public.et_id (id, body) values (5000, 'now fits') $$,
  'the write at id 5000 that was refused above is now accepted'
);

select is(pgpm.extend_to('public.et_id', '5000'), 0,
  'extend_to is idempotent: a second call for the same value creates nothing');

-- ==================== (B) a wildly-off target is refused, not partially extended ============
create table public.et_cap (id bigint primary key, body text);
insert into public.et_cap (id, body) values (1, 'only');
call pgpm.transmute('public.et_cap', 'id', 100::bigint, p_obtain => 1);
select pgpm.obtain('public.et_cap');

-- LIVENESS WITNESS: reaching 1000000 genuinely needs far more than p_max => 5 steps, so the refusal
-- below is guarding real, needed work -- not a target that was already in reach.
select cmp_ok(
  (select count(*)::int from generate_series(0, 1000000, 100) g
    where not exists (
      select 1 from pgpm.part where parent_table = 'public.et_cap'::regclass and attached and lo::numeric = g
    )),
  '>', 5,
  'setup: reaching 1000000 needs far more than 5 new partitions'
);

select throws_like(
  $$ select pgpm.extend_to('public.et_cap', '1000000', 5) $$,
  'pg_partition_magician%more than%p_max%',
  'extend_to refuses loudly when the target would need more new partitions than p_max allows'
);

select is(
  (select count(*)::int from pgpm.part where parent_table = 'public.et_cap'::regclass),
  2,
  'the refused call created NOTHING -- still exactly the monolith + 1 forward partition from setup'
);

-- ==================== (C) an unmanaged table is refused ====================================
create table public.et_unmanaged (id bigint primary key);

select throws_like(
  $$ select pgpm.extend_to('public.et_unmanaged', '100') $$,
  'pg_partition_magician%is not managed%',
  'extend_to refuses a table pgpm does not manage'
);

-- ==================== (D) time grid: the engine is kind-agnostic, not id-specific ==========
create table public.et_time (id bigint generated by default as identity, ts timestamptz not null, body text,
  primary key (ts, id));
insert into public.et_time (ts, body) values (now(), 'only');
call pgpm.transmute('public.et_time', 'ts', interval '1 day', p_obtain => 1);
select pgpm.obtain('public.et_time');

select throws_like(
  $$ insert into public.et_time (ts, body) values (now() + interval '10 days', 'too far') $$,
  '%no partition of relation%found for row%',
  'setup: a timestamp 10 days out is genuinely beyond the 1-day forward grid'
);

select cmp_ok(pgpm.extend_to('public.et_time', (now() + interval '10 days')::text), '>', 0,
  'extend_to creates new day partitions to cover a value 10 days out');

select is(
  (select count(*)::int from generate_series(
      pgpm._grid_floor('time', '1 day', '2000-01-01 00:00:00+00', pgpm._frontier_native('public.et_time'::regclass), 'UTC')::timestamptz,
      date_trunc('day', now() + interval '10 days'),
      interval '1 day'
    ) g
    where not exists (
      select 1 from pgpm.part where parent_table = 'public.et_time'::regclass and attached and lo::timestamptz = g
    )),
  0,
  'no gaps remain in the day grid through the target'
);

select lives_ok(
  $$ insert into public.et_time (ts, body) values (now() + interval '10 days', 'now fits') $$,
  'the write 10 days out that was refused above is now accepted'
);

select * from finish();
