-- pgpm.set_obtain (issue #326): the first-class wrapper for changing config.obtain after transmute,
-- mirroring set_regrain/set_archive_fn/pause/resume so operators never hand-edit pgpm.config. A
-- negative p_obtain is not merely wrong, it is a SILENT no-op: obtain()'s `for k in 0 .. cfg.obtain
-- loop` never executes when cfg.obtain < 0 (0..-1 is an empty plpgsql range), so a negative value
-- quietly disables lookahead forever with nothing raised. set_obtain refuses it up front instead.
create extension if not exists pgtap;
select plan(6);

create table public.so97 (id bigint generated by default as identity primary key, payload text);
insert into public.so97 (payload) select 'x' from generate_series(1, 10);
call pgpm.transmute('public.so97', 'id', 100, p_obtain => 3, p_paused => false);

-- an ordinary table that regclass resolves fine but pgpm never registered
create table public.so97_unmanaged (id bigint primary key);

select throws_like(
  $$ select pgpm.set_obtain('public.so97', -1) $$,
  '%non-negative%', 'set_obtain refuses a negative p_obtain');

select is(
  (select obtain from pgpm.config where parent_table = 'public.so97'::regclass),
  3, 'the refused call left config.obtain untouched');

select lives_ok(
  $$ select pgpm.set_obtain('public.so97', 0) $$,
  'set_obtain allows 0 (no lookahead, mint only the frontier partition)');

select is(
  (select obtain from pgpm.config where parent_table = 'public.so97'::regclass),
  0, 'config.obtain was updated to 0');

select lives_ok(
  $$ select pgpm.set_obtain('public.so97', 7) $$,
  'set_obtain allows a positive value');

select throws_like(
  $$ select pgpm.set_obtain('public.so97_unmanaged', 5) $$,
  '%is not managed%', 'set_obtain refuses an unmanaged table');

select * from finish();
