-- pgpm.set_retain (issue #326): the first-class wrapper for changing config.retain after transmute,
-- mirroring set_regrain/set_archive_fn/pause/resume so operators never hand-edit pgpm.config directly.
--
-- retain is the DESTRUCTIVE knob (it decides what retain() DROPs), so the locked-in contract is:
-- set_retain REFUSES -- not warns -- whenever the new value would make the very next retain() tick
-- drop a partition the OLD value still kept. Loosening (a bigger interval/count, or null = keep
-- forever) can never trip this: a wider horizon only ever keeps a superset of what the old one kept.
-- It also validates p_retain's shape against control_kind the same way transmute does: numeric for
-- id, an interval for everything else (time/uuidv7/text_time all share _retain_boundary's non-id
-- branch).
create extension if not exists pgtap;
select plan(15);

-- ==================== id kind: the refuse-by-default contract ====================
create table public.sr98 (id bigint generated by default as identity primary key, payload text);
insert into public.sr98 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
call pgpm.transmute('public.sr98', 'id', 10000, p_retain => 30000);            -- monolith [0, 60000)
select pgpm.obtain('public.sr98');                                            -- attaches fine partitions from 60000
insert into public.sr98 (id, payload) values (110000, 'frontier');            -- old boundary = floor(110000-30000) = 80000

create table public.sr98_unmanaged (id bigint primary key);

select throws_like(
  $$ select pgpm.set_retain('public.sr98', 'not-a-number') $$,
  '%numeric%', 'set_retain refuses a non-numeric p_retain for control_kind id');

select throws_like(
  $$ select pgpm.set_retain('public.sr98_unmanaged', '1000') $$,
  '%is not managed%', 'set_retain refuses an unmanaged table');

-- tightening past a partition the old value kept: [80000, 90000) has hi=90000, kept under the old
-- boundary (80000) but would fall at-or-below a new boundary of 90000 (retain=20000).
select throws_like(
  $$ select pgpm.set_retain('public.sr98', '20000') $$,
  '%refused%', 'set_retain refuses a tighter retain that would newly drop a partition the old value kept');

select is(
  (select retain from pgpm.config where parent_table = 'public.sr98'::regclass),
  '30000', 'the refused call left config.retain untouched');

-- tightening that grid-floors to the SAME boundary (85000 -> floor 80000, identical to the current
-- one) drops nothing new, so it is allowed even though the raw number is smaller.
select lives_ok(
  $$ select pgpm.set_retain('public.sr98', '25000') $$,
  'set_retain allows a tighter value that grid-floors to the same boundary as before (nothing newly eligible)');

select is(
  (select retain from pgpm.config where parent_table = 'public.sr98'::regclass),
  '25000', 'config.retain was updated to 25000');

-- loosening (bigger retain => smaller/earlier boundary => strictly fewer drops) is unconditionally safe.
select lives_ok(
  $$ select pgpm.set_retain('public.sr98', '40000') $$,
  'set_retain allows loosening retention');

select is(
  (select retain from pgpm.config where parent_table = 'public.sr98'::regclass),
  '40000', 'config.retain was updated to 40000');

-- null (keep forever) is always safe, from any prior value.
select lives_ok(
  $$ select pgpm.set_retain('public.sr98', null) $$,
  'set_retain allows null (keep forever)');

select is(
  (select retain from pgpm.config where parent_table = 'public.sr98'::regclass),
  NULL, 'config.retain was cleared to null');

-- arming a bounded retain straight from "keep forever" is held to the exact same rule: the monolith
-- [0, 60000) would be dropped immediately, and retain was null (kept everything), so it is refused.
select throws_like(
  $$ select pgpm.set_retain('public.sr98', '50000') $$,
  '%refused%', 'set_retain refuses arming a bounded retain from null when it would immediately drop a live partition');

select is(
  (select retain from pgpm.config where parent_table = 'public.sr98'::regclass),
  NULL, 'the refused arm-from-null call left config.retain null');

-- a bounded value that does not reach any existing partition is safe even coming from null.
select lives_ok(
  $$ select pgpm.set_retain('public.sr98', '500000') $$,
  'set_retain allows a bounded value that does not newly drop anything, even from null');

select is(
  (select retain from pgpm.config where parent_table = 'public.sr98'::regclass),
  '500000', 'config.retain was updated to 500000');

-- ==================== time kind: interval-shaped validation ====================
create table public.sr98t (id bigint generated by default as identity, ts timestamptz not null, payload text,
  primary key (id, ts));
insert into public.sr98t (ts, payload) select now() - interval '1 day' * g, 'x' from generate_series(1, 5) g;
call pgpm.transmute('public.sr98t', 'ts', interval '1 day');

select throws_like(
  $$ select pgpm.set_retain('public.sr98t', 'not-an-interval') $$,
  '%interval%', 'set_retain refuses a non-interval p_retain for control_kind time');

select * from finish();
