-- regrain_step's swap calls restore_incoming_fks unconditionally once suspend found anything live
-- to suspend (`if v_fk > 0`) -- but restore_incoming_fks itself re-adds EVERY not-yet-restored FK
-- for the parent, not just the one(s) this swap suspended. A pre-existing "stale" FK (already
-- unrestored before the swap starts -- e.g. an earlier restore attempt that failed) gets caught up
-- in that sweep, and re-adding it needs a fresh lock on its referencing table -- taken from inside
-- the swap, while the managed parent is already under ACCESS EXCLUSIVE. If that referencing table
-- is contended, every other session is blocked for the whole wait (issue #378; measured in
-- bench/regrain_swap_timing.sh's contended case: ~99% of swap duration).
--
-- The fix: regrain_step now snapshots exactly which dropped_fk rows it is about to suspend and
-- passes that exact set to restore_incoming_fks, so a stale, pre-existing unrestored FK is left
-- alone by the swap -- deferred to the next tick's own, separate restore_incoming_fks call
-- (maintain()'s own per-tick flow already does this, install.sql:3868-3901, in its own
-- transaction after the swap has committed, and is not exercised by this file -- it would restore
-- the stale FK anyway via its own separate call, which would mask exactly what this test needs to
-- isolate: whether the SWAP itself touched it). Nothing newly observable is created: the stale FK
-- was already unrestored before this swap touched anything.
create extension if not exists pgtap;
select plan(7);

-- ============================ unit-level: p_ids scopes restore_incoming_fks directly ============================
create table public.m99a (id bigint generated by default as identity primary key, payload text);
insert into public.m99a (payload) select 'x' from generate_series(1, 200);
create table public.r99a_1 (id bigint generated by default as identity primary key,
                            m_id bigint references public.m99a(id));
create table public.r99a_2 (id bigint generated by default as identity primary key,
                            m_id bigint references public.m99a(id));
insert into public.r99a_1 (m_id) select 1 + floor(random() * 200)::int from generate_series(1, 10);
insert into public.r99a_2 (m_id) select 1 + floor(random() * 200)::int from generate_series(1, 10);

call pgpm.transmute('public.m99a', 'id', 500, p_paused => false, p_incoming_fks => 'preserve');

select is((select count(*)::int from pgpm.dropped_fk
            where parent_table = 'public.m99a'::regclass and restored_at is null),
  2, 'precondition: both FKs are dropped-and-unrestored after transmute');

select pgpm.restore_incoming_fks('public.m99a',
  (select array_agg(id) from pgpm.dropped_fk
    where parent_table = 'public.m99a'::regclass and referencing_table = 'public.r99a_1'::regclass));

select is((select count(*)::int from pg_constraint
            where conrelid = 'public.r99a_1'::regclass and contype = 'f' and conparentid = 0),
  1, 'p_ids scoped to r99a_1''s row restores only that FK');
select is((select count(*)::int from pg_constraint
            where conrelid = 'public.r99a_2'::regclass and contype = 'f' and conparentid = 0),
  0, 'r99a_2''s FK, not named in p_ids, is left alone');

select is(pgpm.restore_incoming_fks('public.m99a'), 1,
  'a subsequent call with no p_ids (the default) picks up the remainder');
select is((select count(*)::int from pg_constraint
            where conrelid = 'public.r99a_2'::regclass and contype = 'f' and conparentid = 0),
  1, 'r99a_2''s FK is now restored too');

-- ============================ integration-level: the swap leaves a stale FK alone ============================
create table public.m99b (id bigint generated by default as identity primary key, payload text);
insert into public.m99b (payload) select 'x' from generate_series(1, 500);
create table public.r99b_live (id bigint generated by default as identity primary key,
                               m_id bigint references public.m99b(id));
create table public.r99b_stale (id bigint generated by default as identity primary key,
                                m_id bigint references public.m99b(id));
insert into public.r99b_live (m_id) select 1 + floor(random() * 500)::int from generate_series(1, 20);
insert into public.r99b_stale (m_id) select 1 + floor(random() * 500)::int from generate_series(1, 20);

call pgpm.transmute('public.m99b', 'id', 200, p_paused => false, p_incoming_fks => 'preserve');
select pgpm.restore_incoming_fks('public.m99b');   -- both live for now

-- put r99b_stale back into "not yet restored" -- an earlier restore that simply never happened,
-- not something a regrain of this parent will ever suspend (nothing live to suspend for it).
-- Actually dropping the constraint, not just forging the bookkeeping row, mirrors
-- bench/regrain_swap_timing.sh's own proven technique for this exact scenario.
do $$
declare v_conname name;
begin
  select conname into v_conname from pg_constraint
   where conrelid = 'public.r99b_stale'::regclass and contype = 'f' and conparentid = 0;
  execute format('alter table public.r99b_stale drop constraint %I', v_conname);
end $$;
update pgpm.dropped_fk set restored_at = null
 where parent_table = 'public.m99b'::regclass and referencing_table = 'public.r99b_stale'::regclass;

-- freeze the monolith and drive regrain_step DIRECTLY through to the swap -- NOT via maintain(),
-- whose own separate outer restore_incoming_fks call (install.sql:3891) would restore the stale
-- FK anyway moments later and mask exactly what this test needs to isolate: whether the SWAP's
-- OWN internal call touched it.
insert into public.m99b (id, payload) values (2000, 'frontier');
do $$
declare v_status text; n int := 0; v_cursor text; v_hi text; v_child name;
begin
  select hi into v_hi from pgpm.part
   where parent_table = 'public.m99b'::regclass and attached and lo::numeric = 0;
  loop
    select regrain_cursor into v_cursor from pgpm.config where parent_table = 'public.m99b'::regclass;
    exit when v_cursor is not null and v_cursor::numeric >= v_hi::numeric;
    select child_name into v_child from pgpm.part
     where parent_table = 'public.m99b'::regclass and attached and lo::numeric = 0;
    v_status := pgpm.regrain_step('public.m99b'::regclass, v_child, '200', 50);
    n := n + 1;
    if n > 50 then raise exception 'regrain setup did not converge (last status: %)', v_status; end if;
  end loop;
  select child_name into v_child from pgpm.part
   where parent_table = 'public.m99b'::regclass and attached and lo::numeric = 0;
  v_status := pgpm.regrain_step('public.m99b'::regclass, v_child, '200', 50);
  if v_status !~ '^swapped:' then
    raise exception 'expected the swap tick, got: %', v_status;
  end if;
end $$;

select is((select restored_at is not null from pgpm.dropped_fk
            where parent_table = 'public.m99b'::regclass and referencing_table = 'public.r99b_live'::regclass),
  true, 'the live FK is restored (suspended + restored transparently within the swap, as before)');

-- THE FIX: the swap's own restore_incoming_fks call, scoped to what it suspended, must not have
-- touched r99b_stale.
select is((select restored_at is null from pgpm.dropped_fk
            where parent_table = 'public.m99b'::regclass and referencing_table = 'public.r99b_stale'::regclass),
  true, 'the swap leaves the pre-existing stale FK unrestored -- not opportunistically swept up');

select * from finish();
