-- Pre-flight refusals for from_hypertable. Tests pgpm.from_hypertable_preflight (a side-effect-free
-- function, so the refusals are savepoint-wrappable by throws_ok/lives_ok). Fixtures are loaded by the
-- harness before this file. Apache-only: pgpm targets Apache TimescaleDB, which has no continuous
-- aggregates (a TSL/Community feature), so a hypertable on the target fleet can never carry one and that
-- refusal is not exercised here. Runs in autocommit (disposable-db), like the rest of the db/ track.
select plan(5);

-- a keyed hypertable (UNIQUE on the control column) is accepted
select mk_keyed_hypertable('ph_ok');
select lives_ok(
  $$ select pgpm.from_hypertable_preflight('ph_ok', 'ts') $$,
  'preflight accepts a hypertable whose control column is in a unique constraint');

-- a keyless hypertable (no PK / unique constraint) is ALSO accepted: transmute partitions it keyless
-- (create_hypertable makes the time column NOT NULL, so the keyless contract is satisfied)
select mk_plain_hypertable('ph_keyless');
select lives_ok(
  $$ select pgpm.from_hypertable_preflight('ph_keyless', 'ts') $$,
  'preflight accepts a keyless hypertable (migrated keyless)');

-- a second (space) dimension is refused (pgpm is single-key RANGE)
select mk_hypertable_space('ph_space');
select throws_like(
  $$ select pgpm.from_hypertable_preflight('ph_space', 'ts') $$,
  'pg_partition_magician:%dimension%',
  'preflight refuses a multi-dimension (space-partitioned) hypertable');

-- An INCOMING foreign key that does not reference the key pgpm would reuse is refused HERE (issue #264),
-- before any copy work. That matters more than the usual preflight refusal: the alternative is discovering
-- it in the cutover, after the entire online copy has run, with the populated destination left orphaned.
-- Two unique keys, and the FK references the one that is NOT the reused PK.
create table public.pf_in (id bigint generated by default as identity, code text, ts timestamptz not null,
                           primary key (id, ts), unique (code, ts));
select create_hypertable('public.pf_in', 'ts');
create table public.pf_in_ref (id bigint primary key, c text, t timestamptz,
  foreign key (c, t) references public.pf_in(code, ts));
select throws_like(
  $$ select pgpm.from_hypertable_preflight('public.pf_in', 'ts') $$,
  '%references (code, ts), but the key pgpm would reuse is (id, ts)%',
  'preflight refuses an incoming FK that does not reference the key to be reused, naming both');

-- A NOT VALID outgoing key is refused too: the migration carries an outgoing key by replaying it on the
-- copy and validating it, which would either fail on rows the source never checked or silently upgrade the
-- constraint. Neither is pgpm's to decide.
create table public.pf_par (id bigint primary key);
create table public.pf_out (ts timestamptz not null, p_id bigint, v int);
select create_hypertable('public.pf_out', 'ts');
alter table public.pf_out add constraint pf_out_fk foreign key (p_id) references public.pf_par(id) not valid;
select throws_like(
  $$ select pgpm.from_hypertable_preflight('public.pf_out', 'ts') $$,
  '%are NOT VALID%',
  'preflight refuses a NOT VALID outgoing FK, with the VALIDATE CONSTRAINT remedy');

select * from finish();
-- no teardown: the harness runs each db/ test in a throwaway database (disposable-db).
