-- from_hypertable carries the migrated table's foreign keys, both directions (issue #264).
--
-- Before this, the migration lost them. OUTGOING keys went SILENTLY: `CREATE TABLE ... LIKE ... INCLUDING
-- CONSTRAINTS` copies CHECK and NOT NULL only, no INCLUDING option copies foreign keys, nothing later added
-- them, and the cutover DROPPED the source hypertable -- the only relation still holding them. The result
-- was a partitioned table with no referential integrity where the hypertable had it, no error, and nothing
-- in pgpm.log. INCOMING keys failed LOUDLY but at the worst possible moment: an FK pointing at the
-- hypertable puts a constraint on each chunk, so `drop table <source>` was refused, after the entire online
-- copy had run, leaving the populated destination orphaned behind the rollback.
--
-- from_hypertable is a procedure that COMMITs per chunk and at cutover, so it is called as a bare statement
-- (never wrapped by lives_ok/throws_ok, which use savepoints) and the result state is asserted afterwards.
-- The preflight is a side-effect-free function, so its refusals ARE savepoint-wrappable. Autocommit,
-- disposable-db.
select plan(12);

-- ============================ outgoing: carried to the PARENT ============================
create table public.fk_ref (id bigint primary key, label text);
insert into public.fk_ref values (1, 'referenced'), (2, 'also referenced');

create table public.fk_out (ts timestamptz not null, ref_id bigint not null references public.fk_ref(id), v int);
select create_hypertable('public.fk_out', 'ts');
insert into public.fk_out values (now() - interval '2 hours', 1, 10), (now() - interval '1 hour', 2, 20);

-- LIVENESS. Every "it enforces afterwards" assertion below is satisfied by a fixture that never had
-- referential integrity in the first place, so prove the hypertable enforced BEFORE the migration.
select throws_ok(
  $$ insert into public.fk_out values (now(), 999, 1) $$,
  '23503', NULL,
  'LIVENESS: the hypertable enforces its outgoing key before the migration');

call pgpm.from_hypertable('public.fk_out', 'ts', interval '1 day', p_paused => false);

-- The key must live on the PARENT, not merely on the monolith child. Carrying it onto the destination alone
-- leaves it enforcing over the monolith's range only, and a row routed into a forward partition escapes
-- entirely -- which is what happened before the parent-level adoption was added.
select is(
  (select conrelid::regclass::text from pg_constraint
    where contype = 'f' and confrelid = 'public.fk_ref'::regclass and conparentid = 0),
  'fk_out', 'the outgoing key is re-added on the PARENT, not just the monolith child');

select is(
  (select convalidated from pg_constraint
    where contype = 'f' and confrelid = 'public.fk_ref'::regclass and conparentid = 0),
  true, 'and it is VALIDATED -- the copy phase validated it off the lock, so the parent adopts it');

-- Rows survived the migration unharmed, and the valid references still resolve.
select is((select count(*)::int from public.fk_out), 2,
  'every row survived the migration');

-- Enforcement in the MONOLITH's range (the current interval lives there until the frontier crosses B).
select throws_ok(
  $$ insert into public.fk_out values (now(), 999, 1) $$,
  '23503', NULL,
  'the outgoing key enforces for a row routed into the monolith');

-- Enforcement in a FORWARD partition. This is the assertion that fails against a fix which carries the key
-- onto the destination but never re-adds it at the parent.
select throws_ok(
  format($$ insert into public.fk_out values (%L, 999, 1) $$,
         (select max(hi::timestamptz) - interval '1 hour' from pgpm.part
           where parent_table = 'public.fk_out'::regclass)),
  '23503', NULL,
  'and for a row routed into a FORWARD partition, which the monolith''s own constraint cannot cover');

select lives_ok(
  $$ insert into public.fk_out values (now(), 2, 30) $$,
  'while a VALID reference is still accepted: it enforces, rather than merely existing');

-- ============================ incoming: survives the swap ============================
create table public.fk_in (id bigint generated by default as identity, ts timestamptz not null,
                           v double precision, primary key (id, ts));
select create_hypertable('public.fk_in', 'ts');
insert into public.fk_in (ts, v) select now() - (g || ' hours')::interval, g from generate_series(1, 50) g;

create table public.fk_in_ref (id bigint primary key, r_id bigint, r_ts timestamptz,
  foreign key (r_id, r_ts) references public.fk_in(id, ts));
insert into public.fk_in_ref select 1, id, ts from public.fk_in limit 1;

-- This call used to raise `cannot drop table _hyper_N_M_chunk because other objects depend on it`.
call pgpm.from_hypertable('public.fk_in', 'ts', interval '1 day', p_paused => false);

select is(
  (select relkind::text from pg_class where oid = 'public.fk_in'::regclass),
  'p', 'the migration COMPLETES with an incoming foreign key present');

select is(
  (select conrelid::regclass::text from pg_constraint
    where contype = 'f' and confrelid = 'public.fk_in'::regclass and conparentid = 0),
  'fk_in_ref', 'the incoming key is back on the referencing table, against the new parent');

select throws_ok(
  $$ insert into public.fk_in_ref values (99, 123456789, now()) $$,
  '23503', NULL,
  'and it ENFORCES: an orphan reference is rejected');

-- The window the drop-and-re-add opens is surfaced through the core's own bookkeeping rather than hidden,
-- and it is closed by the time the migration returns.
select is(
  (select fks_suspended::int || '/' || fks_unvalidated::int from pgpm.status()
    where parent = 'public.fk_in'::regclass),
  '0/0', 'no foreign key is left suspended or unvalidated when the migration returns');

-- The old failure left <rel>_pgpm_dest behind, populated, after the rollback.
select is((select to_regclass('public.fk_in_pgpm_dest')::text), NULL,
  'and the destination is not left orphaned');

select * from finish();
