-- Fixtures for the `archive` test track (pgpm_archive against MinIO). Loaded BEFORE
-- pgpm_core/pgpm_archive are installed (test.sh's run_archive), so this file only
-- DEFINES functions and the vault stub -- any body referencing pgpm.*/archive.* is
-- plpgsql, not validated until called, and by the time a test file calls one of these
-- helpers both modules are already installed.

-- pgpm_archive's S3 hooks read credentials via `vault.decrypted_secrets` (Supabase
-- Vault's public read view). The test image is plain Postgres with no pgsodium/Vault
-- available, so stub just the one shape the module actually queries (name,
-- decrypted_secret), seeded with the MinIO root credentials test.sh's harness runs.
create schema if not exists vault;
create table if not exists vault.decrypted_secrets (
  name             text primary key,
  decrypted_secret text not null
);
insert into vault.decrypted_secrets (name, decrypted_secret) values
  ('s3_archive_access_key_id',     'minioadmin'),
  ('s3_archive_secret_access_key', 'minioadmin')
on conflict (name) do update set decrypted_secret = excluded.decrypted_secret;

-- a small bigint-id managed table: build, seed ids 1..p_rows, transmute + obtain. p_paused is
-- forwarded to transmute() (default true, matching transmute's own default) -- callers driving
-- pgpm.maintain() need p_paused => false, since maintain() no-ops entirely on a paused table.
create or replace function mk_archive_table(p_name text, p_rows int default 50000, p_step bigint default 10000, p_retain bigint default null, p_paused boolean default true)
returns void language plpgsql as $$
begin
  execute format('drop table if exists public.%I cascade', p_name);
  execute format('create table public.%I (id bigint generated by default as identity primary key, payload text)', p_name);
  execute format('insert into public.%I (payload) select %L from generate_series(1, %s)', p_name, 'x', p_rows);
  perform pgpm.transmute('public.' || p_name, 'id', p_step, p_retain => p_retain, p_paused => p_paused);
  perform pgpm.obtain('public.' || p_name);
end;
$$;

-- an archive.config row wired to the test MinIO bucket/endpoint (test.sh creates
-- archive-test-bucket via `mc mb` before any test file runs). archive.config is a plain
-- connection-settings table (issue #240 deleted the archive.configure() operator interface along
-- with the paced-worker knobs it used to also set), so this just upserts it directly.
create or replace function mk_archive_config(p_name text, p_compress boolean default false)
returns void language plpgsql as $$
begin
  insert into archive.config (parent_table, bucket, endpoint, prefix, compress)
  values (('public.' || p_name)::regclass, 'archive-test-bucket', 'http://minio:9000', p_name || '/', p_compress)
  on conflict (parent_table) do update set
    bucket = excluded.bucket, endpoint = excluded.endpoint, prefix = excluded.prefix, compress = excluded.compress;
end;
$$;
