-- Fixtures for the `archive` test track (pgpm_archive against MinIO). Loaded BEFORE
-- pgpm_core/pgpm_archive are installed (test.sh's run_archive), so this file only
-- DEFINES functions and the vault stub -- any body referencing pgpm.*/archive.* is
-- plpgsql, not validated until called, and by the time a test file calls one of these
-- helpers both modules are already installed.

-- pgpm_archive's S3 hooks read credentials via `vault.decrypted_secrets` (Supabase
-- Vault's public read view). The test image is plain Postgres with no pgsodium/Vault
-- available, so stub just the one shape the module actually queries (name,
-- decrypted_secret), seeded with the MinIO root credentials test.sh's harness runs.
create schema if not exists vault;
create table if not exists vault.decrypted_secrets (
  name             text primary key,
  decrypted_secret text not null
);
insert into vault.decrypted_secrets (name, decrypted_secret) values
  ('s3_archive_access_key_id',     'minioadmin'),
  ('s3_archive_secret_access_key', 'minioadmin')
on conflict (name) do update set decrypted_secret = excluded.decrypted_secret;

-- a small bigint-id managed table: build, seed ids 1..p_rows, transmute + obtain. p_paused is
-- forwarded to transmute() (default true, matching transmute's own default) -- callers driving
-- pgpm.maintain() need p_paused => false, since maintain() no-ops entirely on a paused table.
-- A PROCEDURE, not a function: it calls pgpm.transmute, which COMMITs (#275), and a FUNCTION cannot
-- call a committing procedure at all -- not even outside an explicit transaction block.
drop function if exists mk_archive_table(text, int, bigint, bigint, boolean);
create or replace procedure mk_archive_table(p_name text, p_rows int default 50000, p_step bigint default 10000, p_retain bigint default null, p_paused boolean default true)
language plpgsql as $$
-- v_made/v_deferred exist only to receive obtain's INOUTs: PL/pgSQL requires a WRITABLE argument for an
-- output parameter, so the parameter defaults cannot be relied on from inside a function or procedure
-- the way they can from a top-level CALL.
declare v_made int; v_deferred boolean;
begin
  execute format('drop table if exists public.%I cascade', p_name);
  execute format('create table public.%I (id bigint generated by default as identity primary key, payload text)', p_name);
  execute format('insert into public.%I (payload) select %L from generate_series(1, %s)', p_name, 'x', p_rows);
  call pgpm.transmute('public.' || p_name, 'id', p_step, p_retain => p_retain, p_paused => p_paused);
  call pgpm.obtain('public.' || p_name, v_made, v_deferred);
end;
$$;

-- an archive.config row wired to the test MinIO bucket/endpoint (test.sh creates
-- archive-test-bucket via `mc mb` before any test file runs), via the archive.configure()
-- operator interface (reintroduced, narrower than the paced-worker-era one issue #240 deleted:
-- connection settings only, no scheduling knob).
create or replace function mk_archive_config(p_name text, p_compress boolean default false)
returns void language plpgsql as $$
begin
  perform archive.configure(('public.' || p_name)::regclass, 'archive-test-bucket',
    p_endpoint => 'http://minio:9000', p_prefix => p_name || '/', p_compress => p_compress);
end;
$$;
