-- Fixtures for the `archive` test track (pgpm_archive against MinIO). Loaded BEFORE
-- pgpm_core/pgpm_archive are installed (test.sh's run_archive), so this file only
-- DEFINES functions and the vault stub -- any body referencing pgpm.*/archive.* is
-- plpgsql, not validated until called, and by the time a test file calls one of these
-- helpers both modules are already installed.

-- pgpm_archive's S3 hooks read credentials via `vault.decrypted_secrets` (Supabase
-- Vault's public read view). The test image is plain Postgres with no pgsodium/Vault
-- available, so stub just the one shape the module actually queries (name,
-- decrypted_secret), seeded with the MinIO root credentials test.sh's harness runs.
create schema if not exists vault;
create table if not exists vault.decrypted_secrets (
  name             text primary key,
  decrypted_secret text not null
);
insert into vault.decrypted_secrets (name, decrypted_secret) values
  ('s3_archive_access_key_id',     'minioadmin'),
  ('s3_archive_secret_access_key', 'minioadmin')
on conflict (name) do update set decrypted_secret = excluded.decrypted_secret;

-- a small bigint-id managed table: build, seed ids 1..p_rows, transmute + obtain.
-- Mirrors tests/58_retain_pre_drop_hook_test.sql's own hk8 setup so the partition
-- layout/boundary math in each archive test file is easy to cross-check against that
-- existing, proven pattern.
create or replace function mk_archive_table(p_name text, p_rows int default 50000, p_step bigint default 10000, p_retain bigint default null)
returns void language plpgsql as $$
begin
  execute format('drop table if exists public.%I cascade', p_name);
  execute format('create table public.%I (id bigint generated by default as identity primary key, payload text)', p_name);
  execute format('insert into public.%I (payload) select %L from generate_series(1, %s)', p_name, 'x', p_rows);
  perform pgpm.transmute('public.' || p_name, 'id', p_step, p_retain => p_retain);
  perform pgpm.obtain('public.' || p_name);
end;
$$;

-- an archive.config row wired to the test MinIO bucket/endpoint (test.sh creates
-- archive-test-bucket via `mc mb` before any test file runs), via the real operator
-- interface (archive.configure) rather than a raw insert -- overrides only the
-- columns a caller passes, everything else keeps archive.configure's own default.
create or replace function mk_archive_config(
  p_name text, p_boundary_rule text default 'partition_aligned', p_drop_trigger text default 'self_driving',
  p_format text default 'ndjson_single', p_compress boolean default false,
  p_byte_budget bigint default 8 * 1024 * 1024, p_part_bytes bigint default 8 * 1024 * 1024
) returns void language plpgsql as $$
begin
  perform archive.configure(
    p_parent        => ('public.' || p_name)::regclass,
    p_bucket        => 'archive-test-bucket',
    p_endpoint      => 'http://minio:9000',
    p_prefix        => p_name || '/',
    p_boundary_rule => p_boundary_rule,
    p_drop_trigger  => p_drop_trigger,
    p_format        => p_format,
    p_compress      => p_compress,
    p_byte_budget   => p_byte_budget,
    p_part_bytes    => p_part_bytes
  );
end;
$$;
