#!/usr/bin/env bash
# Guard obtain's back-off against outlasting the forward grid. Run by CI (`./test.sh perf`, and
# `./test.sh discriminate` proves it catches its defect).
#
# THE DEFECT. maintain_obtain() runs obtain under a 200 ms lock_timeout, and a lost race sets
# config.obtain_retry_after 30 s out so sustained write contention does not queue an ACCESS EXCLUSIVE on
# the parent every tick. The back-off predates #288, when a DEFAULT partition caught any write past the
# grid. Since #288 such a write is refused, and a fixed back-off can outlast the lookahead: a local load
# test (~42k ids/s against obtain 3 x step 200000, ~14 s of grid) lost one race, backed off 30 s, and every
# client aborted with `no partition of relation ... found for row`. The fix honors the back-off only while
# at least ceil(obtain / 2) complete partitions remain ahead of the frontier's own partition.
#
# WHY A SHELL HARNESS, GIVEN tests/100 ALREADY PROVES THE DECISION. tests/100 sets obtain_retry_after by hand.
# Only a second session holding a real lock can show the path that actually produced the outage: a genuine
# lock-timeout deferral, logged and backed off, followed by a tick that must still extend the grid.
#
# WHAT IT ASSERTS, and why each is load-bearing (step 1000, obtain 4, monolith [0,1000), grid top 5000):
#   1. + 2. LIVENESS WITNESS: the race really happened -- a skip_obtain row carrying the lock-timeout error,
#      and a back-off set in the future. Without these, every assertion below could pass against a tick
#      that never contended for anything.
#   3. The back-off still holds while headroom is ample (frontier in [2000,3000), 2 partitions ahead): the
#      next tick creates nothing even though obtain has partitions to create. A "fix" that deletes the
#      back-off fails here.
#   4. The back-off is still in the future immediately before the low-headroom tick, so assertion 5 cannot
#      pass merely because 30 s elapsed.
#   5. + 6. With headroom low (frontier in [4000,5000), 0 ahead) the tick extends the grid anyway, by identity
#      (the partition count and [8000,9000) existing), and a write at 8999 is accepted rather than refused.
#
# Usage: obtain_backoff_headroom.sh <container> <db> [install.sql]
# The install path defaults to the real one; bench/discriminate.sh passes a MUTANT copy instead, to
# prove this guard actually fails when the defect is present.
set -uo pipefail
C="${1:?container}"; DB="${2:?db}"; INSTALL="${3:-/repo/pgpm_core/install.sql}"
fail=0

q()   { docker exec "$C" psql -U postgres -d "$DB" -qtA -c "$1"; }
run() { docker exec -e PGOPTIONS='-c client_min_messages=warning' "$C" \
          psql -U postgres -d "$DB" -qtA -v ON_ERROR_STOP=1 -c "$1"; }
check() { # <label> <actual> <expected>
  if [ "$2" = "$3" ]; then printf 'PASS  %-62s %s\n' "$1" "$2"
  else printf 'FAIL  %-62s got %s, want %s\n' "$1" "$2" "$3"; fail=1; fi
}
parts() { q "select count(*) from pgpm.part where parent_table = 'public.ob_race'::regclass and attached"; }

docker exec "$C" psql -U postgres -q -c "drop database if exists $DB" >/dev/null 2>&1
docker exec "$C" psql -U postgres -q -c "create database $DB" >/dev/null 2>&1
if ! docker exec "$C" psql -U postgres -d "$DB" -q -v ON_ERROR_STOP=1 -f "$INSTALL" >/tmp/obh_install.log 2>&1; then
  echo "FAIL  install did not complete"; sed 's/^/      /' /tmp/obh_install.log; exit 1
fi

run "create table public.ob_race (id bigint generated by default as identity primary key, body text)" >/dev/null
run "insert into public.ob_race (body) select 'x' from generate_series(1, 500)" >/dev/null
run "call pgpm.transmute('public.ob_race', 'id', 1000::bigint, 4, p_paused => false)" >/dev/null
# Frontier into [2000,3000): obtain now has partitions to create, so it must take the parent's lock.
run "insert into public.ob_race (id, body) values (2001, 'frontier')" >/dev/null

# A second session holds ACCESS SHARE on the parent, which conflicts with obtain's ACCESS EXCLUSIVE.
docker exec "$C" psql -U postgres -d "$DB" -qtA \
  -c "begin; lock table public.ob_race in access share mode; select pg_sleep(4); commit;" >/dev/null 2>&1 &
holder=$!
for _ in $(seq 1 50); do
  held=$(q "select count(*) from pg_locks l join pg_class c on c.oid = l.relation
             where c.relname = 'ob_race' and l.mode = 'AccessShareLock' and l.granted and l.pid <> pg_backend_pid()")
  [ "$held" -gt 0 ] 2>/dev/null && break
  sleep 0.1
done
run "call pgpm.maintain_obtain('public.ob_race')" >/dev/null
wait "$holder"

RACED=$(q "select exists (select 1 from pgpm.log where parent_table = 'public.ob_race'::regclass
                            and action = 'skip_obtain' and method like '%lock timeout%')")
check "the lock race really happened: skip_obtain with a lock timeout" "$RACED" "t"
BACKED=$(q "select obtain_retry_after > clock_timestamp() from pgpm.config where parent_table = 'public.ob_race'::regclass")
check "the deferral set a back-off in the future" "$BACKED" "t"

# Lock released, 2 partitions still ahead: the back-off must hold.
run "call pgpm.maintain_obtain('public.ob_race')" >/dev/null
check "ample headroom: the back-off holds, nothing created" "$(parts)" "5"

# Frontier into [4000,5000): nothing left ahead of it.
run "insert into public.ob_race (id, body) values (4001, 'frontier')" >/dev/null
STILL=$(q "select obtain_retry_after > clock_timestamp() from pgpm.config where parent_table = 'public.ob_race'::regclass")
check "the back-off is still in the future before the low-headroom tick" "$STILL" "t"

run "call pgpm.maintain_obtain('public.ob_race')" >/dev/null
check "low headroom: the tick extends the grid through the back-off" "$(parts)" "9"
if run "insert into public.ob_race (id, body) values (8999, 'past the old top')" >/tmp/obh_insert.log 2>&1; then
  check "a write at 8999, past the old grid top of 5000, is accepted" "accepted" "accepted"
else
  check "a write at 8999, past the old grid top of 5000, is accepted" "rejected: $(tail -1 /tmp/obh_insert.log | cut -c1-60)" "accepted"
fi

exit "$fail"
