-- Load-test schema for the from_hypertable track: bench.events is a TimescaleDB HYPERTABLE
-- (time-partitioned on created_at, Apache edition), the shape from_hypertable migrates to pgpm-managed
-- native declarative partitioning under live load.
--
-- KEYED on purpose (PK includes the time control column, id leads for identity), because:
--   * it is the realistic OLTP shape, and
--   * the full-online path (p_track_changes) reconciles in-flight UPDATE/DELETE by the PK, so a usable
--     key must exist (a keyless hypertable refuses track_changes).
-- The hypertable's chunk width is passed by the harness as :chunk_interval (independent of pgpm's
-- partition width, which from_hypertable takes as p_interval at conversion time).
create extension if not exists timescaledb;
create schema if not exists bench;

create table if not exists bench.users (
  id         int  generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

-- The migration candidate. ~400 B incompressible heap rows, so it reaches the target size at a
-- predictable row count, the same anchor the id-track bench uses.
create table if not exists bench.events (
  id         bigint   generated by default as identity,
  created_at timestamptz not null default now(),
  user_id    int      not null,
  kind       smallint not null,
  payload    text     not null,
  -- Timescale forbids a PK/unique constraint that excludes the partition column, so created_at is IN the
  -- key; id leads so identity continuity is exercised and the key reuse at transmute is meaningful.
  primary key (id, created_at)
);
select create_hypertable('bench.events', 'created_at',
  chunk_time_interval => :'chunk_interval'::interval, if_not_exists => true);

-- the lookup index a real app keeps: a user's recent activity. On a time-partitioned table the hot read
-- is "recent rows for a user", so the index leads user_id then created_at desc (prunes to recent chunks/
-- partitions before and after the migration).
create index if not exists events_user_id_idx on bench.events (user_id, created_at desc);

-- a small companion the workload also writes
create table if not exists bench.user_seen (
  user_id    int primary key,
  last_event bigint,
  seen_at    timestamptz not null default now()
);

-- seed a modest user population
insert into bench.users (name)
select 'user_' || g from generate_series(1, 50000) g
on conflict do nothing;
