-- =============================================================================
-- 01. Legacy starting state: a single, large, UNPARTITIONED `messages` table.
--
-- This is the "before" picture -- what a multi-tenant app accumulates over time.
-- Later migrations convert this in place into a time-partitioned table with no
-- up-front data movement, by attaching it as the DEFAULT partition.
-- =============================================================================

create table public.messages (
  id          bigint      generated by default as identity,
  tenant_id   uuid        not null,
  created_at  timestamptz not null default now(),
  body        text        not null,
  constraint messages_pkey primary key (id)
);

-- Tenant-scoped lookups are served by an INDEX, not by partitioning.
-- (Strategy conclusion from the design doc: "partition for lifecycle, index for
-- lookups.")
create index messages_tenant_created_idx
  on public.messages (tenant_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Deterministic data generator.
--
-- Spreads `p_count` rows across the last `p_months` calendar months for a small
-- fixed set of synthetic tenants. Uses generate_series + a hash so reseeds are
-- stable (no reliance on random()).
-- ---------------------------------------------------------------------------
create or replace function public.generate_messages(
  p_count  int default 50000,
  p_months int default 6
)
returns bigint
language plpgsql
as $$
declare
  v_tenants uuid[] := array[
    '00000000-0000-0000-0000-0000000000a1',
    '00000000-0000-0000-0000-0000000000a2',
    '00000000-0000-0000-0000-0000000000a3',
    '00000000-0000-0000-0000-0000000000a4',
    '00000000-0000-0000-0000-0000000000a5'
  ]::uuid[];
  -- First day of the month (p_months - 1) months ago, so the window set is
  -- exactly p_months months ending in the current (partial) month.
  v_start timestamptz := date_trunc('month', now()) - make_interval(months => p_months - 1);
  v_span  interval    := now() - v_start;
begin
  insert into public.messages (tenant_id, created_at, body)
  select
    v_tenants[1 + (g % array_length(v_tenants, 1))],
    v_start + v_span * (((g::bigint * 2654435761) % 1000000)::double precision / 1000000.0),
    'message body #' || g
  from generate_series(1, p_count) as g;

  return p_count;
end;
$$;
