-- =============================================================================
-- DEMO: the other two partitioning dimensions.
--
--   events_id   -- bigint identity, partitioned by integer RANGE on the id
--                  (the Snowflake-style case: id is monotonic with insertion)
--   events_uuid -- uuid, partitioned by a time grid encoded into uuidv7 bounds
--                  (also covers ULID-stored-as-uuid)
--
-- Both are seeded BEFORE adoption and left with maintenance paused, like the
-- time `messages` demo.
-- =============================================================================

-- ---- integer/id dimension --------------------------------------------------
create table public.events_id (
  id      bigint generated by default as identity primary key,
  payload text not null
);
insert into public.events_id (payload)
  select 'evt ' || g from generate_series(1, coalesce(current_setting('poc.events_count', true)::int, 45000)) g;
analyze public.events_id;

-- step = 10,000 ids per partition; keep 2 ahead
select pgpm.adopt_by_id('public.events_id', 'id', p_step => 10000, p_premake => 2, p_drain_batch => 5000);

-- ---- uuidv7 dimension ------------------------------------------------------
create table public.events_uuid (
  id      uuid primary key,
  payload text not null
);
-- seed uuidv7-shaped ids: 48-bit ms prefix (spread across the last 6 months) +
-- random low bits for uniqueness. PG 15 has no uuidv7() generator, so we build them.
insert into public.events_uuid (id, payload)
select
  (substr(h,1,8)||'-'||substr(h,9,4)||'-'||substr(h,13,4)||'-'||substr(h,17,4)||'-'||substr(h,21,12))::uuid,
  'evt ' || g
from (
  select g,
    lpad(to_hex(floor(extract(epoch from (
        (date_trunc('month', now()) - make_interval(months => 5))
        + (now() - (date_trunc('month', now()) - make_interval(months => 5)))
          * (((g::bigint * 2654435761) % 1000000)::double precision / 1000000.0)
    )) * 1000)::bigint), 12, '0')
    || substr(replace(gen_random_uuid()::text, '-', ''), 13) as h
  from generate_series(1, coalesce(current_setting('poc.events_count', true)::int, 45000)) g
) s;
analyze public.events_uuid;

-- monthly time grid, encoded as uuid boundaries; keep 2 ahead
select pgpm.adopt_by_uuidv7('public.events_uuid', 'id', p_interval => '1 month', p_premake => 2, p_drain_batch => 5000);
