-- =============================================================================
-- 03. Core choreography: convert the existing unpartitioned table into a
--     RANGE(created_at) partitioned table with ZERO data movement up front,
--     by attaching the existing table as the DEFAULT partition.
--
-- Caveats surfaced deliberately (see README):
--   * A partitioned table's PRIMARY KEY must INCLUDE the partition key, so the
--     enforced PK becomes (created_at, id); `id` alone is no longer DB-unique.
--   * The DEFAULT partition needs a unique index matching the parent PK before
--     it can be attached. At production scale build it with
--     CREATE UNIQUE INDEX CONCURRENTLY (outside a txn); non-concurrent is fine
--     at POC scale.
-- =============================================================================

-- 1. Rename the live table out of the way. It keeps ALL of its data.
alter table public.messages rename to messages_default;
alter index public.messages_tenant_created_idx rename to messages_default_tenant_created_idx;

-- 2. The partitioned parent's PK must include the partition key (created_at), so
--    the old single-column PK on (id) cannot carry over. Drop it (this is the
--    documented trade-off: id alone is no longer DB-unique). A partition also may
--    not own a competing PRIMARY KEY when attached to a PK'd parent.
alter table public.messages_default drop constraint messages_pkey;

-- Identity belongs on the parent only; drop the child's so it inherits cleanly,
-- but keep id NOT NULL for the composite PK.
alter table public.messages_default alter column id drop identity if exists;
alter table public.messages_default alter column id set not null;

-- Build the composite unique index the parent PK will adopt for this partition.
create unique index messages_default_created_id_uidx
  on public.messages_default (created_at, id);

-- 3. Create the partitioned parent, reusing the ORIGINAL name so the application
--    sees no change.
create table public.messages (
  id          bigint      generated by default as identity,
  tenant_id   uuid        not null,
  created_at  timestamptz not null default now(),
  body        text        not null,
  primary key (created_at, id)   -- includes the partition key
) partition by range (created_at);

create index messages_tenant_created_idx
  on public.messages (tenant_id, created_at desc);

-- 4. Attach the existing table as the DEFAULT partition. No rows move; the
--    existing composite unique index satisfies the parent PK for this partition.
alter table public.messages attach partition public.messages_default default;

-- 5. New inserts through the parent use the parent's identity sequence. Advance
--    it past the largest existing id so live writes never collide with seeded
--    rows.
select setval(
  pg_get_serial_sequence('public.messages', 'id'),
  (select coalesce(max(id), 0) + 1 from public.messages_default),
  false
);

-- 6. Pre-create EMPTY partitions for upcoming months. Future ranges have no rows
--    in DEFAULT yet, so attaching them is conflict-free and brand-new future
--    writes route straight to proper partitions ("hot data benefits first").
--    The current month is skipped: DEFAULT still holds current-month rows, so a
--    proper partition for it can only be created once those rows are drained
--    (handled by the drain engine in 04).
do $$
declare
  v_cur date := date_trunc('month', now())::date;
  i     int;
  lo    date;
  hi    date;
  part  text;
begin
  for i in 1..2 loop  -- next month and the month after
    lo   := (v_cur + make_interval(months => i))::date;
    hi   := (v_cur + make_interval(months => i + 1))::date;
    part := 'messages_' || to_char(lo, 'YYYY_MM');
    execute format(
      'create table public.%I partition of public.messages for values from (%L) to (%L)',
      part, lo, hi
    );
  end loop;
end;
$$;
